### ISSUE TITLE
Unpickling stan models

### ISSUE THREAD

**Issue by karlnapf** [stan-dev/pystan#103]
Hi there,

I run something like this:
```
while(True):
    print "unpickle"
    f = open(fname)
    pickle.load(f)
    f.close()
```

and it fills up my hard-drive, in a quite fast rate. I cannot figure out where those files are, as they are neither in ```/home/heiko``` nor in ```/tmp```

Any ideas?

**Comment by ariddell** [comment]
Rethinking pickling is going to have to wait until after the Stan 3.0 refactor.
