### ISSUE TITLE
get_posterior_mean produces AssertionError

### ISSUE THREAD

**Issue by rgerkin** [stan-dev/pystan#107]
After a successful fit, which I can also summarize with print or fit.summarize, I cannot do:  

```
In [8]: fit.get_posterior_mean()
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-8-fc16b8a70f38> in <module>()
----> 1 fit.get_posterior_mean()

/var/folders/s7/z8gkty4j35s_wrtgxqyznzpw0000gn/T/tmpvFbnY9/pystan/stanfit4anon_model_0eafada6cac1184224f2661613f71c7f_8eb7b01971cf54428ea967dd27d7fad9.so in stanfit4anon_model_0eafada6cac1184224f2661613f71c7f_8eb7b01971cf54428ea967dd27d7fad9.StanFit4anon_model_0eafada6cac1184224f2661613f71c7f.get_posterior_mean (/var/folders/s7/z8gkty4j35s_wrtgxqyznzpw0000gn/T/tmpvFbnY9/pystan/stanfit4anon_model_0eafada6cac1184224f2661613f71c7f_8eb7b01971cf54428ea967dd27d7fad9.cpp:12504)()

AssertionError: 
```

Checking the code, there is an `assert len(fnames) == len(mean_pars)` in get_posterior_mean in stanfit4model.pyx.  

Just above that:  

```
mean_pars = np.array([ch['mean_pars'] for ch in self.sim['samples']])
mean_pars = np.column_stack(mean_pars)
```

where `self` is the fit.  This will work if the value for 'mean_pars' in each chain has the same length as fnames.  For some reason in the fit I have done it is empty, i.e. None.  There is nothing odd about the sample chain, and the summary prints reasonable statistics of the distribution.  It seems that mean_pars was never calculated for these chains.

**Comment by chmullig** [comment]
+1 running into this. What's the intended workaround?

**Comment by ariddell** [comment]
Let me see if I can't figure out what's going on. Short term fix is probably just to calculate the means from the samples directly.

**Comment by chmullig** [comment]
Thanks. A few more details, if they're helpful: OS X 10.10.4. PyStan 2.7. Currently running in IPython notebook, but I think I had the same problem earlier with normal python. Error is:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-109-e65809c622e0> in <module>()
    ----> 1 self.fit.get_posterior_means()
    
    AttributeError: 'stanfit4multilevel_d5c49202c71519239e950e5a423425c' object has no attribute 'get_posterior_means'

**Comment by ariddell** [comment]
Workaround is to add ``mean_pars`` to the list of attribute names on line 102 of stanfit4model.pyx
