### ISSUE TITLE
scikit-learn integration

### ISSUE THREAD

**Issue by rgerkin** [stan-dev/pystan#122]
I've started testing a subclass of sklearn.base.Estimator that wraps StanModel functionality so that the full suite of scikit-learn tools can be used with Stan models, including GridSearch, Pipeline, etc.  I'd post about it in the stan dev mailing list but I don't have post access yet.  Does anyone have any thoughts on this (i.e. does anyone else use scikit-learn?)

**Comment by rgerkin** [comment]
It's up [here](https://github.com/rgerkin/pystan-sklearn).  I show an example of how scikit-learn classes can be used to do a grid search over the eight schools model hyperparameters to find the value with the best predictive power.

**Comment by ariddell** [comment]
This is great! I'm looking forward to trying it out.
