### ISSUE TITLE
memory explosion when using multiple models or named model with os x mavericks

### ISSUE THREAD

**Issue by jhuggins** [stan-dev/pystan#132]
When using OS X mavericks, there appears to be a memory leak related to the use of named models. In particular, the memory leak can be triggered by either (a) creating a named model and calling `sampling` or (b) creating two models (they don't need to be named) and calling `sampling` on either one. 

the same bug was previously observed, but seemed to have been resolved: https://github.com/stan-dev/pystan/issues/10

**Comment by ariddell** [comment]
I'm going to close this because I think it's best addressed after the new Stan 3.0 interface is finished (hopefully soon).

**Comment by ariddell** [comment]
I think this may be fixed in develop shortly.
