### ISSUE TITLE
Eight Schools link in docs is broken

### ISSUE THREAD

**Issue by rgerkin** [stan-dev/pystan#135]
The link to the eight schools example code here:  

http://pystan.readthedocs.org/en/latest/getting_started.html

is broken.  The current link was provided by me, but is now broken again, and I can't even find the eight schools code anywhere in the main Stan repo.  I'd just add it elsewhere but I'm not sure if it was taken out for a reason.

**Comment by syclik** [comment]
The correct link is here:
https://raw.githubusercontent.com/stan-dev/example-models/master/misc/eight_schools/eight_schools.stan

All of our examples have been moved to the example-models repository.

**Comment by rgerkin** [comment]
Thanks, I just fixed the link and submitted a pull request.

**Comment by syclik** [comment]
Thank you! That was really fast.
