### ISSUE TITLE
malloc error during compilation

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#137]
> When I try to fit the attached model, I get the following error:
> 
> INFO:pystan:COMPILING THE C++ CODE FOR MODEL 
> tdsz_lr_talk_763787ac780aba381abd865d0dac4abb NOW.
> python(2242,0x7fff75c03300) malloc: *** error for object 0x1069cb720: 
> pointer being freed was not allocated
> *** set a breakpoint in malloc_error_break to debug
> /Users/noahsilbert/anaconda/bin/python.app: line 3:  2242 Abort trap: 6     
>       /Users/noahsilbert/anaconda/python.app/Contents/MacOS/python "$@"

model:

```
data {
    int<lower=0> ntr; // number of trials per subject
    int<lower=0> nsb; // number of subjects
    int<lower=0> ntk; // number of stim talkers (20)
    int<lower=0> nsc; // number of stim categories (4)
    int<lower=0,upper=1> y[nsb,ntr]; // correct, incorrect dv
    int<lower=1> tk[nsb,ntr]; // talker indices
    int<lower=1> st[nsb,ntr]; // stim cat indices
    int<lower=1> sb[nsb]; // subject indices
}
parameters {
    real alpha[nsc,ntk]; // stim x talker pars
    real mu_a[nsc]; // stim cat means
    real<lower=0.001> sg_a[nsc]; // stim cat SDs
    real beta[nsb]; // subject pars
    real mu_b; // subject mean
    real<lower=0.001> sg_b; // subject SD
}
model {
    // data model
    for(sbi in 1:nsb)
        for(tri in 1:ntr)
            y[sbi,tri] ~ bernoulli(inv_logit(beta[sb[sbi]] + alpha[st[sbi,tri],tk[sbi,tri]]));
    
    // model model
    for(sti in 1:nsc)
        alpha[sti] ~ normal(mu_a[sti],sg_a[sti]);
    
    beta ~ normal(mu_b,sg_b);
    
    // priors
    mu_a ~ normal(0,1);
    sg_a ~ gamma(2,4);
    mu_b ~ normal(0,1);
    sg_b ~ gamma(2,4);
}
```

**Comment by noahmotion** [comment]
Just to follow up on this error and Allen's questions about it ([here](https://groups.google.com/forum/#!topic/stan-users/cHbj68VfMYc)), it is sporadic. It has happened a few times right after the model is compiled (and possibly before it's done compiling the model, since at least once I've gotten that error and then been unable to load a pickled model successfully). It has also happened after sampling was done (or nearly so). Other times, it doesn't happen at all.

I first noticed it on a Mac Pro, but then it happened on a macbook air, too. It may have happened on an iMac I left running over the weekend, but I don't know for sure (this morning it looked like the computer had crashed and rebooted, but I don't know if it was related to this problem or the fact that I had all four cores running chains, which (I think) has caused crashes before). It *seems* like it happens more consistently on the Mac Pro, but I can't say for sure if that's the case.

Thus far, I don't see any obvious pattern. I'll update if I run into the problem again or if I get any new insights into what's going on.

**Comment by ariddell** [comment]
I'll close this for now. Please reopen if you manage to reproduce it.

**Comment by noahmotion** [comment]
I've got a new model (and dataset), and I'm getting the same error every time I try to fit it. It compiles fine, but attempts to get samples (on either a Mac Pro or an iMac, running PyStan 2.6.3) produce this:

    python(89577,0x7fff7656c300) malloc: *** error for object 0x10c2e0720: pointer being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug
    /Users/noahsilbert/anaconda/bin/python.app: line 3: 89577 Abort trap: 6
    /Users/noahsilbert/anaconda/python.app/Contents/MacOS/python "$@"

Here's the model:

    data {
        int<lower=0> ntps; // number of trials per subject
        int<lower=0> nsub; // number of subjects
        int<lower=0> ntlk; // number of stim talkers (8)
        int<lower=0> nstm; // number of stim categories (4)
        int<lower=0> npred; // number of predictors
        int<lower=0,upper=1> y[nsub,ntps]; // correct, incorrect dv
        int<lower=1> talk[nsub,ntps]; // talker indices
        int<lower=1> stim[nsub,ntps]; // stim cat indices
        row_vector[npred] preds[nsub]; // array of by-sub predictor vectors, inc. intercept
        matrix[npred,npred] W; // identity matrix
    }
    transformed data{
        int nu;
        nu <- npred + 1;
    }
    parameters {
        vector[ntlk] Btk; // talker-specific betas
        vector[nstm] Bst; // stim-specific betas
        vector[npred] Msb; // mean of sub-specific betas
        vector[npred] Asb[nsub]; // subject-specific alphas
        vector<lower=0>[npred] tau; // scale for Ssb
        cholesky_factor_corr[npred] Lsb; // chol for Ssb
    }
    transformed parameters {
        vector[npred] Bsb[nsub]; // subject-specific betas
        vector[ntlk] Btkc; // centered talker-specific betas
        vector[nstm] Bstc; // centered stim-specific betas
        for(sbi in 1:nsub)
            Bsb[sbi] <- Msb + diag_pre_multiply(tau,Lsb)*Asb[sbi];
        // center talker and stim specific betas
        Btkc <- Btk - mean(Btk);
        Bstc <- Bst - mean(Bst);
    }
    model {
        // data model
        for(sbi in 1:nsub)
            for(tri in 1:ntps)
                y[sbi,tri] ~ bernoulli(inv_logit(Btk[talk[sbi,tri]] + Bst[stim[sbi,tri]] + preds[sbi]*Bsb[sbi]));
        
        // model model
        Btk ~ normal(0,1);
        Bst ~ normal(0,1);
    
        tau ~ gamma(2,4);
        Msb ~ normal(0,1);

        for(bi in 1:nsub) 
            Asb[bi] ~ normal(0,1);
    }

**Comment by ariddell** [comment]
@noahmotion Thanks for following up. My sense is that a malloc error during compilation should probably be investigated separately from a malloc error during sampling since it's safe to assume they're likely different errors.

If the error is happening consistently on all Macs I'd be willing to try debugging it on a Mac with ``gdb`` (or whatever it is that Apple has blessed for such things).

I've reopened the issue -- hopefully someone else will experience the problem or will know how to debug it on OS X.

**Comment by noahmotion** [comment]
Given how the new model is behaving (or, I suppose, failing to behave), I now wonder if the previous error was during compilation or not. I seems like the new issue is the same as the old one, though my memory of the older issue is a bit hazy.

I'll try the model out on my laptop, too, just to make sure it's happening on all the Macs I have access to.

**Comment by ariddell** [comment]
If it is occurring on all macs let me know and, if you wouldn't mind, please either (1) include some (fake) data here (maybe use JSON.dumps) or (2) email me a pickle file at abr at ariddell dot org?

**Comment by Volodymyrk** [comment]
Happens to me all the time (looks similar, not sure if it is the same issue). 
Code example is on SO:
http://stackoverflow.com/questions/37379761/pystan-os-x-el-capitan-malloc-error-for-object-0x117e956e0

**Comment by ariddell** [comment]
Thanks fort the pointer. Do you have Stan program code + data which will always cause the error?

**Comment by ariddell** [comment]
Closing for now due to lack of a reproducible case.
