### ISSUE TITLE
stan/agrad/rev/var_stack_def.hpp missing

### ISSUE THREAD

**Issue by flimao** [stan-dev/pystan#139]
Hi,

I'm trying to compile PyStan in a Python 3.4 x64, Windows 8.1 setup:

```
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:45:13) [MSC v.1600 64 bit (AMD64)] on win32
```

After setting up the build environment (Windows SDK v7.1), cloning both PyStan and Stan, and running `setup.py install`, the following error shows:

```bash
pystan/_chains.cpp(242) : fatal error C1083: Cannot open include file: 'stan/agrad/rev/var_stack_def.hpp': No such file or directory
```

Indeed, `var_stack_def.hpp` is not present in that directory.

Anyone more knowledgeable than me knows what's going on?

Cheers,
Limão

**Comment by syclik** [comment]
Hi Limão,

If you're cloning PyStan from GitHub, you'll need to update Stan to the
commit hash configured by that particular version of PyStan.

Stan has moved quite a bit since that tagged version and the current
version of develop is clearly incompatible with the version of PyStan that
you've cloned.

There should be directions somewhere to update the Stan submodule.



Daniel

**Comment by ariddell** [comment]
Hi @flimao, I suspect you might need to do a ``git clone --recursive`` if you're building from source. PyStan doesn't keep a copy of the Stan source code (although it used to).

**Comment by flimao** [comment]
@syclik I tried to `git reset` to the correct commit hash, but that particular file is still missing. I'll try to do  what @ariddell said.

Cheers!

**Comment by syclik** [comment]
Yes, do what @ariddel has said. A `git reset` isn't going to really set it
to any particular hash. If you're already on develop, it'll stay there.

**Comment by flimao** [comment]
@syclik As you can probably tell, I'm not so familiar with git :)

**Comment by flimao** [comment]
So, it worked. I no longer get that particular error message. 

I'm getting another error message, though. I'll open another issue thread.

@ariddell and @syclik, thanks for the help!

Cheers,
Limão

**Comment by ariddell** [comment]
No problem. Glad to have someone trying out Windows compilation.
