### ISSUE TITLE
Trouble installing Pystan 2.6 on OS X Yosemite

### ISSUE THREAD

**Issue by Auerilas** [stan-dev/pystan#145]
Following from the stan users group, I'm having trouble installing Pystan v 2.6.0 on OS X Yosemite. I get the error message:

Warning: Can't read registry to find the necessary compiler setting

Make sure that Python modules _winreg, win32api or win32con are installed.

This happens whether I'm using pip or installing from source. I've tried deleting all references to early Pystan versions, which did not resolve the issue.

**Comment by ariddell** [comment]
I think that Warning may not be the cause of the exception. (I could be wrong about this though).

I realize I forgot to push the OS X wheels to PyPI. Let's see if doing that fixes the problem. (Might take a day or so for travis-ci to get everything right: https://travis-ci.org/ariddell/lda-wheel-builder )

**Comment by Auerilas** [comment]
Sounds good. I’ll give it a day or two and let you know if I get it to work

**Comment by ariddell** [comment]
Building wheels didn't encounter any problems, so they should be up on PyPI now.
The OS X wheels are built (and tested) on OS X 10.9. But they should install without problem on OS X 10.10

**Comment by Auerilas** [comment]
That didn’t do it. Here’s the full log, maybe the answer is in there somewhere? I think I only gave a portion of it on the STAN mailing list. I’m curious to know if I’m the only one with this issue or if others with OS X 10.9/10.10 are having similar problems.

**Comment by ariddell** [comment]
Can you try posting the full log again? I don't see it.

**Comment by Auerilas** [comment]
It won't let me upload a txt file and the log is longer than the maximum file size. I put it up on one of my github sites: https://github.com/Auerilas/ecopy-data

It's log.txt

**Comment by ariddell** [comment]
What version of pip are you using? Do you happen to know what version of setuptools is installed?

**Comment by Auerilas** [comment]
I think it’s pip 1.4 and setup tools 7.0

pip --version
pip 1.4.1 from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages

Python 2.7.6 (default, Nov 19 2013, 19:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'7.0'
>>>

**Comment by Auerilas** [comment]
I just upgraded pip to the newest version and got the Pystan install to work.

I had no idea my pip was so out of date

**Comment by ariddell** [comment]
Thanks for the report. This is useful information. Seems like we should make a recent version of pip/setuptools a hard requirement.
