### ISSUE TITLE
Compiled Stan model should not depend on Python.h

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#150]
Insofar as one wants to sling around compiled Stan models as ``.so`` files to avoid waiting for compilation, it would be great if a single Stan model could be compiled for both Python 2 and Python 3.

This is possible if PyStan only accesses the compiled ``.so.`` via ctypes. I believe it's just the interrupt callback that currently depends on Python.h. See: https://bitbucket.org/pypa/wheel/issue/100/binary-wheels-for-different-python

**Comment by bob-carpenter** [comment]
That's a little to Pythonic for me.  What's a ctype?  

The compiled model itself shouldn't depend on interrupts
anywhere --- those are coming in from optimization (maybe)
and HMC (definitely).

- Bob

**Comment by ariddell** [comment]
I guess the issue isn't too clear. When I say Stan model I mean the
PyStan-wrapped Stan model -- that very particular '.so'.

And now that I've thought about this a bit more, I'm not sure getting a
shared object library that doesn't depend on a particular version of
Python is possible. It would be nice to have though.
