### ISSUE TITLE
using init gives error “bad lexical cast”

### ISSUE THREAD

**Issue by steven-murray** [stan-dev/pystan#151]
When running the example in the docstring of pystan.stan, specifically ``exfit0 = stan(model_code=excode, init=initfun1)``, I get the error:

    terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_lexical_cast> >'
    what():  bad lexical cast: source type value could not be interpreted as target

Using pystan 2.6.3.0 on Mac OSX

**Comment by ariddell** [comment]
Thanks for the report. I'm not sure what's going on here. Perhaps an OS X user has encountered this error? (I just ran the code snippet on Linux with 2.6.3.0 and didn't get the error.)

**Comment by ariddell** [comment]
If someone else can reproduce this. Please re-open.

**Comment by ariddell** [comment]
Perhaps someone can reproduce this error? From the stan-users list:

```
import pystan

model_code = '''
data { }
parameters { real mu; }
model { mu ~ normal(0, 1); }
'''

def init_params(chain_id=1):
    return {'mu' : 0.1}

fit = pystan.stan(
    data = {},
    model_code = model_code,
    iter = 2000,
    warmup = 1000,
    chains = 1,
    n_jobs = 1,
    init = init_params
)
```

**Comment by edbaskerville** [comment]
That was me on the stan-users list. Here's my Clang version information:

Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0

**Comment by edbaskerville** [comment]
I noticed PyStan 2.7.0 was out and tried again, same error. Does this work with Clang on Linux?

**Comment by ariddell** [comment]
Hi,

Yes, we test against gcc and clang on linux. There's some testing against OS X 10.9 and clang as well.

It's certainly a strange error. I suppose the next step is to do some C debugging to find out what exactly is being inappropriate cast according to clang.

**Comment by ariddell** [comment]
FWIW, I just checked with OS X, gcc, and 2.7.0.0 and it worked.

**Comment by ariddell** [comment]
@edbaskerville any chance you could give this a shot with the newest Cython 0.23.1 and PyStan 2.7.0.1?
