### ISSUE TITLE
Variational method

### ISSUE THREAD

**Issue by maedoc** [stan-dev/pystan#163]
Stan has a recently added feature to use variational approximate inference, and it's supported with CmdStan through e.g. `./model variational data file=bla.temp.R`.

**Comment by ariddell** [comment]
You're right!
When RStan supports it, PyStan will follow quickly. (see https://github.com/stan-dev/rstan/issues/171)

**Comment by nfoti** [comment]
I've fixed a couple of bugs in some existing code that wrapped the ADVI method in Stan. The algorithm seems to run, however, the results of the algorithm are not returned to Python. I was only able to dig down so far, however, from a discussion with @ariddell and looking at the RStan issue it seems like ADVI just writes its results to file. I'm not very familiar with the code yet to know if we are able to access those results, so we may be stuck until the ADVI code is refactored.

**Comment by maedoc** [comment]
I believe this was the conclusion on the Stan mailing list when the same request was made for R. Parsing the ADVI ascii output is trivial but has some overhead. Perhaps the ADVI output method takes an `ostream` which could override the `<<` to put results directly into a NumPy array.

**Comment by ariddell** [comment]
If the results can be put in any C++ data structure, it's easy to return them as a numpy array to the user. If someone wants to write the code to parse the ADVI ascii output separately that would work as well.

@nfoti In the short term, we just need a simple ``vb`` method, with a bunch of warnings that the api experimental, that requires a filename for output, right? Or maybe that returns the filename which ADVI chooses?

**Comment by syclik** [comment]
If you're willing to wait a week, we might have the issue of it getting back to PyStan fixed. Most of the refactor is done.

**Comment by nfoti** [comment]
I'm willing to wait a bit if the refactor is almost done rather than parsing the files created during execution.

**Comment by akucukelbir** [comment]
i'm just seeing this guys. thanks so much for staying on top of this guys.

@syclik also, do i need to do anything re: the refactor?

**Comment by jeffalstott** [comment]
Hello all,

Is it still the case that Pystan does not have an interface to Stan's variational Bayes capabilities? Or did this develop further under a different issue?

**Comment by gioelelm** [comment]
Hi, 
I was also wondering if we will get ADVI any soon. We are almost one year behind RStan  for this feature. 
No complain meant and I really appreciate your work, just trying to understand wether I should wait for the feature at all or find another solution.

**Comment by ariddell** [comment]
It's an experimental feature right now in RStan/CmdStan. There will be some (minimal) support in the next version of PyStan and hopefully much more as time goes on.

**Comment by mynameisfiber** [comment]
Could we have the code for variational merged into master and simply have a warning that this is an experimental feature?

**Comment by ariddell** [comment]
There's no code to be merged yet. The current state of things is here: https://github.com/stan-dev/pystan/tree/feature/vb-support

If you're interested, we could certainly use help on this.

**Comment by mynameisfiber** [comment]
@ariddell Cool... it'd be easier to contribute if there were an open pull request listing what's been done and what needs to be done. I was under the impression that `feature/advi` was the most up-to-date branch with advi support since it has the most recent commit. Regardless, I'd love to help.

**Comment by ariddell** [comment]
This is about to be fixed, albeit in a very specific sense of "fixed", in #235. In order to get samples from the ADVI posterior, you need to specify a sample file and read the data out of that.

**Comment by cdipaolo** [comment]
@ariddell Hey with regards to the comment above about reading data from the sample file directly, will PyStan ever return this directly to the user? I'm currently doing some relatively janky munging to get this to work:
```py
 def read_sampling_csv(filepath, verbose=False):
     samp = pd.read_csv(filepath, skiprows=[0,1,2,3,5,6])
     if verbose:
         print('[info] read sampling csv file')
     v = [tuple(k.split('.')) for k in samp]
     shapes = {k[0]: list(np.zeros(len(k), dtype=int)) for k in v}
     for k in v:
         shapes[k[0]] = tuple(
             max(int(shapes[k[0]][i]), int(val)) for i, val in enumerate(k[1:])
         ) + (len(samp['.'.join(k)]),)
     samples = {k: np.zeros(shape) for k, shape in shapes.items()}
     for key, val in samp.items():
         k = key.split('.')
         samples[k[0]][tuple(int(i)-1 for i in k[1:])] = val.as_matrix()
     return {
         k: np.moveaxis(samples[k], -1, 0) for k in samples
     }
```
I'm currently using this for LDA with a not-huge number of small documents (3000 documents and probably <8000 words) but have run into similar issues with other models featuring large numbers of parameters. The `vb` sampler converges quickly but this takes a _**long**_ time to run when the sampling file is ~1.1G. As you can see from the above all I care about is an equivalent to `fit.extract()` but if `model.vb` returned the same `StanFit4Model` that `model.sampling` does that'd be awesome.

**Comment by ariddell** [comment]
re: sensible support for VB in PyStan (without going through CSV): Yes! It will not be in the next release but will likely be in the release after that (thanks to the amazing work of @syclik in #282)

re: specific uses of VB: I'd post the question to stan-users

Thanks for being patient.

(I'm reopening this and will close it when #282 gets merged)

**Comment by syclik** [comment]
I need to get on it. I'm assigning myself.

**Comment by ariddell** [comment]
We just need to add a test after the refactor is merged, I believe. Right @syclik ?

**Comment by syclik** [comment]
Sure. We can add the test to the refactor branch if you want, but since it's not working now, maybe merging first so PyStan is in a compilable state would be ideal.

**Comment by ariddell** [comment]
Closing in favor of #295.
