### ISSUE TITLE
Update Windows documentation for PyStan 2.7

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#164]
Building a new conda package seems like a good idea.

**Comment by ariddell** [comment]
@icoxfog417 Did you manage to get PyStan 2.5 running using the instructions?

**Comment by patricksnape** [comment]
@ariddell Just trying a 32-bit PyStan 2.7.0.0 build as we speak - will let you know.

**Comment by ariddell** [comment]
Thanks @patricksnape !

**Comment by patricksnape** [comment]
@ariddell There's a few bugs in Stan Math for MSVC 2008/2010 - just testing some fixes at the moment. This relates to #127.

**Comment by patricksnape** [comment]
See [here](https://github.com/stan-dev/math/pull/134) for a Stan Math fix.

**Comment by ariddell** [comment]
Fantastic. Thanks!

**Comment by patricksnape** [comment]
Builds are up for Windows 32-bit and Linux 64-bit, Python 3.4 and 2.7. Windows 64-bit is building but my VM is ludicrously slow, so may take until tomorrow to get the 64-bit builds uploaded.

**Comment by ariddell** [comment]
Since the windows documentation doesn't reference a specific version of PyStan, I think I can close this. Thanks again Patrick.
