### ISSUE TITLE
Remove diagnostic_file from API documentation

### ISSUE THREAD

**Issue by chmullig** [stan-dev/pystan#165]
Trying to debug performance I see:

> diagnostic_file : str, optional
> File name indicating where diagonstic data for all parameters should be written. If not writable, a temporary directory is used.

However, actually using that results in a `NotImplementedError`. The documentation should be appropriately updated.

**Comment by ariddell** [comment]
Removed from the documentation in e283e54. The overall goal is to push information to and from Stan without dealing with the filesystem. The reason for this is that filesystem details are very much platform dependent. It's easier just to deal with stuff in Python.
