### ISSUE TITLE
pip install pystan fails due to cython 0.23

### ISSUE THREAD

**Issue by tobeplugged** [stan-dev/pystan#171]
There seems to have been a breaking change in python 0.23 that prevents pystan from being build probably.

The issue is related to the way cython implements integer division in 0.23.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef vector[double] samples, split_chain
        for chain in range(n_chains):
            samples.clear()
            get_kept_samples(sim, chain, n, samples)
            split_chain.clear()
            for i in range(n_samples/2):
                                   ^
    ------------------------------------------------------------

    pystan/_chains.pyx:198:32: Cannot assign type 'double' to 'long'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                split_chain.push_back(samples[i])
            split_chain_mean.push_back(stan_mean(split_chain))
            split_chain_var.push_back(stan_variance(split_chain))

            split_chain.clear()
            for i in range(n_samples/2, n_samples):
                                   ^
    ------------------------------------------------------------

    pystan/_chains.pyx:204:32: Cannot assign type 'double' to 'long'

 Building with 0.22 however works just fine.

I've tried to fix the two examples with the result that everything works and the relevant tests pass.

However, a different test fails  if pystan is build with python 0.23: `test_rstan_stanfit:TestStanfit.test_grad_log`. It fails with a very minor mismatch of the two results (probably due to rounding errors). I'm not sure whether it would be good to use a more robust test from np.testing.

**Comment by ariddell** [comment]
See #170
