### ISSUE TITLE
error writing arrays with length 1 with stan_rdump

### ISSUE THREAD

**Issue by d10genes** [stan-dev/pystan#176]
This works

	pystan.stan_rdump({'ix': np.array([1,2,3])}, '/tmp/r.r')
	
But I get an error when the array has length 1

	pystan.stan_rdump({'ix': np.array([1])}, '/tmp/r.r')

		---------------------------------------------------------------------------
	AttributeError                            Traceback (most recent call last)
	<ipython-input-237-a609ad48ace8> in <module>()
	----> 1 pystan.stan_rdump({'ix': np.array([1])}, '/tmp/r.r')
	
	/Users/me/py-env/bay/lib/python2.7/site-packages/pystan/misc.pyc in stan_rdump(data, filename)
	    996             raise ValueError("Variable name {} is not allowed in Stan".format(name))
	    997     with open(filename, 'w') as f:
	--> 998         f.write(_dict_to_rdump(data))
	    999 
	   1000 
	
	/Users/me/py-env/bay/lib/python2.7/site-packages/pystan/misc.pyc in _dict_to_rdump(data)
	    967         elif value.ndim == 1:
	    968             if len(value) == 1:
	--> 969                 s = '{} <- {}\n'.format(name, str(value.pop()))
	    970             else:
	    971                 s = '{} <-\nc({})\n'.format(name, ', '.join(str(v) for v in value))
	
	AttributeError: 'numpy.ndarray' object has no attribute 'pop'

It seems arrays with length 1 are prohibited and [interpreted as dicts](https://github.com/stan-dev/pystan/blob/12f76788691d04f6d6473bed7684b860fc73d1b5/pystan/misc.py#L970). Is that intentional? (is there even a data structure that has both `ndim` and `pop` attributes?)

Thanks

**Comment by ariddell** [comment]
Thanks for the report. This looks like a case that's not handled right.
