### ISSUE TITLE
Installation fails on Windows with 64 bit VC++ 9.0

### ISSUE THREAD

**Issue by tanderberg** [stan-dev/pystan#177]
When trying to pip install on Windows (10 Pro, 64 bit, with 64 bit Anaconda and Visual C++ 9.0 for Python), the result is

cl : Command line error D8021 : invalid numeric argument '/Wno-unused-function'

I guess due to a missing compiler check along these lines:

http://stackoverflow.com/questions/2274006/cmake-invalid-numeric-argument-wextra

**Comment by ariddell** [comment]
Thanks for this. PyStan has pretty minimal support for Windows right now. You might have better luck if you use ``conda`` (see https://pystan.readthedocs.org/en/latest/windows.html).

There are plans/hopes to support Windows more fully under Python 3.5.
