### ISSUE TITLE
problem with pars keyword

### ISSUE THREAD

**Issue by rubind** [stan-dev/pystan#178]
Hi,

The "pars" keyword causes pystan.stan to incorrectly label the samples it returns. In this example, we expect "a" to be centered on 0, "b" to be centered on 1, and "c" to be centered on 2:

----------------------------------------------------------------------------------------------

import pystan
print pystan.__version__

stan_code = """
data {
}

parameters {
   real a;
   real b;
   real c;
}

model {
   a ~ normal(0, 1);
   b ~ normal(1, 1);
   c ~ normal(2, 1);
}
"""

fit = pystan.stan(model_code=stan_code, data={},
                  iter=2000, chains=2, n_jobs = 2, pars = ["a", "c"])
print fit

----------------------------------------------------------------------------------------------

2.8.0.0
...
       mean se_mean     sd   2.5%    25%    50%    75%  97.5%  n_eff   Rhat
a      0.05    0.02   0.99  -1.88  -0.57   0.06   0.69   2.04 2000.0    1.0
c      0.98    0.02   0.99  -1.01   0.32   1.01   1.68   2.82 2000.0    1.0
lp__   2.05    0.02   0.98   0.13   1.36   2.03    2.7   4.01 2000.0    1.0

So clearly "b" has been mislabeled "c." This doesn't happen without setting the pars keyword. I'm running python 2.7.10 (I know...), if it helps.

Thanks!
-David

**Comment by ariddell** [comment]
I'm tempted to make including `pars` a no-op for now since it's completely broken and I can't find an immediate fix. The relevant C++ code is identical in RStan and PyStan.

**Comment by ariddell** [comment]
It looks like the call to the sampler is with the wrong ``fnames_oi``.

**Comment by ariddell** [comment]
Fixed it, I think. This counts as yet another problem that would have been avoided if there was separation between a stanprogram and a stanprogram_with_data.

**Comment by bob-carpenter** [comment]
I agree that these two concepts should be seprated.  

stanc converts a Stan program to a C++ class.  The class needs
to be compiled and dynamically linked.  This is all pre-data.
I have no idea how RcppEigen and inline work in RStan or
how Cython works in Python --- is it easy to make this something
a program can manipulate?

Then the class is instantiated with data.  That actually
creates a C++ object in memory.

**Comment by ariddell** [comment]
Yes. This is all easy to do. Easier than keeping track of everything right now!
