### ISSUE TITLE
Release the GIL during sampling and use threads for parallel sampling

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#179]
There's no reason to use multiprocessing and doing so apparently creates problems for IPython/Jupyter #142. And multiprocessing creates problems for Windows and for CI tests.

This should be easy to implement during the PyStan 3 rewrite. The GIL should be released more systematically in the Cython wrapping code as well.

**Comment by hassan-sabirin** [comment]
https://docs.python.org/2/library/multiprocessing.html
http://stackoverflow.com/questions/20222534/python-multiprocessing-on-windows-if-name-main

The best practice is to write code like this:


```
def run():
    # your pystan/fbprophet code here
    pass

if __name__ == '__main__':
    run()
```
I used this method in windows an am able to run with n_jobs > 1 without problems.

**Comment by ariddell** [comment]
Thanks @hassan-sabirin. This is a good tip.

**Comment by ariddell** [comment]
Needs stan-dev/math#551 to be fixed.

**Comment by ajbouh** [comment]
@ariddel now that https://github.com/stan-dev/math/issues/551 is closed, how much work would this be?

Mixing pystan with dask is pretty painful when pystan holds the GIL during inference... Would be happy to help test a PR!

**Comment by ariddell** [comment]
Good question. Feel free to try to get things working.

(You might want to wait until there's a PyStan release that manages to
work without using the multiprocessing module.)

**Comment by ajbouh** [comment]
I'm not very familiar with the PyStan codebase. Any pointers? Dask is definitely not compatible with multiprocessing. Is there already a dependence on it in the current implementation?

**Comment by ariddell** [comment]
Yes, pystan uses multiprocessing now. We're going to fix that.

**Comment by ajbouh** [comment]
Any update here?

**Comment by ariddell** [comment]
What problem are you encountering? Are you on Windows? The solution to this (or at least, to a related problem) is in the works.

**Comment by ajbouh** [comment]
I'm on Linux and trying to use dask distributed, which is not compatible with the existing multiprocessing approach.

Dask also has lots of trouble when the GIL is held for long periods of time. To really scale out pystan sampling beyond the capacity of a single machine I need a version that doesn't hold the GIL for so long.

I saw that Stan now supports thread local storage for autodiff and is (supposedly) now safe to run without the GIL. Has anyone experimented with removing it since the thread local stuff started working?

**Comment by ajbouh** [comment]
@ariddell?

**Comment by ariddell** [comment]
The GIL is not held during sampling in PyStan 3. There should be a beta 
release in the next comple of weeks.

**Comment by riddell-stan** [comment]
This is now an issue for ``stan-dev/httpstan``.

**Comment by ajbouh** [comment]
@riddell-stan forgive the silly question, but if this is now an issue for stan-dev/httpstan, why is it closed? I looks for a related issue over at https://github.com/stan-dev/httpstan but didn't see anything that looked relevant.

Is the recommendation that folks build PyStan 3 locally for themselves and just use that?

**Comment by riddell-stan** [comment]
httpstan/pystan 3 does release the GIL and does use threads for 
sampling. pystan 2 uses multiprocessing to sidestep the GIL.

using threads doesn't speed things up relative to what pystan 2 does. In 
fact, it's a bit slower.

What's your concern specifically?

**Comment by ajbouh** [comment]
finding a build of pystan 3?

**Comment by riddell-stan** [comment]
You can build "pystan 3" from source here: https://github.com/stan-dev/pystan-next
