### ISSUE TITLE
feeding parameter values and getting likelihood back

### ISSUE THREAD

**Issue by inti** [stan-dev/pystan#180]
Hi, 
it is possible to build a model using pystan and then get it to obtained likelihood values for arbitrary parameter values? 
In essence using (py)stan to build the code to calculate the likelihood and then give it parameters and obtained likelihood values back. I am thinking to what extent I could use the pystan `log_prob` function as the core engine within another optimisation algorithm. 

Thanks in advance.

**Comment by bob-carpenter** [comment]
Yes.  See the grad_log_prob function at  https://pystan.readthedocs.org/en/latest/genindex.html

If you want to follow up, we have a Google Group:  https://pystan.readthedocs.org/en/latest/genindex.html

We try to restrict the issue tracker clear for bug reports and feature requests.
