### ISSUE TITLE
Error unpickling StanModel in the same session

### ISSUE THREAD

**Issue by stephen-hoover** [stan-dev/pystan#181]
I have code which runs several Stan models in the same session, and it's convenient to be able to pickle and unpickle them. Everything runs with pystan v2.4.0.1, but I've found that if I use versions >= 2.5, I encounter errors like
```
File "/usr/local/lib/python3.5/site-packages/pystan/model.py", line 361, in __getstate__
    with io.open(state['module_filename'], 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp_m7fspn3/pystan/stanfit4stan_4f6a8aa4aaaf729189aef079d2e69e90_6b6428759bd45bcbf54b3be85430e3cb.cpython-35m-x86_64-linux-gnu.so'
```
I believe this happens because Python will not reload modules which have already been loaded. Pystan stores modules in a temporary directory. If the original model is destroyed, that temp directory goes away, but the Python module in memory still points to that temp directory with its `__file__` attribute. So when the second model tries to pickle itself, it hits the `if not os.path.exists(state['module_filename']):` line in `__getstate__`.

It looks to me like the contents of the module file should be the same as the `model_cppcode` already stored in the `StanModel` object. If I modify `StanModel.__getstate__` to remove all of the `state['module_bytes']`-related lines, and modify `StanModel.__setstate__` to write `state['model_cppcode'].encode('utf-8')` to the new module file instead of `state['module_bytes']`, everything seems to work. Would a PR for this be welcome?

**Comment by ariddell** [comment]
A PR would be welcome if you can pin down what's happening. Perhaps the model-module should get unloaded when the model instance gets garbage collected?

There is one point to be clear about: the ``StanModel.module`` is the loaded C extension module; it's very different from the utf-8 encoded ``model_cppcode``.

Initially we just kept the tmp directories around forever but this became a problem when one is working on a server and fitting many, many models; nothing ever got deleted and disk space filled up.

Perhaps unloading the module in the ``__del__`` method would work?

In any event, pinning down the source of the problem (i.e., that something is going wrong with loading and the ``__file__`` attribute) would be enormously welcome.

**Comment by stephen-hoover** [comment]
Sure, I'll work on it a bit more and submit a PR. I'm not sure that unloading the model module in the `__del__` is the best solution -- that seems like it could create problems if a second `StanModel` is unpickled before the first is garbage collected, but used after. Maybe the best solution would be to keep the `module_filename` with the `StanModel` instead of relying on `self.module.__file__`?

**Comment by ariddell** [comment]
Would it be easier to start by getting a test to reproduce the bug you're having? I think I could help with that if you can sketch exactly how the problem arises. You have a model available to Python and then you unpickle a version of the same model?

**Comment by stephen-hoover** [comment]
Yes, that's a good place to start. I'll try to find a small example to reproduce what I'm seeing.

**Comment by stephen-hoover** [comment]
Define the following function, which reads a `StanModel` from a pickle, then re-writes it to a new pickle.
```
def read_write(fin, fout):
    with open(fin, 'rb') as _f:
        model = pickle.load(_f)
    with open(fout, 'wb') as _f:
        pickle.dump(model, _f)
```
Given an existing pickled `StanModel` as `fin`, this function runs once successfully, but if I run it a second time, it generates an exception of the form
`RuntimeError: Compiled module associated with Stan model not found at /var/folders/jn/z8wk4r050bn_zsxmyrhb4gsw0000gn/T/tmp9wzl424w/pystan/stanfit4stan_4f6a8aa4aaaf729189aef079d2e69e90_d8421d4c2d11c125209592b46bb0154b.cpython-35m-darwin.so`.

**Comment by ariddell** [comment]
Great. I can reproduce this. Thanks!

So it's clear that the StanModel.__del__ is getting called here at some point and this is deleting the temporary directory for the model. (I just added a `print` to check this). So which instance is being deleted?

**Comment by ariddell** [comment]
I wonder if there's any way one can avoid hitting disk. Can this compiled extension module be loaded and unloaded from some virtual file?

Or perhaps the mistake can be fixed by making sure that pickling happens in a different temporary directory each time?

**Comment by ariddell** [comment]
@stephen-hoover I've taken the strategy here of just never dealing with having the module on disk. Once the module is loaded we actually don't need to have it on disk. I'll add a few tests in a moment.

**Comment by stephen-hoover** [comment]
Excellent! It looks like this solves my problem. Thank you for the quick fix!

**Comment by tomwallis** [comment]
I'm getting a similar error and I don't understand why. 

1. I fit a model under Pystan 2.6.3.0, and pickled it. Loaded again all fine and for numerous times, sessions.
2. I recently upgraded to Pystan 2.8.0.2. Running the script that loads the picked file produces the following error:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-89362a63ffdc> in <module>()
      3                         ('expt_' + str(experiment_num) + '_' + 
      4                          model_name + '_full_model_fit.pkl')), 'rb') as f:
----> 5     stan_model, fit, plot_df, param_df, pop_param_df = pickle.load(f)

/Users/myusername/miniconda3/envs/default/lib/python3.4/site-packages/pystan/model.py in __setstate__(self, state)
    353         self.__dict__.update(state)
    354         lib_dir = tempfile.mkdtemp()
--> 355         with io.open(os.path.join(lib_dir, self.module_filename), 'wb') as f:
    356             f.write(self.module_bytes)
    357         try:

FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/jh/f31f472d08n2f7f_nlcmrbxm0000gn/T/tmplnycwpqg/pystan/stanfit4tanh3_full_520365d2a90f7f71c99ecae95c20058e_870d9071f5492aeafe7cd1afbcccb02d.so'
```

I'm guessing the fix above came too late for my version changes, and that in general, models pickled with old versions of Pystan will not be unpickleable by new versions?

**Comment by ariddell** [comment]
Unfortunately models are specific to versions of Stan. PyStan versions are (except for the very final number) proxies for Stan versions. I hope it's not too much trouble to recompile the model.

**Comment by tomwallis** [comment]
Ah, I see. 

It's no problem -- this refers to old data. I was merely trying to reproduce the error I experienced [here](https://github.com/stan-dev/pystan/issues/191) in a model I knew (thought) would work.
