### ISSUE TITLE
pystan installation when stan is available

### ISSUE THREAD

**Issue by migueldvb** [stan-dev/pystan#182]
Is there any option that can be provided to setup.py to install pystan when stan is already available in the system?

**Comment by ariddell** [comment]
Do you mean the cmdstan binary or the stan source (+ stan math)

**Comment by migueldvb** [comment]
I have a computer with cmdstan and I would like to install the pystan interface.

**Comment by ariddell** [comment]
PyStan doesn't use the cmdstan binary. Like RStan, it uses the Stan library directly (that is, it compiles the functionality into a Python extension module).

Are you having trouble installing PyStan?

**Comment by migueldvb** [comment]
Thanks, the installation works fine but I thought that it could use the library from cmdstan.
