### ISSUE TITLE
Survey Model example does not work

### ISSUE THREAD

**Issue by keryil** [stan-dev/pystan#183]
I could not get the Survey Model example (taken from Bayesian Cognitive Modeling book) properly under PyStan. I am using PyStan 2.8.0 on (Homebrew) Python 2.7.10.

Here's the model: https://github.com/stan-dev/example-models/blob/master/Bayesian_Cognitive_Modeling/ParameterEstimation/Binomial/Survey_model.stan

Here's the data and sampling code:
```
data = {'nmax':500,
        'm':5,
        'k':[16,18,22,25,27]}

fit = model.sampling(data=data,
                  iter=4000, thin=1, chains=1, warmup=2000, pars=["n","theta"])
```
Basically the `theta` variable samples come out all `-inf`'s in the trace for a reason I could not discover. 

The same model works as expected (i.e. as it works in the book) on rstan, using the R wrapper also provided with the example in the repo.

**Comment by ariddell** [comment]
Thanks for this. I think this might be the same as #64.

**Comment by ariddell** [comment]
If anyone else runs into this the fix is to avoid using the `pars` keyword for the time being.
