### ISSUE TITLE
pyStan should allow compiler optimization

### ISSUE THREAD

**Issue by stephen-hoover** [stan-dev/pystan#185]
When upgrading from v2.4.0.1 to v2.8.0.0, I discovered that my models all ran about 10x slower than before. I tracked this down to the v2.6.0.0 --> v2.6.3.0 change, specifically https://github.com/stan-dev/pystan/compare/v2.6.0.0...v2.6.3.0#diff-352247931e49c30c3094b222abb57619L283 . pyStan had previously compiled the model modules with O3 optimization, and now it uses O0 (no optimization). 

Restoring the optimization flag returns model performance to what I had with v2.4.0.1. In fact, the O2 flag appears to be better than O3 in terms of average time per chain.

Would it be possible to either restore compiler optimization (I'd prefer O2 based on my tests) or make the optimization level a settable parameter in the `StanModel.__init__`?

**Comment by bob-carpenter** [comment]
Yes, please.  We absolutely need to keep compiler optimization to
at least the -O2 level and preferably the -O3 level.

Did you run those timing tests based on the exact same seeds?

- Bob

**Comment by stephen-hoover** [comment]
I didn't set the seeds, but I did run several times at each optimization setting. Would we have exactly the same RNG draws for each optimization level? If so, I can try using the same seed. I observed that of four chains, all of the chains at the O2 level finished in about the same amount of time. At O3, the fastest chain was the same as O2, but there was always at least one straggler that took tens of percent longer to run. Still rather anecdotal, I know. I'll try running with the seed set.

**Comment by bob-carpenter** [comment]
> On Oct 29, 2015, at 1:24 PM, Stephen Hoover <notifications@github.com> wrote:
> 
> I didn't set the seeds, but I did run several times at each optimization setting. Would we have exactly the same RNG draws for each optimization level?

Not necessarily.   The floating point "spec" as it is leaves
quite a lot of wiggle room on both the hardware and compiler side.

> If so, I can try using the same seed. I observed that of four chains, all of the chains at the O2 level finished in about the same amount of time. At O3, the fastest chain was the same as O2, but there was always at least one straggler that took tens of percent longer to run. Still rather anecdotal, I know. I'll try running with the seed set.

The straggler is almost certainly an issue with warmup, not
optimization.  I don't know if PyStan has a way to report
the time taken to do a log density and gradient eval --- it
gets dumped out in CmdStan and can be used to calibrate optimization
speed (and again, even with everything the same, you need to run
a few times to avoid being sensitive to other resources being used).

- Bob

**Comment by stephen-hoover** [comment]
Fixing the seed wasn't enough to ensure the same run times, but the results over sets of three runs are still pretty consistent. Under O2 optimization, I had a model run four chains in 29 to 37 seconds. Under O3, it was 32 to 46 seconds. I'm not confident enough in these results to push for O2 over O3, since I don't know why it would be like this. 

I see variation in both the warm-up and sampling portions of the chain. I'm going by the screen output provided, e.g.
```
#  Elapsed Time: 17.8875 seconds (Warm-up)
#                27.678 seconds (Sampling)
#                45.5655 seconds (Total)
```

If optimization level were a settable option, I'd probably pick O2 right now, but really, I'd be very happy with a hardcoded O3. O0 is about 10x longer runtimes.

**Comment by bob-carpenter** [comment]
Thanks for following up.  Yes, -O2 and -O3 are both way way
better than -O1.  Our code's been written to lean heavily
on compiler optimizations.

Allen will have to chime in on providing configurable
optimization.  

The other issue is that it can vary by hardware (CPU, memory,
machine architecture [particularly memory to CPU]) and
by compiler.

- Bob

**Comment by syclik** [comment]
With fixed seeds, are the draws identical using O2 and O3? If not, can you also report effective sample size?

You should pick the one that gives you more effective sample size per time. Presumably you're interested in things that take longer than 45 seconds?

Also, the variability in time run to run may be much larger than you think. Can you try running with the same setup 100 times and report back?

**Comment by ariddell** [comment]
Found the issue where optimization was turned off: #33 

I think that was back before the switch to header-only Stan.

**Comment by bob-carpenter** [comment]
It's fine to compile stanc without optimization.  It is a very
bad idea to compile Stan models without optimization --- it's 
only about 10% as fast.

- Bob

**Comment by stephen-hoover** [comment]
@syclik , I don't have a good effective sample size measurement yet (see #186 ). I can try running 100 times, but I don't think I'll be able to set that up immediately. Is it relevant for this issue?

**Comment by syclik** [comment]
For the issue, no. There should be a way for PyStan to set the optimization level. 

If you're trying to compare O2 vs O3 *and* want some action from someone, then yes. (This includes suggesting users use O2 instead of O3.) I wouldn't trust those numbers if only repeated a handful of times. I've run c++ code that runs between 1.5 secs and 8 secs with the variability coming from the Mac being a Mac (deterministic code, all just running the same executable). Understanding the level of variability was an important exercise for myself in practical timing. 

No need to do anything now unless you're curious.

**Comment by stephen-hoover** [comment]
Thank you!
