### ISSUE TITLE
Test PyStan on Windows with Python 3.5

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#190]
Appveyor is now setup to build PyStan using Python 3.5 and Visual Studio 14.0.

https://ci.appveyor.com/project/ariddell/pystan

It's failing right now, but I'd like that to change.

**Comment by ariddell** [comment]
@patricksnape is there some way to see your conda build script for older versions of PyStan? I suspect that if I made some of those changes things might work. I realize you were building for VS 2008 and now we can use VS 2014 since we're restricting things to Python 3.5.

**Comment by patricksnape** [comment]
@ariddell The repository is [here](https://github.com/menpo/conda-recipes/tree/master/pystan), unfortunately the history is a bit mixed up but hopefully you can use the history per file to help.

At the moment, conda is in a bit of a transition period due to continuum hiring a bunch of people to work on conda Windows builds and the recent release of Python 3.5. I'm just trying to get some information from the continuum guys about how the new system will work and then I can be more helpful.

On the upside, these new changes to conda are designed to deal with the problems we have been having with Visual Studio versions and Python!

**Comment by patricksnape** [comment]
Also, the problem seems to be [here](https://ci.appveyor.com/project/ariddell/pystan/build/1.0.3/job/yqag5pwpdsfx8ju6#L277) in the build and likely stems from the fact that Visual Studio 2015 defaults to throwing an error when it receives unknown options - and those last few options seem to be GCC options.

**Comment by ariddell** [comment]
All of the options need to be guarded? Even the optimization level?

**Comment by patricksnape** [comment]
Yes, because the optimisation level is set on Windows with the flags [here](https://msdn.microsoft.com/en-us/library/k1ack8f1.aspx). All of the flags are forward slash rather than dash.

**Comment by ariddell** [comment]
hitting these
```
[00:22:19] C:\Python35\lib\site-packages\pystan\stan\src\msinttypes.h(105): error C2371: 'int_fast16_t': redefinition; different basic types
[00:22:19] 
[00:22:19] C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdint.h(36): note: see declaration of 'int_fast16_t'
[00:22:19] 
[00:22:19] C:\Python35\lib\site-packages\pystan\stan\src\msinttypes.h(109): error C2371: 'uint_fast16_t': redefinition; different basic types
[00:22:19] 
[00:22:19] C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdint.h(40): note: see declaration of 'uint_fast16_t'
```

**Comment by ariddell** [comment]
@patricksnape Are there any parts of your patches which don't need to be adopted because I'm using VS2014? Or should I just try to put them all in?

**Comment by patricksnape** [comment]
Sorry for the slow response - I'm battling with Python 3.5 automated builds for our software.

That looks like an error in the face that you are including your own version of `misinttypes.h` in Stan but VS 2015 is much more compliant and I think now mostly covers that use case for that header file. 

Do you want me to try adding a PR to PyStan that adds auto-building in the vein that we achieve it in Menpo? i.e. a conda folder that contains the recipe and is built by the Appveyor and Travis scripts?

**Comment by ariddell** [comment]
No worries.

I figured out that msinttypes.h was the problem and now have 32-bit windows wheels building on appveyor (64 bit still has problems). https://ci.appveyor.com/project/ariddell/pystan/build/1.0.11

For pure-packaging (apart from CI testing) I think having a separate repo is marginally easier. I'll create a pystan-conda repository right now and add you to it. I'll populate it with your recipe if that's alright with you.

**Comment by ariddell** [comment]
@patricksnape I've added you to ariddell/pystan-conda (mirrors ariddell/pystan-osx-wheel-builder, which I use for building OS X wheels).

I'm assuming you're happy to let me just follow along with mempo's conda-recipes changes and take over building conda binaries, right? I'd really like for PyStan to support Windows (with Python 3.5+), so I'm more than happy to do this.

**Comment by patricksnape** [comment]
It failed because you have hit the timeout:

``Build execution time has reached the maximum allowed time for your plan (60 minutes).``

Of course, happy to help get everything building and then of course you are welcome to host the conda packages yourself under a pystan name or stan or something?

**Comment by ariddell** [comment]
I'll be able to really dig into this once we get msinttypes.h out of stan-math (soon, see stan-dev/math#201).

For now I've added the contents of menpo/conda-recipes/pystan into https://github.com/ariddell/pystan-conda. Perhaps I should wait until I get 64bit and 32bit building under appveyor and then tackle the conda build for Python 3.5? I've taken a look at the appveyor.yml in menpo/menpo, and my impression is that I can just copy that once things are working on appveyor in this repo.

Thanks again for your help! I'm sure I'll have some more questions down the road.

**Comment by patricksnape** [comment]
Sure - we can wait to see what patches we need once stan-math is all up to date. I usually start with no patches (ideally) and then patch as required :+1: 

Do you want the conda builds automated or just versioned? In Menpo everything is automated so we automatically upload new conda builds upon tagging a new version. But obviously you are free to do this yourself as when you update the conda recipe?

**Comment by ariddell** [comment]
So appveyor is building Python 3.5 Windows wheels now.

I'll create a new issue to track the conda release progress.
