### ISSUE TITLE
`assert` in `_chains.effective_sample_size` triggers on constant parameters  

### ISSUE THREAD

**Issue by stephen-hoover** [stan-dev/pystan#191]
I'm coming across instances where the `assert chain_var[chain] < float('inf'), chain_var[chain]` line in _chains.pyx triggers when I'd rather it didn't. I have a model with a transformed parameter which is the same on every step of the chain. It has standard deviation zero, and so the autocovariance is nan. This causes an `AssertionError` in `_chains.effective_sample_size`.

@ariddell , I know I suggested in #186 checking that `chain_var[chain]` isn't infinity, but it seems there's cases where that should pass. For this particular case, the `Rhat` in the summary output shows up as `NaN` (if I remove the `assert`), so that makes it obvious that the effective sample size output is suspect.

**Comment by ariddell** [comment]
Good point. The assert should be removed.

**Comment by tomwallis** [comment]
I just had this same assert error in Pystan 2.8.0.2. How can I check which version the commit above corresponds to?

**Comment by ariddell** [comment]
This hasn't been released yet. You can just remove the assert in the source file for the time being. We should make a release very soon (Stan 2.9).

**Comment by tomwallis** [comment]
I just installed the `develop` branch from Github for the time being.
