### ISSUE TITLE
Support/encourage HDF5 (or similar) instead of pickle

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#197]
The following is a serious problem that many people are likely to encounter with moderate numbers of parameters/samples:

```
Traceback (most recent call last):
  File "irt_regression.py", line 131, in <module>
    pickle.dump(fit.extract(), f)
OverflowError: cannot serialize a bytes object larger than 4 GiB
```

`pickle` cannot serialize objects of > 4GiB. Samples can use up this much memory. Thinning after the fact is not easy.

Is there an alternative to pickle here?

**Comment by ariddell** [comment]
Nevermind, this is a bug in Python; pickle is fine: https://bugs.python.org/issue24658

**Comment by pganeshGapps** [comment]
Not anymore in Python 3.4 which has PEP 3154 and Pickle 4.0
https://www.python.org/dev/peps/pep-3154/

But you need to say you want to use version 4 of the protocol:
https://docs.python.org/3/library/pickle.html

pickle.dump(d, open("file", 'w'), protocol=4)

**Comment by ariddell** [comment]
Thanks! We should certainly change the docs to tell people to use protocol=4 by default.

**Comment by ariddell** [comment]
Re-opening as  a reminder to update the docs.
