### ISSUE TITLE
"Fixed_param" algorithm segfaults

### ISSUE THREAD

**Issue by axch** [stan-dev/pystan#200]
Tried running the "Fixed_param" algorithm (as another way to do what I was trying to do in #199) from pystan, but it failed with a segmentation fault.  I was able to reproduce the problem with the eight schools example [schools.py.txt](https://github.com/stan-dev/pystan/files/63992/schools.py.txt) :
```
$ python schools.py
<snip lots of compilation output>
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security /tmp/tmpNWhLXX/tmp/tmpNWhLXX/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5096558326829618303.o -o /tmp/tmpNWhLXX/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5096558326829618303.so
Segmentation fault (core dumped)
```

I am using pystan 2.8.0 on Ubuntu 14.04 with Python version 2.7.0, Cython version 0.23.4, and numpy version 1.8.2.

Same example works (edit: meaning completes successfully without a segmentation fault) with the HMC algorithm, and works with the fixed_param algorithm in CmdStan 2.9.0.

**Comment by ariddell** [comment]
Thanks. That should certainly not happen.

**Comment by luac** [comment]
I dug a little deeper and found a workaround for this:

```
model.sampling([...], algorithm='Fixed_param', control={'adapt_engaged': False})
```

The segfault seems to be the result of a bad interaction between the code that deals with adaptation and Fixed_param (which doesn't do any adaptation). Perhaps adapt_engaged should default to False in this case?

**Comment by ariddell** [comment]
Thanks @luac! This is really helpful.
