### ISSUE TITLE
Cache StanProgram/StanModel compilation

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#204]
PyStan should cache [StanProgram](https://github.com/stan-dev/stan/wiki/User-Interface-Guidelines-for-Developers) (née StanModel) compilation by default. Compiled extension
objects are small (ca. 5M) and model compilation takes a great deal of time. Excellent work on this has been done by Paul Kernfeld (@paulkernfeld) (https://github.com/paulkernfeld/pystan-cache).

Desiderata:
- [ ] Use standard cache locations for OS X, Linux, and Windows; this is default for `cache_dir`
- [ ] Cache by default, `cache=False` will disable
- [ ] Cache 350M worth of models by default using a LRU cache

(I picked 350M because that's the default amount of disk space Firefox
will use for caching images if you disable automatic cache management.)

Details:
- [ ] Hash of Stan model code + Stan version + platform works as a unique identifier

**Comment by ariddell** [comment]
I'd love to have this feature. What about just starting with an experimental version which doesn't have the LRU cache and doesn't pay attention to disk space constraints?

**Comment by ariddell** [comment]
For what it's worth, I've been informally caching my Stan models and have accumulated 4G in 4 months. I think a default cache of 500M is reasonable.

**Comment by bob-carpenter** [comment]
Seems reasonable to me (starting simple and 500MB cache size).

Is there a way to use the temp directory so we don't drop 500MB
of data onto someone's drive without them realizing it and without
it getting autocleaned?  Otherwise, you may want to have them
explicitly turn it on and size it so they know what they're getting
into.

I think many people are going to be working through lots of
model variants.

- Bob

**Comment by ariddell** [comment]
We're using the standard cache directories (OS X, Windows, Linux). They're known to the operating system as temporary.

**Comment by ariddell** [comment]
Note that if you compress a model using LZMA (part of Python standard library), it only takes ~3M rather than ~25M.

**Comment by ariddell** [comment]
PyStan 3 has this.

**Comment by sursu** [comment]
@ariddell in case you know: what is the expected release date of PyStan 3?

**Comment by riddell-stan** [comment]
There's a working alpha version which you can install with `python3 -m pip install --pre pystan`. See https://github.com/stan-dev/pystan-next

**Comment by sursu** [comment]
True, but I'm reluctant to use it when it says "Do not use!".
An estimated release date would be nice.

**Comment by riddell-stan** [comment]
I've responded on the forum: https://discourse.mc-stan.org/t/preview-of-next-version-of-pystan/7024/9?u=ariddell
