### ISSUE TITLE
linux installation problem

### ISSUE THREAD

**Issue by kscheffler** [stan-dev/pystan#208]
I'm trying to install pystan (2.9.0.0) in CentOS Linux release 7.2.1511 (running on windows via VirtualBox) using python 3.5 and pip. Cython and numpy have already been installed successfully. Below is the tail end of what I get on "pip install pystan". I notice it is asking for winreg, win32api or win32con, which I am under the impression are only available for windows. Any idea why it is asking for this? (Sorry if this is an issue unrelated to PyStan, which seems a strong possibility.)

    compile options: '-DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen_3.2.4 -Ipystan/stan/lib/stan_math/lib/boost_1.58.0 -I/usr/local/include/python3.5m -c'
    extra options: '-O0 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized'
    Warning: Can't read registry to find the necessary compiler setting
    Make sure that Python modules winreg, win32api or win32con are installed.
    gcc: pystan/stan/src/stan/lang/grammars/whitespace_grammar_inst.cpp
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc: pystan/stan/src/stan/lang/grammars/functions_grammar_inst.cpp
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <http://bugzilla.redhat.com/bugzilla> for instructions.
    cc1plus: warning: command line option â-Wstrict-prototypesâ is valid for C/ObjC but not for C++ [enabled by default]
    gcc: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <http://bugzilla.redhat.com/bugzilla> for instructions.
    error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen_3.2.4 -Ipystan/stan/lib/stan_math/lib/boost_1.58.0 -I/usr/local/include/python3.5m -c pystan/stan/src/stan/lang/grammars/functions_grammar_inst.cpp -o build/temp.linux-x86_64-3.5/pystan/stan/src/stan/lang/grammars/functions_grammar_inst.o -O0 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized" failed with exit status 4
    
    ----------------------------------------
Command "/usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fe9s3eqv/pystan/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lnooa0fl-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-fe9s3eqv/pystan

**Comment by ariddell** [comment]
That's really odd. Can you figure out what version of gcc it is?

**Comment by kscheffler** [comment]
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)

**Comment by ariddell** [comment]
Could you try compiling the model with verbose=True? It would be helpful to see what the compiler error is (``gcc: internal compiler error: Killed (program cc1plus)``)

**Comment by kscheffler** [comment]
Attached is the output for "pip -v -v -v install pystan &> pipoutput.txt" (maximum verbosity). It doesn't seem to give more info on that error. I sould mention that the first error is "Failed building wheel for pystan" (after complaining about the win files).

[pipoutput.txt](https://github.com/stan-dev/pystan/files/108761/pipoutput.txt)

**Comment by ariddell** [comment]
I've never seen this error before. Have you tried Python 3.4? Does Python 3.5 come with Centos 7?

**Comment by kscheffler** [comment]
No, it comes with Python 2.7. Pystan wouldn't install so I installed Python 3.5 in case that was the problem. I'll try with 3.4 tomorrow.

**Comment by ariddell** [comment]
So I think the best bet is to (1) hope that someone else has this problem and figures out a solution and (2) try a different VM?

Maybe searching for gcc centos virtualbox problems might help?

**Comment by kscheffler** [comment]
After installing a few things (e.g. Guest Additions for smoother use of Virtualbox) I installed Python3.5.0 (previous was 3.5.1; I don't know why Google turned up a different one this time) and I now get a different error (verbose output attached). This looks like the same error I also get using Python 2.7.5.

[pipoutput_350.txt](https://github.com/stan-dev/pystan/files/110318/pipoutput_350.txt)

**Comment by ariddell** [comment]
This looks like the error:

```
    /usr/include/features.h:330:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
     #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
        ^
    {standard input}: Assembler messages:
    {standard input}:120481: Warning: end of file not at end of a line; newline inserted
    {standard input}:120908: Error: unrecognized symbol type ""
    gcc: internal compiler error: Killed (program cc1plus)
```

Perhaps this is something CentOS specific?

**Comment by mccahill** [comment]
I don't think this is CentOS specific because I see the same problems when trying to build under Ubuntu 14.04

**Comment by ariddell** [comment]
I develop on Ubuntu 14.04 and I haven't seen this.

Can you get the pip log for this error when you're using Ubuntu 14.04? I think it's something redhat is doing (IMHO).

**Comment by ariddell** [comment]
I'm going to close this for now. If you have more information that would help, please reopen.
