### ISSUE TITLE
Document installation of CVODE

### ISSUE THREAD

**Issue by syclik** [stan-dev/pystan#209]
Write documentation on how to install CVODE in PyStan.

Write what happens if CVODE is not installed. Write what happens if installation is successful.

**Comment by ariddell** [comment]
@syclik is there something I can copy in cmdstan or rstan?

**Comment by syclik** [comment]
I added a couple lines in the cmdstan manual, but it was just saying that
we use cvodes. If you're able to take care of building it, then just copy
some of the text from the cmdstan manual? Just search from "cvode" in the
manual.

**Comment by ariddell** [comment]
I'm going to release 2.14.0 first.

**Comment by riddell-stan** [comment]
Fixed by #496
