### ISSUE TITLE
Consider using forkserver on Python 3 for multiprocessing backend by default

### ISSUE THREAD

**Issue by jseabold** [stan-dev/pystan#210]
Calling a threaded operation on both sides of a fork without exec will deadlock. Some discussions of the issue

https://github.com/numpy/numpy/issues/654
https://github.com/numpy/numpy/pull/4194
https://github.com/xianyi/OpenBLAS/issues/294
https://github.com/joblib/joblib/issues/138

**Comment by jseabold** [comment]
Related to #179.

**Comment by ariddell** [comment]
Thanks! This is good to know about.

**Comment by ariddell** [comment]
I think #179 covers this. Thanks.
