### ISSUE TITLE
Align function parameter names with CmdStan (e.g., num_draws)

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#216]
If CmdStan and RStan switch to `num_draws` (previously `iter`), PyStan should follow

See https://github.com/stan-dev/stan/issues/1801

**Comment by bob-carpenter** [comment]
Agreed.  There are the superficial output changes and the deeper algorithm parameter names.  I'd rather push the latter off to Stan 3.

**Comment by ahartikainen** [comment]
This is fixed by PyStan3. Do we keep this issue open?
