### ISSUE TITLE
Add FAQ section with an entry about Jupyter

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan#217]
An FAQ section would be helpful, I think. The Jupyter question is going to come up again.

**Comment by riddell-stan** [comment]
@ahartikainen It seems like https://pypi.org/project/nest-asyncio/ is the preferred solution? Is that right?

I would be open to adding a test which creates a jupyter notebook (with the nest-asyncio calls) and verifies that PyStan works.

**Comment by ahartikainen** [comment]
nest-asyncio is my go-to solution.

Apparently that doesn't work in spyder (I have not  tested spyder in a long time) but thread hack might work there.

**Comment by defjaf** [comment]
Could you make this more explicit? I.e., could you provide an actual recipe in the FAQ for the solution? (I would imagine a lot of users will be using Jupyter -- is there any way to make this automatic within pystan?)
