### ISSUE TITLE
Unfeature pystan2 from sponsors page

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan#219]
@jgabry can you unfeature pystan2 from https://github.com/sponsors/stan-dev? PyStan 2 is not maintained.

**Comment by rok-cesnovar** [comment]
Fixed. The new pystan repository is now featured: 

![image](https://user-images.githubusercontent.com/28476796/111984208-590f2d00-8b0b-11eb-932f-6810c15a375a.png)
