### ISSUE TITLE
Use mcmcplotlib for plotting

### ISSUE THREAD

**Issue by twiecki** [stan-dev/pystan#224]
There was some discussion on joining efforts with `pymc3` on having a single plotting package: https://github.com/mcmcplotlib/mcmcplotlib Any interest in still going that route?

**Comment by ariddell** [comment]
Yes! I think this would be great. I don't know enough matplotlib to guide the effort but I'm eager to support it and use a common library.

**Comment by ariddell** [comment]
Work is on #315
