### ISSUE TITLE
Cast np.int types to python int in `_make_json_serializable`

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan#225]
```
def _make_json_serializable(data: dict) -> dict:
    """Convert `data` with numpy.ndarray-like values to JSON-serializable form.
    Returns a new dictionary.
    Arguments:
        data (dict): A Python dictionary or mapping providing the data for the
            model. Variable names are the keys and the values are their
            associated values. Default is an empty dictionary.
    Returns:
        dict: Copy of `data` dict with JSON-serializable values.
    """
    # no need for deep copy, we do not modify mutable items
    data = data.copy()
    for key, value in data.items():
        # first, see if the value is already JSON-serializable
        try:
            json.dumps(value)
        except TypeError:
            pass
        else:
            continue
        # numpy scalar
        if isinstance(value, np.ndarray) and value.ndim == 0:
            data[key] = np.asarray(value).tolist()
        # numpy.ndarray, pandas.Series, and anything similar
        elif isinstance(value, collections.abc.Collection):
            data[key] = np.asarray(value).tolist()
        else:
            raise TypeError(f"Value associated with variable `{key}` is not JSON serializable.")
    return data
```

Currently `np.int64` type values raise TypeError (`raise TypeError(f"Value associated with variable `{key}` is not JSON serializable.")`).

I think we can add `numbers.Integral` and `numbers.Real` and cast numbers automatically

```
from numbers import Intergral, Real

if isinstance(value, Integral):
    value = int(value)
elif isintance(value, Real):
    value = float(value) 
```

**Comment by riddell-stan** [comment]
@ahartikainen Can you show the code which prompted this bug report?

**Comment by ahartikainen** [comment]
https://github.com/arviz-devs/arviz/pull/1583

```
def sel_observations(self, idx):
  xdata = self.idata_orig.constant_data.x.values
  ydata = self.idata_orig.observed_data.y.values
  mask = np.full_like(xdata, True, dtype=bool)
  mask[idx] = False
  N_obs = len(mask)
  N_ex = np.sum(~mask)
  observations = {
      "N": N_obs - N_ex,
      "x": xdata[mask],
      "y": ydata[mask],
      "N_ex": N_ex,
      "x_ex": xdata[~mask],
      "y_ex": ydata[~mask],
  }
```

**Comment by riddell-stan** [comment]
Could arviz cast numpy integer types to Python integer types?

I'd propose opening a new issue with a subject which describes a problem. For example, "PyStan fails when given numpy integer types rather than Python integers" With such a subject, it will be easy for other users to find and to provide examples of how this is a problem experienced by many people.

**Comment by riddell-stan** [comment]
@ahartikainen Would you mind reviewing #230 ? I think it may provide a useful short-term fix for this problem. Good enough to let us release 3.0.

**Comment by ahartikainen** [comment]
> Could arviz cast numpy integer types to Python integer types?

This is not only an arviz problem. It is just how numpy.int vs python int behave.

**Comment by ahartikainen** [comment]
Ok, just checked this

```
import numpy as np
import json

json.dumps({"a": np.int32(1)})
```

```TypeError: Object of type int32 is not JSON serializable```

So extracting integer values from numpy arrays is always going to be a problem. (E.g. in the example np.sum returns a np.int32).

**Comment by riddell-stan** [comment]
PyStan 3 is backwards-incompatible. I think we should take the opportunity to be more conservative in what we accept as input as this will reduce our maintenance burden in the long term. (Reducing the maintenance burden is one of the stated goals of PyStan 3.) The `Data` type I propose in the PR seems very reasonable to me.

**Comment by riddell-stan** [comment]
I understand. I'm suggesting that we require people to convert to Python integers, so {"a": int(np.int32(3))}. That's what the `Data` type says.

**Comment by ahartikainen** [comment]
Sure.

We probably want to say that somewhere. Python doesn't really make it explicit when number is python int vs numpy int. And our users probably are not that familiar with these kind of problems.

**Comment by riddell-stan** [comment]
Let's wait until someone asks. Then we can write an FAQ entry. Right now we have documented what is allowed in a data dictionary via the function signature: https://pystan.readthedocs.io/en/latest/reference.html#stan.build This will certainly be enough for advanced users and library authors.

**Comment by riddell-stan** [comment]
Okay, let's do this with ``numbers.Integral``, see #326 We need a new PR since the code has changed quite a bit.
