### ISSUE TITLE
sample_file and stan_rdump don't successfully write files that cmdstan's stansummary can read

### ISSUE THREAD

**Issue by jeffalstott** [stan-dev/pystan#226]
#### Summary:
Please provide a short couple sentence summary.
Pystan has options to write a "sample_file" during `sampling`, but the resulting file can't be parsed by cmdstan's `stansummary`. Similarly, pystan's `stan_rdump` cannot take the output of a `sampling` and write it do disk.

#### Current Output:
#python
`> sampling_draws = my_model.sampling(..., sample_file='output.csv') `
output.csv writes, but to the wrong format:
#shell
```
> bin/stansummary output.csv
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_lexical_cast> >'
  what():  bad lexical cast: source type value could not be interpreted as target
Aborted
```

Can we just write the output of the summary manually? No:
```
> from pystan.misc import stan_rdump
> stan_rdump(sampling_draws, 'output.csv')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-d802443ee158> in <module>()
----> 1 stan_rdump(sampling_draws,'output.csv')

/home/jeffrey_alstott/anaconda3/lib/python3.4/site-packages/pystan/misc.py in stan_rdump(data, filename)
   1011 
   1012     """
-> 1013     for name in data:
   1014         if not is_legal_stan_vname(name):
   1015             raise ValueError("Variable name {} is not allowed in Stan".format(name))

stanfit4anon_model_0340770eb9d8a6ea3e843127d3b0b33c_6160836309826482080.pyx in stanfit4anon_model_0340770eb9d8a6ea3e843127d3b0b33c_6160836309826482080.StanFit4Model.__getitem__ (/tmp/tmpc_d0eam6/stanfit4anon_model_0340770eb9d8a6ea3e843127d3b0b33c_6160836309826482080.cpp:11505)()

stanfit4anon_model_0340770eb9d8a6ea3e843127d3b0b33c_6160836309826482080.pyx in stanfit4anon_model_0340770eb9d8a6ea3e843127d3b0b33c_6160836309826482080.StanFit4Model.extract (/tmp/tmpc_d0eam6/stanfit4anon_model_0340770eb9d8a6ea3e843127d3b0b33c_6160836309826482080.cpp:10063)()

/home/jeffrey_alstott/anaconda3/lib/python3.4/site-packages/pystan/misc.py in _check_pars(allpars, pars)
    763     for par in pars:
    764         if par not in allpars:
--> 765             raise ValueError("No parameter {}".format(par))
    766 
    767 

ValueError: No parameter 0
```

#### Expected Output:
What I would expect (not necessary what _should_ happen, but what I _expected_ to happen) is that both the `sample_file` option and the `stan_rdump` would write a file that cmdstan could interpret.

#### PyStan Version:
2.9
#### Python Version:
3.4.3
#### Operating System:
Linux

**Comment by betanalpha** [comment]
stan_rdump isn't meant to dump the fit object but rather a dictionary of input data, which could for example then be used to run cmdstan.

**Comment by ariddell** [comment]
Yes, check out the documentation here: https://pystan.readthedocs.io/en/latest/conversion.html

Clearly some examples are needed. This ``rdump`` format is the only format which currently is supported across interfaces.

**Comment by jeffalstott** [comment]
Thanks all,

I did read the documentation for `stan_rdump`, as that's the only place the function is referenced; there are indeed no examples to make more clear what the documentation is referring to when it says "model data". Even just "model input data" (as @betanalpha wrote) would be sufficiently clear to avoid a user trying what I tried.

This issue comes from the discussion in [the Stan users list](https://groups.google.com/forum/#!category-topic/stan-users/general/N0UfmIgR9yU) , which is where @ariddell asked me to post an issue. I assume now he was referring to the `sample_file` option. In addition to resolving that, it would be good if the `StanFit4Model` object had some ability to write itself to disk.

**Comment by ariddell** [comment]
A StanFit4Model can be pickled. This is the standard way to serialize things in Python.

For reference, here's the start of a csv file produced by pystan:

```
# Sample generated by Stan
# stan_version_major=2
# stan_version_minor=9
# stan_version_patch=0
lp__,accept_stat__,stepsize__,treedepth__,n_leapfrog__,n_divergent__,beta.1.1,beta.2.1,beta.3.1,beta.1.2,beta.2.2,beta.3.2,beta.1.3,beta.2.3,beta.3.3,beta.1.4,beta.2.4,beta.3.4
-15134.5,5.18361e-119,2,1,1,0,1.60017,1.88318,-0.0785405,-0.233453,0.574693,-1.61708,0.334204,-1.79341,-0.337801,-0.85087,0.732671,-0.324948
-15134.5,0,2.33506,1,1,1,1.60017,1.88318,-0.0785405,-0.233453,0.574693,-1.61708,0.334204,-1.79341,-0.337801,-0.85087,0.732671,-0.324948
```

Why can't cmdstan read this?

**Comment by jeffalstott** [comment]
> A StanFit4Model can be pickled. This is the standard way to serialize things in Python.

I should have been more clear: I meant written in a way that other parts of the Stan ecosystem can read.

> Why can't cmdstan read this!

Two guesses, which are probably wrong as I don't really follow what's described in the cmdstan documentation: 

1. There are additional facts written in the header in the #s that cmdstan parses (seems unlikely, but cmdstan does indeed write more info in there). An example from the documentation (page 12):
```
# stan_version_major = 2
# stan_version_minor = 8
# stan_version_patch = 0
# model = bernoulli_model
# method = sample (Default)
# sample
# num_samples = 1000 (Default)
# num_warmup = 1000 (Default)
# save_warmup = 0 (Default)
# thin = 1 (Default)
```

2. There is more info that happens later on in the file, after the rows of sample data. From page 13 of the cmdstan documentation:

> The next section describes the results of adaptation taking place during the
warmup phase.
```
# Adaptation terminated
# Step size = 1.81311
# Diagonal elements of inverse mass matrix:
# 0.415719
```

**Comment by sakrejda** [comment]
@jeffalstott Pretty much right on both counts.  This is something I'm working on addressing on a more general level (i.e.-we need to define an output format in a way that's not so fragile) but at the moment  moment it is fragile.  I guess one way of fixing this without changing stan_csv_reader much would be to let it read the standard .csv portion even if it fails to read the comment section correctly.

**Comment by ariddell** [comment]
@jeffalstott the hack I had in mind was faking the header cmdstan expects so that stansummary will read it.

**Comment by jeffalstott** [comment]
@ariddell  It looks like there is both a header and a footer. Perhaps @sakrejda can tell us what all stansummary is looking for? I.e. does it need both the header and the footer? Do the examples I copied from the cmdstan module show all the relevant info, are there edges cases with different behavior that isn't shown? Is the footer just those four lines?

**Comment by sakrejda** [comment]
@jeffalstott This is code I'm still working on understanding.  If you can send the PyStan file I'm willing to run stansummary and find where it fails on PyStan's files.  If there's a quick fix to make it more robust we could put that in the next release.  Most of the code that reads this is here: https://github.com/stan-dev/stan/blob/develop/src/stan/io/stan_csv_reader.hpp

**Comment by jeffalstott** [comment]
@sakrejda Below is the complete output written when using pystan with the `sample_file` option. This was run with just two iterations (one warmup). I ran it with some init values, which appear to not be written to the file at all.

```
# Sample generated by Stan
# stan_version_major=2
# stan_version_minor=9
# stan_version_patch=0
lp__,accept_stat__,stepsize__,treedepth__,n_leapfrog__,n_divergent__,beta.1,beta.2,beta.3,beta.4,beta.5,beta.6,beta.7,beta.8,mu_phi,var_phi,phi
1.22679e+08,0.918439,0.000488281,7,111,0,0.00334559,-0.00245425,0.0329689,-0.0547399,0.041858,-0.00192523,0.0147659,-0.00367984,0.459717,0.1431,0.645284
# Adaptation terminated
# Step size = 12.4029
# Diagonal elements of inverse mass matrix:
# 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

1.22679e+08,0,12.4029,1,1,1,0.00334559,-0.00245425,0.0329689,-0.0547399,0.041858,-0.00192523,0.0147659,-0.00367984,0.459717,0.1431,0.645284
#
#  Elapsed Time: 8.51 seconds (Warm-up)
#                2.53 seconds (Sampling)
#                11.04 seconds (Total)
#
```

**Comment by betanalpha** [comment]
I believe boost::lexical_cast cannot parse scientific notation, hence
the original error (I had suspected this but have been traveling and
keep forgetting to reply once I get back to my laptop).  CmdStan
is careful to not output scientific notation, but it looks like PyStan
is not in this case.

**Comment by ariddell** [comment]
PyStan is using a CSV writer from stan-dev/stan.

**Comment by sakrejda** [comment]
@jeffalstott Thanks for posting the file, probably won't get to do any digging till Friday.

**Comment by jeffalstott** [comment]
@sakrejda Any luck?

Back in the original discussion in the [Stan users list](https://groups.google.com/forum/#!category-topic/stan-users/general/N0UfmIgR9yU) I was advised to just use cmdstan instead. However, cmdstan is giving different results from pystan (cmdstan doesn't converge and has terrible n_effs, while pystan seems fine)*. So, for the moment I'm stuck with pystan, and having the ability to integrate multiple chains run on different computers would be great.

*I know that shouldn't be happening. I'll be submitting a separate issue about it later.

**Comment by ariddell** [comment]
Are you using cmdstan develop or a released version?

Perhaps we should move this issue somewhere else (like stan-dev/stan)
since it's a meta-issue?

**Comment by sakrejda** [comment]
@ariddell I will try to trouble-shoot the reader problem this afternoon so that's a stan-dev/stan issue. @jeffalstott for this particular issue is the root problem that PyStan doesn't have an equivalent to Stansummary?

**Comment by ariddell** [comment]
@jeffalstott Thanks for your attention to this. Let's move this out of PyStan for now since it's not really an issue that can be addressed at the PyStan level since PyStan uses stan-dev/stan for CSV writing. The non-alignment of PyStan and CmdStan results might be a PyStan issue but it's a different one.

**Comment by jeffalstott** [comment]
@ariddell Good question that I hadn't thought of! I had installed with the instructions from [Getting Started with Cmdstan](https://github.com/stan-dev/cmdstan/wiki/Getting-Started-with-CmdStan), and `git branch` says that put me on the develop branch. Oops. I assume I should try again with 2.9.0? pystan and cmdstan were sometimes giving similar results with small data sets (10k observations), but cmdstan started yielding crap with 100k+ observations and pystan kept giving reasonable results. I had hoped that was due to different behavior with inits (pystan's documentation isn't clear on what the default `random` init values exactly corresponds to). Could there be some other issue in the develop branch?

I will try this with cmdstan release 2.9.0 and see if there's still a problem. If so, then I'll post another issue.

**Comment by jeffalstott** [comment]
@sakrejda My wish list, from most- to least-pressing concern.

1. Have some way of combining chains created from using pystan on separate computers, at different times. 
2. Have the pystan `sample_file` write something that `stansummary` can parse (this would accomplish the first goal).
3. Have pystan have its own equivalent of `stansummary`, which took as inputs `StanFit4Model` objects (this would also accomplish the first goal).

**Comment by sakrejda** [comment]
@jeffalstott For the moment it looks like it's just being fragile in reading metadata from the .csv file, I'm going to come up with a temporary fix and see what the dev list thinks of it.. It should be at least possible to return empty metadata but read the .csv portion.

**Comment by sakrejda** [comment]
@ariddell If you don't mind doing an easy fix: stan_csv_reader is dying on @jeffalstott 's file because there is no space after the "=" in the first three lines.  Can you just add the spaces or is this a stan-dev/stan function that's messing up? The file version below (modified lines 2-4) works fine with stansummary.  Still working on a long-term fix but let me know if you're ok with doing the quick fix.
~~~
# Sample generated by Stan
# stan_version_major = 2
# stan_version_minor = 9
# stan_version_patch = 0
lp__,accept_stat__,stepsize__,treedepth__,n_leapfrog__,n_divergent__,beta.1,beta.2,beta.3,beta.4,beta.5,beta.6,beta.7,beta.8,
1.22679e+08,0.918439,0.000488281,7,111,0,0.00334559,-0.00245425,0.0329689,-0.0547399,0.041858,-0.00192523,0.0147659,-0.003679
# Adaptation terminated
# Step size = 12.4029
# Diagonal elements of inverse mass matrix:
# 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

1.22679e+08,0,12.4029,1,1,1,0.00334559,-0.00245425,0.0329689,-0.0547399,0.041858,-0.00192523,0.0147659,-0.00367984,0.459717,0
#
#  Elapsed Time: 8.51 seconds (Warm-up)
#                2.53 seconds (Sampling)
#                11.04 seconds (Total)
#
~~~

I'll leave it up to you whether to re-open/fix.  It does look like there is some stuff that could happen with the stan_csv_reader code to make it more robust too.

**Comment by ariddell** [comment]
I'm not sure where those lines are getting written. I'm think more likely than not being handled outside of any Python code. For a short term fix why not just use ``sed`` or something like that?

    echo 'stan_version_major=2' | sed 's/=/ = /'

**Comment by sakrejda** [comment]
@ariddell It's in that [dark place](https://github.com/stan-dev/pystan/blob/2fb318776f87fe11d009f2994ffe90c58ff30adc/pystan/stan_fit.hpp#L398) between PyStan and Stan.  But yeah, sed's an alternative solution

@jeffalstott I don't have time to check if modifying that line 398  of stan_fit.hpp from "=" to "= " fixes your problem but it would be pretty straightforward to check for someone who has built pystan from source (not me!)

I'll see if there's something to be done for the reader b/c this is silly.

**Comment by ariddell** [comment]
It's in RStan too, but in a different file: https://github.com/stan-dev/rstan/blob/3ea6066981a15e1ae0de86b71147ddf12e141496/rstan/rstan/inst/include/rstan/stan_args.hpp#L62

@jeffalstott As an enthusiastic supporter of a common serialization format for the *stans, I can say that I hope your problem is solved in the not too distant future. For now I think ``sed`` might be your best bet.

@sakrejda Is there an issue in stan or cmdstan where the common output format issue is being tracked that can be linked here for future reference?

**Comment by sakrejda** [comment]
@aridell: no issue yet although it's getting there. There's a wiki page where I've been working on documenting something that monkeys the current formats but is consistent enough that we could read/write it reliably without a lot of work on the interface side.

**Comment by sakrejda** [comment]
@ariddell @jeffalstott: There's an [issue](https://github.com/stan-dev/stan/issues/1907)  and pull request for stan_csv_reader now to fix this.

**Comment by ariddell** [comment]
Wonderful. Thanks @sakrejda!

**Comment by ariddell** [comment]
Wonderful. Thanks @sakrejda!
