### ISSUE TITLE
Fixed_param algorithm not yet implemented

### ISSUE THREAD

**Issue by samvoisin** [stan-dev/pystan#231]
I am attempting to perform prior predictive checks in PyStan3. It appears `algorithm` is no longer a valid kwarg for the `sample` or `build` methods? Is this correct or has it not been implemented? For example:

```
# prior predictive model
pp_model = stan.build(prior_pred_code, data=pp_data, random_seed=1)
pp_samps = pp_model.sample(num_samples=nsims, num_warmup=0, algorithm='Fixed_param')
```
raises the following error:

```
Building...
Found model in cache. Done.
Sampling...
Traceback (most recent call last):
...
ValueError: {'json': {'algorithm': ['Unknown field.']}}
```

**Comment by riddell-stan** [comment]
This hasn't yet been implemented.

It is one of the easiest and least controversial things which could be added after the 3.0 release. If others want this, please leave a :+1: response on the issue.

As always, we'd welcome help.

**Comment by betanalpha** [comment]
The `fixed_param` sampler is definitely pretty critical to a comprehensive Stan workflow.

**Comment by samvoisin** [comment]
@riddell-stan I would be happy to help with this. I think prior and posterior checks are critical for Bayesian modeling. However, I have not done much coding at the interface of stan and python. Is there anywhere you recommend I look first?

**Comment by riddell-stan** [comment]
I agree this is really important.

I'll expose fixed_param in httpstan today. I'd welcome help writing the tests and exposing things here in pystan. I'll keep you posted.

**Comment by riddell-stan** [comment]
Support added in httpstan, https://github.com/stan-dev/httpstan/pull/548

**Comment by riddell-stan** [comment]
@samvoisin Want to take a stab at this? The httpstan version which expoes fixed param sampling is available. The function call in pystan should look like this:

```
pp_samps = pp_model.fixed_param(...)
```

**Comment by samvoisin** [comment]
@riddell-stan Sure thing! I will take a look this evening (east coast).

**Comment by samvoisin** [comment]
@riddell-stan I was able to run the example in the [httpstan readme](https://github.com/stan-dev/httpstan) using `stan::services::sample::fixed_param`. I'm currently working on getting the full contents of my `.stan` file into the REST call.

**Comment by riddell-stan** [comment]
I just looked at `model.py` and realized that copying-and-pasting almost everything in the `sample` method (into a `fixed_param` method) is probably not what we want to do.

I'll submit a PR today or tomorrow to make it much easier to add the fixed_param method.

**Comment by riddell-stan** [comment]
@samvoisin Once #235 is merged you should be able to add the ``fixed_param`` method. Something like this:

```python
    def fixed_param(self, **kwargs) -> stan.fit.Fit:
        """Draw samples from the model using ``stan::services::fixed_param``.

        More docstring...

        Returns:
            Fit: instance of Fit allowing access to draws.

        """
        kwargs["function"] = "stan::services::sample::fixed_param"
        return self._create_fit(kwargs)
```

We'll also need some tests.
