### ISSUE TITLE
distutils.errors.CompileError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by Hart19** [stan-dev/pystan#245]
#### Summary:

Compilation error on Pystan 2.9.0.0 
#### Description:

Trying to run stan_example.py and get the distutils.errors.CompileError.  A previous discussion (219) on this error said it was Cython.  I was already running Cython 0.24 but since there was 0.24.1 I upgraded.  This upgrade did not resolve my issue.

 python stan_example.py
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5afbb95bd3cd8bb6e35e922f39ddb6e2 NOW.
Traceback (most recent call last):
  File "stan_example.py", line 14, in <module>
    model = pystan.StanModel(model_code = model_code)
  File "/usr/lib/python2.7/site-packages/pystan/model.py", line 312, in **init**
    build_extension.run()
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 496, in build_extension
    depends=ext.depends)
  File "/usr/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile
    raise CompileError, msg
distutils.errors.CompileError: command 'gcc' failed with exit status 1
#### PyStan Version:

Pystan 2.9.0.0 
#### Cython Version:

Cython-0.24.1
#### Python Version:

Python 2.7.10 
#### GCC Version:

GCC 4.7.2 20130108
#### Operating System:

SuSE 11.4 (x86_64)

**Comment by ariddell** [comment]
Thanks for the report. A bit more information is needed to figure out what went wrong during compilation. Can you try running:

```
model = pystan.StanModel(model_code = model_code, verbose=True)
```

**Comment by Hart19** [comment]
python stan_example.py
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5afbb95bd3cd8bb6e35e922f39ddb6e2 NOW.
INFO:pystan:OS: linux2, Python: 2.7.10 (default, Aug  7 2015, 13:36:07)
[GCC 4.7.2 20130108 [gcc-4_7-branch revision 195014]], Cython 0.24.1
Compiling /tmp/tmpnSdfMQ/stanfit4anon_model_5afbb95bd3cd8bb6e35e922f39ddb6e2_7086623867173230264.pyx because it changed.
[1/1] Cythonizing /tmp/tmpnSdfMQ/stanfit4anon_model_5afbb95bd3cd8bb6e35e922f39ddb6e2_7086623867173230264.pyx
building 'stanfit4anon_model_5afbb95bd3cd8bb6e35e922f39ddb6e2_7086623867173230264' extension
creating /tmp/tmpnSdfMQ/tmp
creating /tmp/tmpnSdfMQ/tmp/tmpnSdfMQ
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -I/tmp/tmpnSdfMQ -I/usr/lib/python2.7/site-packages/pystan -I/usr/lib/python2.7/site-packages/pystan/stan/src -I/usr/lib/python2.7/site-packages/pystan/stan/lib/stan_math -I/usr/lib/python2.7/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.2.4 -I/usr/lib/python2.7/site-packages/pystan/stan/lib/stan_math/lib/boost_1.58.0 -I/usr/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c /tmp/tmpnSdfMQ/stanfit4anon_model_5afbb95bd3cd8bb6e35e922f39ddb6e2_7086623867173230264.cpp -o /tmp/tmpnSdfMQ/tmp/tmpnSdfMQ/stanfit4anon_model_5afbb95bd3cd8bb6e35e922f39ddb6e2_7086623867173230264.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
/tmp/tmpnSdfMQ/stanfit4anon_model_5afbb95bd3cd8bb6e35e922f39ddb6e2_7086623867173230264.cpp:55:20: error: Python.h: No such file or directory
/tmp/tmpnSdfMQ/stanfit4anon_model_5afbb95bd3cd8bb6e35e922f39ddb6e2_7086623867173230264.cpp:57:6: error: #error Python headers needed to compile C extensions, please install development version of Python.
Traceback (most recent call last):
  File "mod.stan_example.py", line 14, in <module>
    model = pystan.StanModel(model_code=model_code, verbose=True)
  File "/usr/lib/python2.7/site-packages/pystan/model.py", line 312, in __init__
    build_extension.run()
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 496, in build_extension
    depends=ext.depends)
  File "/usr/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile
    raise CompileError, msg
distutils.errors.CompileError: command 'gcc' failed with exit status 1

**Comment by ariddell** [comment]
That's strange. verbose=True usually gives me a lot more detail.

Can you share the model code?

**Comment by ahartikainen** [comment]
This line
> /stanfit4anon_model_5afbb95bd3cd8bb6e35e922f39ddb6e2_7086623867173230264.cpp:57:6:
 error: #error Python headers needed to compile C extensions, please install development version of Python.

You need to install development version of python (python-dev|python-devel).

On ubuntu/debian:
    sudo apt-get install python-dev
On SuSE:
    sudo zypper install python-devel

**Comment by ariddell** [comment]
Closed for now. Please reopen if there are more details.
