### ISSUE TITLE
No module named 'pystan'

### ISSUE THREAD

**Issue by microprediction** [stan-dev/pystan#246]
After installing pystan, either directly from github or from pypi, I subsequently get a pystan import error. 

```
import pystan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pystan'
```

**Comment by microprediction** [comment]
If it helps, this stopped working 20 hours ago.

**Comment by riddell-stan** [comment]
PyStan 3 was released on 26. March, 2021. PyStan 3 makes numerous **backwards-incompatible changes**. You can read more about the changes in [Upgrading to 3.0](https://pystan.readthedocs.io/en/latest/upgrading.html#upgrading-to-3-0).

The module name change is mentioned in the upgrading guide.

**Comment by hemangjoshi37a** [comment]
Any updates? Have anyone found any solutions yet?

**Comment by riddell-stan** [comment]
Please see the [Upgrading to 3.0](https://pystan.readthedocs.io/en/latest/upgrading.html#upgrading-to-3-0) guide.

Here's how you sample with PyStan 3:

```python
import stan

schools_code = """data { ..."""
schools_data = {'J': 8, ... }

posterior = stan.build(schools_code, data=schools_data, random_seed=1)
fit = posterior.sample(num_chains=4, num_samples=1000)
fit["eta"]  # array with shape (8, 4000)
```
