### ISSUE TITLE
8schools.stan is unavailable (404)

### ISSUE THREAD

**Issue by evelynmitchell** [stan-dev/pystan#247]
#### Summary:
https://raw.githubusercontent.com/stan-dev/pystan/develop/pystan/stan/src/models/misc/eight_schools/eight_schools.stan
no longer resolves

#### Reproducible Steps:
Found off of: 
https://pystan.readthedocs.io/en/latest/getting_started.html

#### Current Output:
404 not found

#### Expected Output:
To be able to download 8schools.stan

**Comment by bob-carpenter** [comment]
It is indeed missing.  It downloads, then returns a text file just saying `404`.  Weird.
