### ISSUE TITLE
arguments for plugin

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan#255]
Is there a way to give arguments for the plugin?

**Comment by riddell-stan** [comment]
What kinds of arguments are you thinking about? How would they be provided?

**Comment by ahartikainen** [comment]
There are couple of different arguments I'm thinking.

"Constants" -> e.g. arguments that handle output accuracy or e.g. output type

"Dynamic" -> arguments that are model dependent, (parameter names etc)


I was thinking of somekind of **kwargs behaviour that that could grab them or maybe a dictionary for 'post_sample_kwargs'. Or maybe the plugins could eat all kwargs that are not used by pystan. Tbh don't want to clutter the pystan side.

**Comment by riddell-stan** [comment]
I'm still not sure what you mean. Can you sketch a simple Plugin which would accept arguments? There's an example of a Plugin in the docs.
