### ISSUE TITLE
plugin locations

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan#256]
Is there a possibility to add more plugin location?

I'm thinking of 

    pre_build
    pre_sample

Where the example plugin could call e.g. `nest_asyncio`?

**Comment by riddell-stan** [comment]
With one exception (#150), it's fair to say that httpstan and pystan are feature complete. At least for the next six months at least, adding a feature which increases maintenance costs (even marginally) will require a strong justification and extensive discussion on the Stan forums.

PyStan is 769 LOC right now. It's *extremely* easy to fork. Forks are easy to publish on PyPI. Those interested in adding features are strongly encouraged to try forking first.

**Comment by ahartikainen** [comment]
Sure, sounds ok
