### ISSUE TITLE
Commit message format is not being checked

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan#260]
Commit message format is not being checked. This was being checked earlier.

**Comment by ahartikainen** [comment]
What kind of checks do we want to have?

We used to have external app right? What if we move the check into the workflow? I think there are different Actions that can handle this issue

e.g.

https://github.com/marketplace/actions/commit-linter

**Comment by riddell-stan** [comment]
I'd settle for re-enabling whatever we had before. I think it was commitlint.

**Comment by riddell-stan** [comment]
Fixed for the moment.
