### ISSUE TITLE
win64 pystan.stan(model...) fit fails to find compiled module

### ISSUE THREAD

**Issue by csobchuk** [stan-dev/pystan#263]
#### Summary:
setup is Win64, anaconda 64 bit python 3.5.2 with Visual Studio 2015, pip install pystan :: version 2.12 and going through the getting started documentation on 
http://pystan.readthedocs.io/en/latest/getting_started.html
on a jupyter notebook on latest chrome browser.

#### Description:
each line works up until 
> fit=pystan.stan(model_code=schools_code, data=schools_dat, iter=1000, chains=4)
which does compile the pyd file but exist with the following response:
ImportError: No module named 'stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_2419847978121782363'

a number of files are created in the temp directory and then removed with the exception of the above .pyd file

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
jupyter notebook just seems to hang waiting - [*] 

from the jupyter console the part where it seems to start to fail begins here:
C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\site-packages\pystan\stan\lib\stan_math_2.12.0\stan/math/prim/sca
l/prob/normal_log.hpp(84): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\site-packages\pystan\stan\lib\stan_math_2.12.0\stan/math/prim/sca
l/prob/normal_log.hpp(88): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\site-packages\pystan\stan\lib\stan_math_2.12.0\stan/math/prim/sca
l/prob/normal_log.hpp(89): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\site-packages\pystan\stan\lib\stan_math_2.12.0\stan/math/prim/sca
l/prob/normal_log.hpp(107): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\site-packages\pystan\stan\lib\stan_math_2.12.0\stan/math/prim/sca
l/prob/normal_log.hpp(109): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\site-packages\pystan\stan\lib\stan_math_2.12.0\stan/math/prim/sca
l/prob/normal_log.hpp(111): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_2419847978121782363.obj : warning LNK4197: export 'PyInit_stanfit4an
on_model_95013624776d537c3cd7cd4d641c30e0_2419847978121782363' specified multiple times; using first specification
   Creating library C:\Users\myuser\AppData\Local\Temp\tmprezokzv_\Users\myuser\AppData\Local\Temp\tmprezokzv_\stanfit
4anon_model_95013624776d537c3cd7cd4d641c30e0_2419847978121782363.cp35-win_amd64.lib and object C:\Users\myuser\AppData\
Local\Temp\tmprezokzv_\Users\myuser\AppData\Local\Temp\tmprezokzv_\stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_
2419847978121782363.cp35-win_amd64.exp
Generating code
Finished generating code
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Process SpawnPoolWorker-3:
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\queues.py", line 345, in get
    return ForkingPickler.loads(res)
ImportError: No module named 'stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_2419847978121782363'
Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\queues.py", line 345, in get
    return ForkingPickler.loads(res)
ImportError: No module named 'stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_2419847978121782363'
Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\queues.py", line 345, in get
    return ForkingPickler.loads(res)
ImportError: No module named 'stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_2419847978121782363'
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "C:\Users\myuser\AppData\Local\Continuum\Anaconda3\lib\multiprocessing\queues.py", line 345, in get
    return ForkingPickler.loads(res)
ImportError: No module named 'stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_2419847978121782363'

#### Expected Output:
la = fit.extract(permuted=True)  # return a dictionary of arrays
mu = la['mu']

## return an array of three dimensions: iterations, chains, parameters
a = fit.extract(permuted=False)

print(fit)

fit.plot()

Inference for Stan model: anon_model_95013624776d537c3cd7cd4d641c30e0.
4 chains, each with iter=20; warmup=10; thin=1; 
post-warmup draws per chain=10, total post-warmup draws=40.

           mean se_mean     sd   2.5%    25%    50%    75%  97.5%  n_eff   Rhat
mu         5.72    0.49   3.13   0.77   3.82   5.24   7.27  15.34     40    1.2
tau        4.21    0.46   2.94   0.15   2.11   3.88   6.64   10.0     40   1.01
eta[0]     0.26    0.19   1.17  -2.08  -0.45   0.28   0.72   2.82     40   0.96
eta[1]     0.07    0.17   1.07  -1.64  -0.97   0.16   1.04   1.87     40   1.09
eta[2]    -0.06    0.17    1.1  -2.33  -0.82  -0.12    0.8   1.93     40   0.96
eta[3]      0.2    0.15   0.97  -1.44  -0.58   0.13   0.71   2.33     40    1.0
eta[4]    -0.28    0.13   0.82  -1.84  -0.68  -0.37   0.45   1.22     40   1.08
eta[5]    -0.02    0.14   0.87  -1.79  -0.56  -0.05   0.69    1.7     40    1.0
eta[6]     0.23    0.15   0.95  -2.16  -0.39   0.25   0.98    2.0     40   1.03
eta[7]     0.28    0.19   1.21  -2.28  -0.48   0.52   1.02   2.28     40   0.94
theta[0]    7.1    1.01   6.41  -5.26   2.75   5.82  11.07  23.61     40   0.99
theta[1]   6.51    0.98   6.19   -6.6    1.9   6.44  10.68  18.37     40   1.08
theta[2]   5.73    1.03   6.55  -7.48   1.77   4.37   8.34  21.83     40    1.1
theta[3]   6.71    0.91   5.75  -2.77   1.95   4.88  11.38  17.01     40   1.01
theta[4]   4.32    0.67   4.26  -3.78   1.56    3.8   7.66  13.31     40   1.06
theta[5]   5.24    0.77   4.84  -5.32   2.24    4.8   9.27  13.73     40   0.98
theta[6]    6.9    0.76   4.82   0.05   3.09   5.92    9.7   17.7     40   0.99
theta[7]   8.03    1.13   7.16  -2.45   2.86   6.01  11.15  26.48     40   1.02
lp__      -6.15    0.39   2.45 -11.24  -7.94  -5.63  -4.58  -1.22     40   1.12

Samples were drawn using NUTS(diag_e) at Fri Sep 30 20:02:40 2016.
For each parameter, n_eff is a crude measure of effective sample size,
and Rhat is the potential scale reduction factor on split chains (at 
convergence, Rhat=1).

#### PyStan Version:
2.12.0.0
#### Python Version:
3.5.2
#### Operating System:
windows 7 enterprise 64 bit

**Comment by ariddell** [comment]
PyStan can't sample in parallel on windows, you need to specify ``n_jobs=1`` in the call to Stan.

Support for Windows is new to PyStan. It might make sense to automatically set ``n_jobs=1``; it's not difficult to detect that a user is running windows.

**Comment by csobchuk** [comment]
Thanks Allen. Works great.
