### ISSUE TITLE
Install error on macOS: can't find expression_grammar_inst.cpp

### ISSUE THREAD

**Issue by fonnesbeck** [stan-dev/pystan#267]
Attempting to install piston following the instructions on the README results in the following error:

```
gcc: pystan/stan/src/stan/lang/grammars/expression_grammar_inst.cpp
clang: error: no such file or directory: 'pystan/stan/src/stan/lang/grammars/expression_grammar_inst.cpp'
clang: error: no input files
clang: error: no such file or directory: 'pystan/stan/src/stan/lang/grammars/expression_grammar_inst.cpp'
clang: error: no input files
error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/fonnescj/anaconda3/envs/dev/include -arch x86_64 -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12 -Ipystan/stan/src -Ipystan/stan/lib/stan_math_2.12.0/ -Ipystan/stan/lib/stan_math_2.12.0/lib/eigen_3.2.9 -Ipystan/stan/lib/stan_math_2.12.0/lib/boost_1.60.0 -Ipystan/stan/lib/stan_math_2.12.0/lib/cvodes_2.8.2/include -I/Users/fonnescj/anaconda3/envs/dev/include/python3.5m -c pystan/stan/src/stan/lang/grammars/expression_grammar_inst.cpp -o build/temp.macosx-10.6-x86_64-3.5/pystan/stan/src/stan/lang/grammars/expression_grammar_inst.o -Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized" failed with exit status 1
```

Building on macOS 10.12 with Python 3.5.2 (Anaconda).

**Comment by ariddell** [comment]
Installing from source? Have the submodules been grabbed?

**Comment by ahartikainen** [comment]
I could (almost) duplicate the issue if `--recursive` is dropped from git line 
(OSX 10.11 with miniconda python 3.5.2)

    git clone https://github.com/stan-dev/pystan.git
    cd pystan
    python setup.py install

vs

    git clone --recursive https://github.com/stan-dev/pystan.git
    cd pystan
    python setup.py install

Error:

    gcc: pystan/stan/src/stan/lang/grammars/indexes_grammar_inst.cpp
    clang: error: no such file or directory: 'pystan/stan/src/stan/lang/grammars/indexes_grammar_inst.cpp'
    clang: error: no input files
    clang: error: no such file or directory: 'pystan/stan/src/stan/lang/grammars/indexes_grammar_inst.cpp'
    clang: error: no input files
    error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/user1/miniconda2/envs/tmp35/include -arch x86_64 -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12 -Ipystan/stan/src -Ipystan/stan/lib/stan_math_2.12.0/ -Ipystan/stan/lib/stan_math_2.12.0/lib/eigen_3.2.9 -Ipystan/stan/lib/stan_math_2.12.0/lib/boost_1.60.0 -Ipystan/stan/lib/stan_math_2.12.0/lib/cvodes_2.8.2/include -I/Users/user1/miniconda2/envs/tmp35/include/python3.5m -c pystan/stan/src/stan/lang/grammars/indexes_grammar_inst.cpp -o build/temp.macosx-10.6-x86_64-3.5/pystan/stan/src/stan/lang/grammars/indexes_grammar_inst.o -Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized" failed with exit status 1

OT: 
After a package is installed with `python setup.py install`, uninstalling the package can be challenging task. The last step can be done with `pip`. Then `pip uninstall packagename` works.

    git clone --recursive https://github.com/stan-dev/pystan.git
    cd pystan
    pip install .

or even straight from git with pip.

    pip install git+https://github.com/stan-dev/pystan

**Comment by fonnesbeck** [comment]
Ah, that's it. Left out the `--recursive` flag. Sorry for the trouble. Keep up the good work!

**Comment by ariddell** [comment]
It would be great if we could get ``pip`` to do the recursive clone.

This might be solved permanently in a future release. PyStan doesn't really need to use submodules. I'm inclined just to add a copy of Stan to the repository. Seems like this is the way things work on mercurial-based repositories and, of course, with monorepos.

**Comment by ahartikainen** [comment]
Hmm. Is pip not downloading the submodule stan?

I created a new conda environment and runned `pip install git+...`. I was able to do 8 schools after installation. Did I do something "wrong"?

**Comment by ariddell** [comment]
If ``pip install`` does a recursive clone that's great. I rather imagine that most people installing from source want to see/edit the source -- otherwise they should just use pip since we have wheels.

**Comment by ahartikainen** [comment]
True.

I would still suggest using 'pip install .' in setup folder for convenient uninstall.
