### ISSUE TITLE
calculate my own r-hat

### ISSUE THREAD

**Issue by dirknbr** [stan-dev/pystan#267]
If I wanted to calculate my own r-hat, can I assume that when draws from different chains are stacked together they are stacked like

parameter has dim 1
num_chains = 2
num_samples = 100

The first 100 will be chain 1 and the next 100 will chain 2?

**Comment by ahartikainen** [comment]
For that you might want to check how to get non-stacked (raw ndarray) draws.

OT. You might want to check `arviz.rhat` functionality

**Comment by dirknbr** [comment]
it seems reshaping works a bit differently, it interleaves them

``` 
>>> x
array([[ 1, 11],
       [ 2, 12]])
>>> y = x.reshape(4)
>>> y
array([ 1, 11,  2, 12])
>>> y.reshape((2, 2))
array([[ 1, 11],
       [ 2, 12]])
```

**Comment by riddell-stan** [comment]
Could we move this to the discussion forum? The issue tracker is for bugs.
