### ISSUE TITLE
ImportError when compiling model with Anaconda in Docker

### ISSUE THREAD

**Issue by jonasbusk** [stan-dev/pystan#270]
#### Summary:

Stan fails with an ImportError when compiling the C++ code for a model with Anaconda in Docker.

#### Description:

I've pip installed pystan in the continuumio/anaconda Docker image and can import pystan in Python without errors. But when compiling a Stan model (for example the [eight schools example](http://pystan.readthedocs.io/en/latest/getting_started.html#example-1-eight-schools)), I get an ImportError. 

#### Reproducible Steps:

1. Build docker image with pystan from the following Dockerfile:

```
FROM continuumio/anaconda:latest

RUN apt-get -y update && apt-get install -y build-essential
RUN pip install pystan
```

2. Run the Docker image.
3. `$ python eight_schools.py`

#### Current Output:

```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_95013624776d537c3cd7cd4d641c30e0 NOW.
Traceback (most recent call last):
  File "eight_schools.py", line 30, in <module>
    iter=1000, chains=4)
  File "/opt/conda/lib/python2.7/site-packages/pystan/api.py", line 372, in stan
    verbose=verbose)
  File "/opt/conda/lib/python2.7/site-packages/pystan/model.py", line 316, in __init__
    self.module = load_module(self.module_name, lib_dir)
  File "/opt/conda/lib/python2.7/site-packages/pystan/model.py", line 55, in load_module
    return imp.load_module(module_name, *module_info)
ImportError: /tmp/tmp5yprKc/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_5097586568873299303.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
```

#### Expected Output:

No errors.

#### PyStan Version:

'2.12.0.0'

#### Python Version:

Python 2.7.12 :: Anaconda 4.2.0 (64-bit)

#### Operating System:

continuumio/anaconda Docker image

**Comment by ariddell** [comment]
Likely related to #269

**Comment by jonasbusk** [comment]
Like [#269](https://github.com/stan-dev/pystan/issues/269), using Anaconda 4.0.0 works fine.

Dockerfile:

```
FROM continuumio/anaconda:4.0.0

RUN apt-get -y update && apt-get install -y build-essential
RUN pip install pystan
```

**Comment by ariddell** [comment]
Closing in favor of #269 . I'm persuaded it's an issue with the new Cython version.
