### ISSUE TITLE
Add include=bool parameter to pystan.stan

### ISSUE THREAD

**Issue by Denisevi4** [stan-dev/pystan#277]
Could you add include parameter to pystan.stan, the same as for RStan

include	
Logical scalar defaulting to TRUE indicating whether to include or exclude the parameters given by the pars argument. If FALSE, only entire multidimensional parameters can be excluded, rather than particular elements of them.

**Comment by ariddell** [comment]
The underlying issue is that there are limits on memory, right? Is there any other reason to exclude/include params?

**Comment by ahartikainen** [comment]
Is this something we want to change?

**Comment by riddell-stan** [comment]
I'll close this for now. I think there are other priorities right now and I know that people have mentioned supporting parameter pruning at the Stan C++ level.
