### ISSUE TITLE
Create a psis-loo Python package

### ISSUE THREAD

**Issue by avehtari** [stan-dev/pystan#278]
#### Summary:
Add psis.py from https://github.com/avehtari/PSIS/tree/master/py

#### Description:
It would be nice is PyStan would include PSIS-LOO
Python code is available at https://github.com/avehtari/PSIS/tree/master/py

I was going to make a PyStan version of rstanarm demonstration as a Kaggle notebook https://www.kaggle.com/avehtari/d/uciml/pima-indians-diabetes-database/bayesian-logistic-regression-with-rstanarm but that would require adding psis.py to PyPI, but since PyStan is already in PyPI, it would be easier to just include psis.py to PyStan.

**Comment by ariddell** [comment]
Adding things to pypi is really easy. I'm happy to offer advice. Is psis-loo in RStan or is it a separate package?

**Comment by avehtari** [comment]
For R there is loo package which is in CRAN. 

For Python there is psis-loo code https://github.com/avehtari/PSIS/tree/master/py and it's not in pypi

R loo package has now more features than the above mentioned Python psis-loo code, but even the basic psis-loo code in pypi or as part of PyStan would be helpful.

I interpret your comment so that you recommend adding the current psis-loo Pythin code to pypi?

**Comment by jgabry** [comment]
Devin started working on a package for python (https://github.com/detcitty/loo) but I'm not sure what the status of that is.

**Comment by bob-carpenter** [comment]
He said he wanted to come back and keep working on it,
but then I never heard anything again.  Why don't you
try emailing him directly?

**Comment by jgabry** [comment]
I did email him earlier this fall but I don't think I heard back. I can
reach out again.

**Comment by ariddell** [comment]
Getting a loo pypi package together seems like low-hanging fruit. Any news @jgabry ? The repo @detcitty started looks like a good start.

**Comment by jgabry** [comment]
Agree that it's a low-hanging fruit. @detcitty are you planning to continue working on this or should we look into finding someone else to pick up where you've left off?

**Comment by ariddell** [comment]
@bgoodri could this be a summer of code project (if @detcitty doesn't have time)?

**Comment by bgoodri** [comment]
Yeah, @jgabry would be a better mentor though.

**Comment by jburos** [comment]
FYI in case this is helpful, we ported the PSIS-LOO code from [https://github.com/avehtari/PSIS/tree/master/py] into a python package called [stanity](http://github.com/hammerlab/stanity). It's meant to be an interim solution until a more official package was released, but am also happy to help with that effort if I can.

**Comment by ariddell** [comment]
This is great. Thanks!

Does this mean we don't need a separate psis package on PyPI?

Should we perhaps create a section "third-party libraries" in the documentation and point everyone to stanity? (This is what, for example, aiohttp does: [third-party libraries](https://aiohttp.readthedocs.io/en/stable/third_party.html).)

**Comment by ariddell** [comment]
On second thought, what about adding psis-loo to pystan under pystan.model_selection (to mirror [sklearn](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.LeaveOneOut.html#sklearn.model_selection.LeaveOneOut))? Does this interest anyone?

**Comment by ahartikainen** [comment]
I think ArviZ library will include PSIS-loo code.

I still need to make sure it works with PyStan fits.

**Comment by ahartikainen** [comment]
@avehtari are you fine with ArviZ solution?

**Comment by avehtari** [comment]
> @avehtari are you fine with ArviZ solution?

yes
