### ISSUE TITLE
Installation of pystan on Fedora 33 causes fbprophet to fail

### ISSUE THREAD

**Issue by Shadmeister** [stan-dev/pystan#278]
#### Describe the bug

Installing pystan using pip3 on a Linux build Fedora 33 causes installation of fbprophet to fail. I installed fbprophet beginning of March 2021 and it worked. Upgraded the PC and later installed fbprophet (21/04/2021 and 22/04/201) and it fails with error "no module pystan", although using pip3 pystan is installed. Error was :

`ModuleNotFoundError: No module named 'pystan'`

I noticed that the installation directory structure is different to other modules, such that 

/home/richard/.local/lib/python3.9/site-packages/pystan-3.0.2.dist-info/*
/home/richard/.local/lib/python3.9/site-packages/stan/

As per other modules, the directory would be "pystan" and not "stan". 

I copied the "stan" directory to "pystan" (created), ran the fbprophet again, and the error response was then :

`AttributeError: module 'pystan' has no attribute 'StanModel'`

Therefore, are the Linux installation files in error ?. I can see that 3.0.2 was created 13th April 2021, which then correlates with the installation working March 2021, and not now ??

**Comment by ahartikainen** [comment]
This is pystan 3 vs 2.x problem

Fix this with

    pip install "pystan<3"

**Comment by Shadmeister** [comment]
Hi,
Excellent, that has allowed pystan to be compiled and installed, and then fbprophet.
Thanks for the very prompt response, much appreciated. 
Regards,
Shadmeister.

**Comment by carolfs** [comment]
Does this mean that pystan 3 is broken on Fedora? I also tried to install pystan both on Python 3.9 and Python 3.8, but every time I got a ModuleNotFoundError.

**Comment by Shadmeister** [comment]
> Does this mean that pystan 3 is broken on Fedora? I also tried to install pystan both on Python 3.9 and Python 3.8, but every time I got a ModuleNotFoundError.
Hi,
Using pip3, i ran the command as provided by ahartikainen, which installs pystan with version less than 3. Once this was completed, fbprophet installed correctly. 
The issue is with pystan being completely re-written, which breaks other installations - see the following link
[Pystan Upgrading](https://pystan.readthedocs.io/en/latest/upgrading.html)

Regards,
Shadmeister.

**Comment by carolfs** [comment]
The provided command worked for me as well, but it's clear that pystan 3 still has a bug, no? Why shouldn't it work on Fedora? BTW I don't have fbprophet, just trying to use pystan directly.

**Comment by Shadmeister** [comment]
> The provided command worked for me as well, but it's clear that pystan 3 still has a bug, no? Why shouldn't it work on Fedora? BTW I don't have fbprophet, just trying to use pystan directly.

I can only assume that since pystan 3 is a complete rewrite, that any other module or python script will fail, unless written specifically for pystan 3. If you examine the upgrade link i provided, the import command has changed from `import pystan` (version 2) to `import stan` (version 3).

Regards,
Shadmeister.

**Comment by carolfs** [comment]
All I did was install pystan with `pip install pystan` (finished successfully), then `import pystan`, and it doesn't work.

**Comment by Shadmeister** [comment]
> All I did was install pystan with `pip install pystan` (finished successfully), then `import pystan`, and it doesn't work.

Yes, you need to `import stan` as per the link provided on upgrading pystan. 
Regards,
Shadmeister.

**Comment by carolfs** [comment]
Ok, I tried that and now at least I got a different error: `RuntimeError: Unable to import low-level simdjson bindings.` I guess I'll stick to pystan 2 for the moment.
