### ISSUE TITLE
PyStan cannot run inside an asyncio event loop (use of `asyncio.run`)

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan#280]
#### Describe the bug

PyStan's use of `asyncio.run` fails when called inside an event loop. This is *not* a typical use of PyStan, but it would be nice to support if we can.

#### Steps/Code to Reproduce

Easy to reproduce. Call virtually any function inside an async function.

**Comment by riddell-stan** [comment]
@hugbubby I tried to solve this. There's not an obvious solution, as far as I know. Would you mind sharing the context in which you were trying to use PyStan from an async function?

**Comment by hugbubby** [comment]
Mostly, if pystan is being used outside of manual one-off sampling, it's as a backend system which has to from time-to-time communicate the results of its samples to other programs. In our case, run a web server that other systems can query. The web server we use is called aiohttp and runs asynchronously.

**Comment by riddell-stan** [comment]
That's a reasonable use case.

I think this is going to be a wontfix for now (because there's no easy solution). But I think it should be easy for you to modify pystan so it works in your particular case. You can hack `build` and `sample` into async functions without too much work.

**Comment by k-hashimoto** [comment]
I'm facing same issue. I cloud install pystan successfully, but I have same error msg when I tried sample code on readme.

my environment is...
- python : '3.7.10 (default, Apr 10 2021, 16:02:25) \n[GCC 8.3.0]
- pystan: Version: 3.0.2

GCC version is lower than required one, but I think compiler version do not affect this issue.

**Comment by riddell-stan** [comment]
Since this likely does not concern a bug, would you mind posting this problem on the Stan Forums, https://discourse.mc-stan.org/ ? That's the best place to get help in cases like this.
