### ISSUE TITLE
PyStan memory leak?

### ISSUE THREAD

**Issue by fonnesbeck** [stan-dev/pystan#280]
When attempting to run [this model](https://gist.github.com/fonnesbeck/3df0392d675647571e2ab42f31b9b64e) on Python 3.5.2 (running on macOS 10.12) with PyStan 2.12 I observe that four Python processes spin up and immediately start consuming memory until my system locks up. Here is screen shot of the processes:

![](http://d.pr/i/Wimw+)

I do get a few warnings about the LKJ not being positive definite for the Metropolis proposal, but no errors.

**Comment by bob-carpenter** [comment]
Could you be a bit more specific about what you're doing
to run the model?

Doesn't sound like preallocating memory for draws is
the problem if you get warnings about LKJ.

Are you running NUTS?  There's no Metropolis proposal in NUTS.  
In the paper version, it did slice sampling and now it does
a multinomial draw over points on the trajectory (including
the starting point, so it may look like a Metropolis rejection
if that point is selected).

- Bob

**Comment by fonnesbeck** [comment]
I'm running exactly what is in the Jupyter notebook in the link at the top of the issue report (I'm trying to replicate an analysis Frank Harrell is doing). Here is the actual call:

```python
fit = pystan.stan(model_code=model, iter=10000, seed=7,
                  data=dict(x=data.sbp0, 
                            y1=data.sbp, 
                            y2=data.ds.astype(int), 
                            treat=(data.trt=='B').astype(int), 
                            n=data.shape[0], 
                            sigma_b=(-10/dst.norm.ppf(0.1), np.log(0.5)/dst.norm.ppf(0.05)), 
                            Zero=(0,0)))
``` 

I assume this is using NUTS if I don't specify otherwise, yes?

**Comment by fonnesbeck** [comment]
The memory usage escalates very quickly, from a few MB up to well over 15 GB per process until I have to kill it.

**Comment by fonnesbeck** [comment]
[Here is the console output](https://gist.github.com/fonnesbeck/887fff7efda8a15b939450960fa87e38) just before I shut it down. I am trying again, this time using the current master rather than whichever release pip installs.

**Comment by fonnesbeck** [comment]
OK, installing from master rather than the 2.12 release seems to cure the memory issue. Still runs slow, but it sounds like I have some matrix specification/initialization issues to deal with.

I will close this.
