### ISSUE TITLE
Interrupted runs continue using CPU after session closed

### ISSUE THREAD

**Issue by fonnesbeck** [stan-dev/pystan#281]
When I interrupt a MCMC run in PyStan (running from Jupyter notebook), the four Python processes continue to run and peg the CPUs. The only way to stop this is to manually kill the processes.

Running PyStan built from today's master on Python 3.5.2 (Anaconda) and Jupyter 5 with macOS 10.12.

**Comment by fonnesbeck** [comment]
This appears to be joblib-related; when I run `n_jobs=1` the behavior goes away.

**Comment by ariddell** [comment]
Thanks for the report. There is an interrupt callback which should be propagated. Sounds like it's not working.

**Comment by ahartikainen** [comment]
Not sure if this the source of the problem.

Multiprocessing is called in pystan/model.py:_map_parallel

    # line 79
    pool = multiprocessing.Pool(processes=n_jobs)
    map_result = pool.map(function, args)
    pool.close()
    pool.join()

So if this is interrupted when running line 80 pool.map. My guess is that .close() and .join() are not called. 

Maybe [try-finally clause](https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions) could help?

    try:
        pool = multiprocessing.Pool(processes=n_jobs)
        map_result = pool.map(function, args)
    finally:
        pool.close()
        pool.join()

**Comment by ariddell** [comment]
Good catch! I'm sure that's it.
