### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by spmacdonald** [stan-dev/pystan#288]
When I try to install pystan I get the following error:

```
$ python3 -m pip install pystan
Collecting pystan
  Using cached https://files.pythonhosted.org/packages/10/33/4402eb2df8aff1d45da3f2b91785f56c847f5634eb02c6eb9094cb18e905/pystan-3.1.0-py3-none-any.whl
Requirement already satisfied: aiohttp<4.0,>=3.6 in /home/scott/GBE_VIRTUALS/py-3.8/lib/python3.8/site-packages (from pystan)
Collecting httpstan<4.5,>=4.4 (from pystan)
  Could not find a version that satisfies the requirement httpstan<4.5,>=4.4 (from pystan) (from versions: 0.1.0, 0.1.1, 0.2.3, 0.2.5, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.6.0, 0.7.2, 0.7.3, 0.7.5, 0.7.6, 0.8.0, 0.9.0, 0.10.1, 1.0.0)
No matching distribution found for httpstan<4.5,>=4.4 (from pystan)
```

$ python
Python 3.8.0 (default, Feb 25 2021, 22:10:10)
[GCC 8.4.0] on linux

I tried to install httpstan manually, but it defaulted to version 1.0.0.  Not sure where I have gone wrong...

**Comment by riddell-stan** [comment]
What operating system are you using?

**Comment by spmacdonald** [comment]
Ubuntu 18.04.  

I think maybe the problem is my version of gcc is too old?  I would expect an error message trying to compile stan in this case, not that it cannot find the right version of httpstan?

**Comment by riddell-stan** [comment]
It's too old for the PyPI wheel. This is a known issue. It's why we have the gcc version requirement.

Building httpstan from scratch is the right thing to do.

You should be able to build a version of httpstan with the correct version number. Please open a bug in httpstan if something odd is happening or if the instructions are not clear.

**Comment by astrojuanlu** [comment]
For future readers: httpstan apparently doesn't distribute sdists on PyPI. To fix the error that @spmacdonald originally reported, one has to upgrade pip first, so the `manylinux2014` wheel is properly downloaded.
