### ISSUE TITLE
UI: Updated sampling progress overwhelms Jupyter interface

### ISSUE THREAD

**Issue by amas0** [stan-dev/pystan#293]
#### Describe the bug
The improved UI messages (I believe implemented in 163af4fc9d19a7991f7bafc66fdb1a309d400975, I first noticed it when I went from 3.0 -> 3.1) have an odd interaction with the Jupyter interface. Effectively, multiple status lines are printed to the interface every second and model fits that only run for a few minutes will fill up the browser interface with thousands of 
`Sampling : X% (Y/Z)` lines. 

I glanced through the source and I think it's attempting to write a line to the browser every time the event loop polls for completion as in: 

https://github.com/stan-dev/pystan/blob/163af4fc9d19a7991f7bafc66fdb1a309d400975/stan/model.py#L211-L214

The `sampling_output.clear()` doesn't clear anything in Jupyter and you just end up with a ton of lines. Another effect is your browser essentially will max out a CPU core trying to write as lines to your screen as fast as possible.

I was going to look to see if I could find some workaround to ease the issue in Jupyter while not changing the behavior in terminals, but I wanted to throw this issue up first just to have a record of it. I know it's kind of clunky because this was all clearly written to function best from a terminal interface and Jupyter hijacking that process just causes some oddities, but it would be nice to smooth out the experience. 

If you have any ideas, I'd be happy to try to explore them. Otherwise, I might do some exploration and try to cook up a PR if I find something that seems to work.

#### Steps/Code to Reproduce
Sample from any model in a Jupyter interface.

**Comment by riddell-stan** [comment]
Are you using 3.1.1? I would have thought the fix was in there.

**Comment by riddell-stan** [comment]
re: CPU usage, we might consider adding a check which avoids writing if the iteration count has not changed.

Something like:

```
if current_iterations.get(operation["name"]) == iteration:
    continue
```

How about that?

Thanks for the detailed issue report.

**Comment by amas0** [comment]
> Are you using 3.1.1? I would have thought the fix was in there.

Confirmed using 3.1.1.


I'll play around with that suggestion and get back to this -- thanks!

**Comment by amas0** [comment]
@riddell-stan  Proposed PR #296, just takes your suggestion of avoiding printing when the number of iterations hasn't changed. Tested it out in Jupyter and my terminal -- terminal behaves as before and we get a more reasonable number of sampling outputs in Jupyter.
