### ISSUE TITLE
Using previously installed cmdstan

### ISSUE THREAD

**Issue by mkovalski** [stan-dev/pystan#296]
Is there an option to use an already installed cmdstan instead of needing to rebuild cmdstan inside of pystan? Using a linux machine without internet connection, and using the latest release (2.14.0) source files. I notice that the stan source files are just packaged within pystan and you aren't able to just reference an already installed version within another subdirectory.

**Comment by syclik** [comment]
Sorry -- I don't think the question makes sense.

PyStan does not use CmdStan and CmdStan isn't distributed with PyStan.
PyStan keeps the python dictionary that's data in memory.

Does that make sense? If you want to just use CmdStan from python, then
there's an unpublicized package that Alp put together that I can't think of
off the top of my head.

**Comment by mkovalski** [comment]
Sorry, the way my question was worded was a bit confusing. Let me try and rephrase this, and please let me know if I have anything mistaken.

Within the different versions of the stan interfaces (cmdstan, pystan, etc), there is a folder that contains the source code to stan. For my version of cmdstan, this is stan_2.14.0/ and for pystan, this is pystan/stan/. These directories contain the same stan source and by building both tools separately I end up with duplicate stan builds. I was wondering if there was a way, instead of needing to compile the same version of stan for both of these tools, to have pystan point to an already built stan.

**Comment by ariddell** [comment]
Copying the data is cheap. (Source code compresses particularly well.) Unless you have a really compelling reason for preserving space, I wouldn't worry about it. If you're worried about there being differences in the code (there should not be), you could verify that the files are the same.
