### ISSUE TITLE
stan compilation failing early with no gcc error message

### ISSUE THREAD

**Issue by gregorydavidmartinez** [stan-dev/pystan#298]
I have a rather complicated python code that produces a stan file "temp.stan".  This temp.stan compiles fine with cmdstan.  And in previous versions of pystan, it compiled fine (sorry, I can't recall specifically which versions it compiled with).  But, when running the current version of pystan, the compilation fails.  But, there is no associated gcc error message, just "CompileError: command 'gcc' failed with exit status 1"

Here is the temp.stan file:
[temp.stan.txt](https://github.com/stan-dev/pystan/files/748703/temp.stan.txt)

And here is the actual output:

In [1]: run efit.py                    
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_c770978ff7549bb81c98d223928af133 NOW.
\---------------------------------------------------------------------------
CompileError                              Traceback (most recent call last)
/home/gmartine/efit_stan/efit.py in <module>()
    722 
    723 if __name__ == "__main__":
--> 724    main(sys.argv[1:])

/home/gmartine/efit_stan/efit.py in main(argv)
    719 
    720 def main(argv):
--> 721     fit1 = stanfit("efit.yaml")
    722 
    723 if __name__ == "__main__":

/home/gmartine/efit_stan/efit.py in __init__(self, inifile)
    673         efit_dat = enterData(self.dir_name, self.star_names)
    674         #print efit_dat
--> 675         self.fit = pystan.stan(file='temp.stan', data=efit_dat, iter=points, chains=chains)
    676 
    677         f1 = open(self.dir_name + self.run_name + ".summary", "w")

/usr/lib64/python2.7/site-packages/pystan/api.pyc in stan(file, model_name, model_code, fit, data, pars, chains, iter, warmup, thin, init, seed, algorithm, control, sample_file, diagnostic_file, verbose, boost_lib, eigen_lib, n_jobs, **kwargs)
    377         m = StanModel(file=file, model_name=model_name, model_code=model_code,
    378                       boost_lib=boost_lib, eigen_lib=eigen_lib,
--> 379                       obfuscate_model_name=obfuscate_model_name, verbose=verbose)
    380     # check that arguments in kwargs are valid
    381     valid_args = {"chain_id", "init_r", "test_grad", "append_samples", "enable_random_init",

/usr/lib64/python2.7/site-packages/pystan/model.pyc in __init__(self, file, charset, model_name, model_code, stanc_ret, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args)
    307 
    308         try:
--> 309             build_extension.run()
    310         finally:
    311             if redirect_stderr:

/usr/lib64/python2.7/distutils/command/build_ext.pyc in run(self)
    338 
    339         # Now actually compile and link everything.
--> 340         self.build_extensions()
    341 
    342     def check_extensions_list(self, extensions):

/usr/lib64/python2.7/distutils/command/build_ext.pyc in build_extensions(self)
    447 
    448         for ext in self.extensions:
--> 449             self.build_extension(ext)
    450 
    451     def build_extension(self, ext):

/usr/lib64/python2.7/distutils/command/build_ext.pyc in build_extension(self, ext)
    497                                          debug=self.debug,
    498                                          extra_postargs=extra_args,
--> 499                                          depends=ext.depends)
    500 
    501         # XXX -- this is a Vile HACK!

/usr/lib64/python2.7/distutils/ccompiler.pyc in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    572             except KeyError:
    573                 continue
--> 574             self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    575 
    576         # Return *all* object filenames, not just the ones we just built.

/usr/lib64/python2.7/distutils/unixccompiler.pyc in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    132                        extra_postargs)
    133         except DistutilsExecError, msg:
--> 134             raise CompileError, msg
    135 
    136     def create_static_lib(self, objects, output_libname,

CompileError: command 'gcc' failed with exit status 1

**Comment by ahartikainen** [comment]
What are the following versions?

python
numpy
cython
pystan
gcc

**Comment by gregorydavidmartinez** [comment]
Thanks for the reply!  After many headpalms, I finally figured out the problem.  It had to do with my os (I upgraded to Fedora 24).  Apparently, I was missing the file "/usr/lib/rpm/redhat/redhat-hardened-cc1" which was included in the "redhat-rpm-config" rpm package.  After a quick install, it seems to be compiling fine.  Sorry for jumping the gun and thanks for the attention.
