### ISSUE TITLE
Add documentation on creating a development environment

### ISSUE THREAD

**Issue by amas0** [stan-dev/pystan#299]
#### Describe the problem with the documentation

While the basic usage documentation provides instructions for installing a release via `pip` and the contribution documentation gives general guidelines on etiquette and goals, there aren't any instructions for setting up a development environment to include installing from source in an editable fashion similar to `pip install -e .`.

#### Suggest a potential alternative/fix

Inspection shows the project uses `poetry` for build -- it would be helpful for those of us who aren't familiar with `poetry` to have some minimal instructions to get an environment set up in a way that we could iterate on the codebase.

**Comment by riddell-stan** [comment]
I have looked into this. (I used to use `pip install -e .` everywhere.)

This one doesn't have a particularly satisfying answer. There isn't an equivalent of `pip install -e`. See https://github.com/python-poetry/poetry/discussions/1135#discussioncomment-145756 for the official answer from the poetry folks.

If you feel like you've settled on a good solution, feel free to post it on the Stan forums.

Looking at my setup, it looks like I create a venv, activate it, and manually install dependencies with `pip`. I run tests in the pystan repo directory, so any changes I have made get picked up on.

**Comment by amas0** [comment]
Thanks for sharing that discussion, a helpful rabbit hole to go down. 

Reading more on poetry, it looks like running a standard `poetry install` from within the source directory creates a virtualenv for you, and within that venv the source code is editable. I just tested it out for myself and it seems to work. 

So `poetry install` + using the poetry-created-venv gives a functional development environment _for developing on `pystan`_. 

If I understand correctly, the thing that does _not_ work within poetry is the ability to install the whole package as editable _within another environment_. So, if you were trying to make changes to `pystan` locally and testing those changes out in another project, you'd have no equivalent `pip install -e`. At least until someone in the world of python packaging figures out how to have an equivalent solution that poetry can use.

As for instructions, I don't think it'd be any more complex than:

1. Install [Poetry](https://python-poetry.org/)
2. Clone the repo:
```
git clone https://github.com/stan-dev/pystan.git
```
3. Run the install
```
poetry install pystan/
```
4. Either configure your development environment to use the Poetry-created virtual environment or use commands such as `poetry run` or [others](https://python-poetry.org/docs/basic-usage/) to do development activities.

I use Pycharm for development and pointing that at the Poetry virtual environment had everything working nicely. 

I'd be happy to make a post on the Stan forums with some more detail to the above. I feel like the most useful place to include these steps would be in the "Contributing to PyStan" section of the documentation.

**Comment by ahartikainen** [comment]
There is a way to extract requirements from poetry and then doing `pip install -e .` but not sure how easy it is to do.

**Comment by riddell-stan** [comment]
I don't want to create a documentation section which we may have to change in 6 or 12 months (as tooling or convention changes).

I would prefer to link to well-written, generic instructions for how to develop a package when the package uses poetry. If such a thing exists now and is likely to be maintained, we could link to it.

**Comment by amas0** [comment]
I think the closest one could get to generic instructions would be to link
the Poetry basic usage <https://python-poetry.org/docs/basic-usage/> page.
Perhaps language like "PyStan is built using Poetry. To get started with
development, clone the repository and run `poetry install`. For details on
usage to include working with the virtual environment or running tools such
as pytest, refer to the Poetry documentation." would be sufficient?

That way it's light on details that are subject to change but points people
in the right direction where they can read more.

As to extracting reqs from poetry and running an editable install from
there -- while I have seen some people develop workarounds in that vein, it
ends up seeming pretty hacky (and definitely the kind of thing that would
change in the future with changes in tooling).

The default Poetry install gives a development setup that seemingly covers
the majority of use cases and is unlikely to change in the future.

**Comment by riddell-stan** [comment]
> To get started with development, clone the repository and run `poetry install`. For details on
usage to include working with the virtual environment or running tools such
as pytest, refer to the Poetry documentation." would be sufficient?

Until the dust settles and there's a standard way of doing things, I hesitate even saying this. Of course, I also hesitate because I myself don't use this approach. (@ahartikainen do you use `poetry install` for pystan development?)

How about this. Someone (perhaps you?) posts on the discussion forum under a title such as "Tips for hacking on PyStan" and explains their approach. Other people can add a description of their approach. I promise to participate. I think I can reverse engineer what I did to arrive at my current setup.

**Comment by ahartikainen** [comment]
I have used poetry install before. It is probably easiest way to use dev env.

**Comment by amas0** [comment]
I went ahead and threw up [a post on the Stan forums](https://discourse.mc-stan.org/t/tips-for-setting-up-a-pystan-development-environment/22555) detailing the instructions I used to get a development environment up and running with Poetry. Hopefully some find it helpful.

If there's no desire to add anything to the docs directly, then I think we're probably good to close this issue. Thanks.

**Comment by riddell-stan** [comment]
I think it's highly likely this issue will be solved by https://www.python.org/dev/peps/pep-0660/ . Closing this for now.
