### ISSUE TITLE
PyStan should use callbacks to python instead of writing directly to stdout

### ISSUE THREAD

**Issue by shoyer** [stan-dev/pystan#30]
Currently, sampling progress is written directly to stdout via `stan_fit.hpp`. Ideally, it seems that updating sampling progress should be a call back to python, so progress could be passed to a python logger or [progress bar](https://github.com/fnoble/python-progressbar) object.

My use case is running pystan non-interactively in a cluster computing environment where it would be useful to be able to use a logger object so I can log progress to a file.

Another use case would be displaying progress in an IPython notebook, which currently doesn't happen. Writing to stdout from the C++ side ends up printing in the terminal window which I used to launch IPython.

To give a bit more context, I've written a script which writes output via stdout (so I can use [Hadoop streaming](http://hadoop.apache.org/docs/r1.1.2/streaming.html)), and it is a little annoying that the only way to turn off the status messages writing to stdout is to set `refresh=0`, which also disables pystan's logging. On the whole, it seems like slightly poor manners for a library to write directly to stdout.

A side benefit might be allowing for a `KeyboardInterrupt` to stop progress even in the midst of sampling from a chain.

I recognize that this may be a little tricky to implement (involving hacking on the C++/Cython side) but I think it would be worth doing eventually, so I thought I would mention it.

**Comment by ariddell** [comment]
This was the first issue but I think it makes sense to track this at #98.
