### ISSUE TITLE
TypeError in extract()

### ISSUE THREAD

**Issue by sfeeney** [stan-dev/pystan#301]
#### Summary:
Since upgrading to the latest version of PyStan (pystan.__version__ = '2.14.0.0') I get a TypeError when extracting fits when permuted = True. This worked fine in version 2.12.0.0.

#### Description:
The error occurs in the line 

extracted[par] = extracted[par].reshape(newdim, order='F')

in extract() because newdim is a float. This seems to stem from self.sim['n_save'] being assigned as a float in model.py, though I've not tracked down the source further than that. It may be something to do with the use of the // operator but I'm not sure.

#### Reproducible Steps:
I have a Pickled Stan model that I use to fit some data using the sampling() method, returning an object named fit. If I call fit.extract(permuted=True) I can reproduce this error. Please let me know if you need the full code.

#### Current Output:
The error message I get is:

Traceback (most recent call last):
  File "stan_cpl.py", line 495, in <module>
    samples = fit.extract()
  File "stanfit4anon_model_86f0c8d2f63dcf12b6bc584c29bf7ac4_1190911492343917902.pyx", line 574, in stanfit4anon_model_86f0c8d2f63dcf12b6bc584c29bf7ac4_1190911492343917902.StanFit4Model.extract (/var/folders/4q/2gmnqtb5211g95b5p6rlh32800011w/T/tmpzoG1H_/stanfit4anon_model_86f0c8d2f63dcf12b6bc584c29bf7ac4_1190911492343917902.cpp:11624)
TypeError: 'float' object cannot be interpreted as an index

#### Expected Output:
This should return an OrderedDict object containing the requested samples.

#### PyStan Version:
2.14.0.0

#### Python Version:
2.7.12

#### Operating System:
OS X

**Comment by ariddell** [comment]
Are you trying to use a pickled PyStan 2.12 model from PyStan 2.14?

**Comment by sfeeney** [comment]
Hi! Nope, I've recompiled and Pickled the model since updating.

**Comment by ariddell** [comment]
OK. I'll try to reproduce this.

**Comment by ahartikainen** [comment]
Can you print `fit.sim` and see if `'warmup'`, `'iter'` or `'thin'` is float. 
Do you use default or custom values for those parameters?

In `model.py` those values are added to `sim` dict and are not confirmed to have the correct dtypes.

Integer division in python3 (python2+division) returns int or float

    int//int=int
    float//float=float
    int//float=float
    float//int=float

**Comment by sfeeney** [comment]
Sure thing!
`print 'github check', fit.sim['warmup'], fit.sim['iter'], fit.sim['thin']`
yields
`github check 5000 10000.0 1`
so it looks like `'iter'` is the culprit. Oh, argh, I've just realised I've called `sampling()` with `iter = 1e4`, hence it's a float. Changing this to 10000 fixes the call to `extract(permuted = True)`. Sorry about that! Shall I close the issue? Or is it worth adding a check / conversion in the Stan code? This wasn't an issue with the previous version, and `sampling()` seems to cope.

**Comment by ahartikainen** [comment]
Reshape with float dimensions is a numpy property, not a problem from pystan.

https://github.com/numpy/numpy/blob/master/doc/release/1.12.0-notes.rst

From notes:

Compatibility notes

DeprecationWarning to error

Indexing with floats raises IndexError, e.g., a[0, 0.0].
Indexing with non-integer array_like raises IndexError, e.g., a['1', '2']
Indexing with multiple ellipsis raises IndexError, e.g., a[..., ...].
Non-integers used as index values raise TypeError, e.g., in reshape, take, and specifying reduce axis.

**Comment by ariddell** [comment]
I think the NumPy/Python convention is fairly clear here. You have to cast to int when an int is called for.

I myself use ``1e6`` in code sometimes, but I do cast it to int. I expect this to fail (as it does):

```
import numpy as np
np.random.normal(size=1e6)  # should be: np.random.normal(size=int(1e6))
```

**Comment by sfeeney** [comment]
Understood! I agree that the issue is me using a float where an int is called for. Is it worth explicitly checking for the type of this input within PyStan? Purely because it seems different parts of the code respond differently, and that way the user would be left in no doubt of their mistake?

**Comment by ahartikainen** [comment]
In my opinion it should raise an error in pystan. Before numpy 1.12 it was ok, but after 1.12 release it should be checked.

I see that there are potential problems with automatic conversion from float to int so raising error is more suitable. If no error is raised then atleast warning should be shown.

**Comment by ariddell** [comment]
I agree. It should raise a ValueError.

**Comment by sfeeney** [comment]
Okay cool! Sorry this turned out to be more a case of stopping the user from being daft rather than a real bug! Though I suppose that's preferable...

**Comment by ariddell** [comment]
Closing this in favor of #302 to make clear what the next step is.
