### ISSUE TITLE
Raise ValueError if 'warmup', 'iter' or 'thin' is float

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#302]
See #301.

**Comment by ahartikainen** [comment]
Test against `numbers.Integral`? Should work for `int` and `np.int64`

    from numbers import Integral
    ...
    if not isinstance(iter, Integral):
        raise ValueError("...")

**Comment by ariddell** [comment]
Let's check to see what numpy does. If we can use the same check and/or message I think that would help. I think it's good if people can associate certain words with "oh yeah, I need to cast this float to int".

**Comment by ahartikainen** [comment]
In numpy the checks are done in c (?).

https://github.com/numpy/numpy/commit/c87c7a612ee7f90281797e447255c402b099c73a
https://github.com/numpy/numpy/pull/2891
https://github.com/numpy/numpy/pull/3243

**Comment by ariddell** [comment]
Those are some serious tests (e.g. checking that warnings are raised)!

Let's copy as much as we can of the relevant message? How about..

"only integer values allowed as {warmup, iter..}"

p.s. PyStan 3 will have type checking... That's the plan.
