### ISSUE TITLE
_split_data doesn't handle unsigned integers

### ISSUE THREAD

**Issue by tyarkoni** [stan-dev/pystan#303]
#### Summary:
In [`misc._split_data`](https://github.com/stan-dev/pystan/blob/develop/pystan/misc.py#L361), all input data are checked to make sure they're of `int` or `float` type and encoded appropriately. But in numpy's dtype hierarchy, `uint` and `int` are distinct, so unsigned integers are ignored, and PyStan fails when one or more inputs has a dtype like `uint8`. The issue arises here:

```python
if np.issubdtype(np.asarray(v).dtype, int):
    data_i.update({k.encode('utf-8'): np.asarray(v, dtype=int)})
```

Is there any reason not to check against both `int` and `uint`, since the `dtype` of the input data is immediately set to `int` anyway?

This isn't a big deal in my particular use case, since it's trivial to convert the dtype of the array before passing it to PyStan, but since other users may run into this at some point, it might be worth fixing (assuming there's no potential problem I'm missing). I'm happy to open a PR if the suggested solution makes sense.

**Comment by ahartikainen** [comment]
Does it handle np.int64?

Does numbers.Integral work for uint. Or np.integer / np.integral?

**Comment by ariddell** [comment]
A PR would be great. Wonderful catch @tyarkoni .

**Comment by ariddell** [comment]
This was a bit more complicated than I thought.

np.integer seems to work in practice, but the docs suggest that it shouldn't. According to the drawing in the docs for numpy.core.numerictypes np.uint is not a subdtype of np.integer -- but it seems to work just the same.

I'm going to switch it to np.integer for now and hope this is fixed.
