### ISSUE TITLE
Python 3.6 wheels for Windows

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#307]
Everyone has Python 3.6 compatible wheels except Windows. This should be fixed in the next release.

**Comment by aamirc** [comment]
When will this next release be available by?

**Comment by agiani99** [comment]
Hi all,
I managed to pip install pystan on AMD64 Windows 10 into anaconda 3 with python3.6
The trick is really to allow W10 to see paths longer than 260chars.
Registry entry is here
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
and value to set to 1 is LongPathsEnabled.
HTH
best
Andrea

**Comment by ariddell** [comment]
Is this something that everyone is encountering? I imagine PyStan isn't
alone in having long filenames/paths.

Do specific tips need to be added to the installation instructions?

**Comment by ahartikainen** [comment]
There are some really long filenames in docs. If one installs vanilla python they normally use `C:/program_files/python3.6/site-packages` etc. Anaconda/miniconda are usually installed on user files `C:/Users/user/miniconda/envs/my_env/lib/python3.6/site-packages`.

I have noticed this problem a few times.

**Comment by aamirc** [comment]
This didn't solve the problem for me - it still throws out a wheels error.
