### ISSUE TITLE
pip install fails with FileNotFoundError: [Errno 2] 

### ISSUE THREAD

**Issue by fcitterio** [stan-dev/pystan#311]
**Summary**
I got the following error when executing `pip install pystan`:

> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\citterio\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\pystan\\stan\\lib\\stan_math_2.14.0\\doc\\api\\html\\d0\\d88\\struct_eigen_1_1internal_1_1general__matrix__vector__product_3_01_index_00_01stan_1_1math_1_1var15f7d538e8be7d782eccb613a7b1e9bd.html'

**Description**
The prerequisites of numpy and cython are statisfied and I have installed Visual C++ Build Tools 2015.
The problem is that a file is missing and I can't find it in the right directory:
Actually the list of files in '`C:\\Users\\citterio\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\pystan\\stan\\lib\\stan_math_2.14.0\\doc\\api\\html\\d0\\d88`  is:
![cattura](https://cloud.githubusercontent.com/assets/26324543/23792908/2f37d4ca-0589-11e7-9246-7d7e181e6c37.PNG)

#### Current Output:
The complete command output is 

> Collecting pystan
>   Using cached pystan-2.14.0.0-cp35-cp35m-win_amd64.whl
> Requirement already satisfied: Cython!=0.25.1,>=0.22 in c:\users\citterio\appdata\local\programs\python\python35\lib\site-packages (from pystan)
> Requirement already satisfied: numpy>=1.7 in c:\users\citterio\appdata\local\programs\python\python35\lib\site-packages (from pystan)
> Installing collected packages: pystan
> 
> Exception:
> Traceback (most recent call last):
>   File "C:\Users\citterio\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "C:\Users\citterio\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\commands\install.py", line 342, in run
>     prefix=options.prefix_path,
>   File "C:\Users\citterio\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_set.py", line 784, in install
>     **kwargs
>   File "C:\Users\citterio\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 851, in install
>     self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
>   File "C:\Users\citterio\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
>     isolated=self.isolated,
>   File "C:\Users\citterio\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
>     clobber(source, lib_dir, True)
>   File "C:\Users\citterio\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\wheel.py", line 323, in clobber
>     shutil.copyfile(srcfile, destfile)
>   File "C:\Users\citterio\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 115, in copyfile
>     with open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\citterio\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\pystan\\stan\\lib\\stan_math_2.14.0\\doc\\api\\html\\d0\\d88\\struct_eigen_1_1internal_1_1general__matrix__vector__product_3_01_index_00_01stan_1_1math_1_1var15f7d538e8be7d782eccb613a7b1e9bd.html'

#### PyStan Version:
2.14.0
#### Python Version:
3.5
#### Operating System:
Windows 10

**Comment by ariddell** [comment]
I've seen some mentions of a limit on the length of file names on Windows. Perhaps this is related.

In any event, PyStan should be removing these docs (stan_math docs) from the wheel before it is uploaded to PyPI.

**Comment by ariddell** [comment]
Almost positive this is the file length problem.

**Comment by pradyunsg** [comment]
This is the first result on Google when searching this error. I'm linking this to pypa/pip#3055 since that is the upstream issue that has workarounds listed.

**Comment by gilcot** [comment]
Not only Windows issue as I'm running a Debian box for version 0.5.1
``` 
Complete output from command python setup.py egg_info:
Tracback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-build-jDDZct/zabbix-api/setup.py", line 30, in <module>
    long_description=read_descr('README.md'),
  File "/tmp/pip-build-jDDZct/zabbix-api/setup.py", line 17, in read_descr
    long_description = open(filepath).read()
  IOError: [Errno 2] No such file or directory: '/tmp/pip-build-jDDZct/zabbix-api/README.md'
```
Very strange

**Comment by ariddell** [comment]
Can you install from the wheel?

**Comment by gilcot** [comment]
Hello @ariddell 

For what I can read, I need to do a `pip install wheel` first then download the .whl file ...but where to found this later?

Thanks.

**Comment by ahartikainen** [comment]
I'm sorry, but what is zabbix-api and what does it have to do with PyStan? (I have not heard of it before)

Did you run this

    pip install pystan

**Comment by gilcot** [comment]
ooops sorry @ahartikainen 

I wrote in the wrong browser window (this one was the first result when googling on the error, but not for the guilty module)
