### ISSUE TITLE
Getting `ValueError: not enough values to unpack` when no observations are supplied

### ISSUE THREAD

**Issue by ForceBru** [stan-dev/pystan#312]
#### Describe the bug

An internal error occurs when I try to `stan.build`.

#### Describe your system

- macOS Catalina
- x86_64
- Apple clang version 12.0.0 (clang-1200.0.32.29)
- ```
   Python 3.9.5 (default, May 18 2021, 12:31:01) 
   [Clang 10.0.0 ] :: Anaconda, Inc. on darwin
   ```

#### Steps/Code to Reproduce

Code:

```python
import stan

print("PyStan version:", stan.__version__)

stan_code = """
data {
    int<lower=2> nlags;
}
model {
    vector[nlags] eps;
    
    for (i in 1:nlags)
        eps[i] ~ normal(0, 1);
}

"""

stan.build(stan_code, data = {'nlags': 5})
```

This model may make zero sense, but it compiles fine. Error:

```
$ python pystan_error.py
PyStan version: 3.2.0
Building: 18.8s, done.
Messages from stanc:
Warning in '/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/httpstan_6atmzqvs/model_eakxmxp2.stan', line 9, column 8: The variable eps may not have been assigned a value before its use.
Traceback (most recent call last):
  File "/Users/forcebru/test/pystan_error.py", line 18, in <module>
    stan.build(stan_code, data = {'nlags': 5})
  File "/Users/forcebru/opt/miniconda3/lib/python3.9/site-packages/stan/model.py", line 512, in build
    return asyncio.run(go())
  File "/Users/forcebru/opt/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/forcebru/opt/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/forcebru/opt/miniconda3/lib/python3.9/site-packages/stan/model.py", line 507, in go
    param_names, dims = zip(*((param["name"], param["dims"]) for param in params_list))
ValueError: not enough values to unpack (expected 2, got 0)
```

- It says: `line 9, column 8: The variable eps may not have been assigned a value before its use`, but I'm not using `eps` anywhere - I'm just trying to set priors. `nlags >= 2`, because of `int<lower=2> nlags;`, so `1:nlags` in the loop is definitely not empty, thus `eps` should be initialized. I guess this is just something I don't understand and it's not the point of the issue. EDIT: looks like I didn't understand what sampling means: [the documentation](https://mc-stan.org/docs/2_27/reference-manual/print-statements-section.html#debug-by-print) says that `eps[i]` must be defined before usage in sampling...
- The `ValueError` seems to be an internal error that doesn't tell me what's wrong with my code. It would've been nice if the error message was more user-friendly

**Comment by riddell-stan** [comment]
Thanks for the clear and concise report. Looks like this case (no params) is not handled correctly.
