### ISSUE TITLE
Variational Bayes output

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/pystan#313]
#### Summary:
It'd be nice if the fit returned by the variational Bayes fit (StanModel.vb) was compatible with the fit object returned by the default HMC sampling (StanModel.sampling).

#### Description
By that I mean, if I printed it, I'd get the nice little summary statistics that I do with the regular fit objects returned by the HMC sampling. Also it'd be nice if I could extract posterior samples using an extract function. This way I could easily swap in the variational methods and compare how they're working with my models.

At the very least, it'd be nice to have the posterior samples automatically parsed from the output file produced by the variational Bayes fit. Managing temporary text files and custom CSV formats isn't terribly fun. CSV isn't too bad for single parameters, but vectors of parameters have to kinda be manually reshaped to make it comparable to the regular fit objects. I coded up a really questionable solution to that to show you what I mean:
https://github.com/bbbales2/pystan/commit/573bba07f81008cbca2b4c55f9be9b8f374611d2

This is with respect to PyStan 2.14.

Thanks a lot!

**Comment by bbbales2** [comment]
I wouldn't mind having a proper go at this, but I've got a couple questions first.

It looks like what StanModel.sampling does is run its stuff and then just fill up a StanFit4Model object (https://github.com/stan-dev/pystan/blob/e9fc7336c338417232497217f4028a0f2654b1e6/pystan/model.py#L729)

I looked at the code (https://github.com/stan-dev/pystan/blob/77d183ce2d33ef72a4435535974d43b5d4c3783d/pystan/stanfit4model.pyx) and it looks like the fit objects do a lot, but as far as I can tell StanModel.sampling and StanModel.vb both instantiate new StanFit4Model objects, but only StanModel.sampling fills up the data structures and returns the fit object (.vb returns a dict instead). Is there any complexity to the StanFit4Model objects that would limit the usefulness of this implementation?

I'm not super familiar with variational inference, other than we're approximating a posterior as a mixture of Gaussians using a KL-like divergence.

This means that (to be compatible with PyStan.sampling) the output from fit.extract() would be the parameters of the model, not the actual parameters being optimized in the KL divergence.

So should StanFit4Model.log_prob and StanFit4Model.grad_log_prob still return the same things that a StanModel.sampling fit would return? Or something different that corresponds to the variational inference?

I think I could weasel a way to get .extract and .summary to work (which is what I'd like), but I'm wondering if maybe I'm glossing over some important distinction in the fit types.

**Comment by bob-carpenter** [comment]
I don't know if the core Python's code been updated for
the refactor, but all this is going to change in 2.15, so it
would be prudent to wait until that's done unless you need it before
then.  My understanding is that Allen's busy until June and won't
be able to get to the refactored PyStan code before then (I
suspect PyStan's going to miss the 2.15 release date by a couple
months).

- Bob

**Comment by bbbales2** [comment]
Ah, sure thing Bob. I can just carry around my little parse script wherever I need it.

Thanks guys!

**Comment by ariddell** [comment]
Bob, I think the refactor #282 got merged. What's changing in 2.15?

**Comment by bob-carpenter** [comment]
The refactor was merged into stan-dev/stan, but I hadn't realized
that PyStan had been updated.  I must have misunderstood what
you wouldn't have time for until June.  

- Bob
