### ISSUE TITLE
cmdstand and pystan deliver different results on diagnose test=gradient

### ISSUE THREAD

**Issue by cs224** [stan-dev/pystan#316]
#### Summary:

I am in the process of learning Stan and use cmdstan and pystan in parallel to see their commonalities and differences. In one of my toy models the diagnostics from cmdstand and pystan differ. I guess this should not be the case.

#### Reproducible Steps:

The following python program can create the pystan_mixture_experiments_shifted_gamma.stan and data.R files to use for cmdstan by executing `write_stan_model('pystan_mixture_experiments_shifted_gamma')`:

```python
import os

import numpy as np, pandas as pd, matplotlib.pyplot as plt, seaborn as sns
import scipy.stats as stats

import pystan

SEED = 5132290 # from random.org
np.random.seed(SEED)

D = 200 # granularity of plots along the x-axis
PLOT = False
# PLOT = True

n1 = 500
n2 = 200
n = n1+n2

shift1 = 20
shift2 = 40

k = 2.
theta = 4.
np.random.gamma(k, theta)
data1 = np.random.gamma(k, theta, n1) + shift1
stats.rv_continuous.fit(stats.gamma, data1, floc=shift1)
data2 = np.random.gamma(k, theta,n2) + shift2

data = np.concatenate([data1 , data2])

x_plot = np.linspace(data.min(), data.max(), D)
y_gamma_sum = (n1/n)*stats.gamma.pdf(x_plot, k, loc=shift1, scale=theta) + (n2/n)*stats.gamma.pdf(x_plot, k, loc=shift2, scale=theta)

if PLOT:
    fig, ax = plt.subplots(figsize=(8, 6))
    n_, bins, patches = ax.hist(data, histtype='stepfilled', bins=100, alpha=0.85, label="k: {} and \\theta: {}".format(k, theta), color="#A60628", normed=True)#, weights=weights, normed=True
    ax.plot(x_plot, y_gamma_sum, c='gray', alpha=0.9, label='True y_norm_sum');
    ax.legend(loc="upper left")
    ax.set_title("sum of two gaussians")
    ax.set_xlim(0,100)
    ax.set_ylim(0.0, 0.1)
    ax.set_xlabel("x")

model_string = """
data {
    int<lower = 0> N; // number of observations
    real y[N]; // y is a length N vector of integers
}
parameters {
    real<lower=0, upper=1> p;
    real<lower=0, upper=10> a; // a ~ uniform(0,10)
    real<lower=0, upper=10> b; // b  ~ uniform(0,10)
    ordered[2] shifts;
}
model {
    vector[2] contributions;

    p ~ beta(2,2);
    shifts ~ normal(30,50);

    for(i in 1:N) {
        contributions[1] = log(p)   + gamma_lpdf(y[i] - shifts[1] | a, b);
        contributions[2] = log(1-p) + gamma_lpdf(y[i] - shifts[2] | a, b);
        target += log_sum_exp(contributions);
    }
}
"""
sm = pystan.StanModel(model_code=model_string)

def initfun():
    return dict(p=0.7, a=2.0, b=0.2, shifts=np.array([20.0, 40.0]))

data_list = {'y': data, 'N': n}

def write_stan_model(model_name):
    dir_path = os.getcwd() + '/' + model_name
    if not os.path.exists(dir_path):
        os.makedirs(dir_path)

    model_file = dir_path + '/' + model_name + '.stan'
    with open(model_file, "w") as model_file_handle:
        print(model_string, file=model_file_handle)

    data_file = dir_path + '/data.R'
    pystan.stan_rdump(data_list, data_file)

# write_stan_model('pystan_mixture_experiments_shifted_gamma')
# create a link in cmdstan-2.14.0/examples to the model name directory and execute make as shown in the next line
# user@pc:~/.../cmdstan-2.14.0$ make examples/pystan_mixture_experiments_shifted_gamma/pystan_mixture_experiments_shifted_gamma
# user@pc:~/.../cmdstan-2.14.0/examples/pystan_mixture_experiments_shifted_gamma$ ./pystan_mixture_experiments_shifted_gamma diagnose test=gradient data file=data.R

fit = sm.sampling(data=data_list, chains=1, test_grad=True) # , init=2, seed=3986075333
```

The cmdstand output is:
```
method = diagnose
  diagnose
    test = gradient (Default)
      gradient
        epsilon = 9.9999999999999995e-07 (Default)
        error = 9.9999999999999995e-07 (Default)
id = 0 (Default)
data
  file = data.R
init = 2 (Default)
random
  seed = 3986075333
output
  file = output.csv (Default)
  diagnostic_file =  (Default)
  refresh = 100 (Default)


TEST GRADIENT MODE

 Log probability=-38746.7

 param idx           value           model     finite diff           error
         0        0.443837         -326.74         -326.74    -3.01101e-05
         1       -0.612429         4802.65         4802.65     8.31293e-06
         2        -1.38595        -34269.9        -34269.9    -2.07362e-05
         3        0.236216         1340.25         1340.25     1.97134e-05
         4        0.153828         1340.26         1340.26    -2.48254e-05
```
The pystan output is:
```
TEST GRADIENT MODE
 Log probability=-102543
 param idx           value           model     finite diff           error
         0        -1.62627        -100.089            -nan            -nan
         1       -0.748789         6125.49            -nan            -nan
         2       -0.157727        -58474.6            -nan            -nan
         3        -1.23028         3175.29            -nan            -nan
         4       -0.681622         1575.82            -nan            -nan
```

#### Expected Output:

From page 69 of the stan-reference-2.14.0.pdf in the section called "Diagnosing Problems with Derivatives" I understand that `nan` values are problem indicators.

As you can see the finite diff and error columns are -nan for the pystan run, but deliver values for the cmdstan run.

#### PyStan Version

pystan: '2.14.0.0'
cmdstan: cmdstan-2.14.0

#### Python Version:

Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 

#### Operating System:

Linux XXX 4.8.0-41-generic #44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ariddell** [comment]
Thanks for the report! Looks like a problem.

**Comment by syclik** [comment]
Allen, mind checking to see if it's fixed on develop or on the refactor branch if it hasn't been merged?

**Comment by ahartikainen** [comment]
Seeds for CmdStan and PyStan are different.

In PyStan, max seed can be 2147483647 (= MAX_UINT). This is checked in `pystan/misc.py` in function `def _check_seed`. Value over this gives warning and selects a random number between 0 and MAX_UINT. (see function end of the post).

    /Users/ahartikainen/miniconda2/envs/py35/lib/python3.5/site-packages/pystan/misc.py:669: UserWarning: `seed` is too large; max is 2147483647
      warnings.warn("`seed` is too large; max is {}".format(MAX_UINT))

`Log probability=-102543` is quite low. Maybe there are somewhere under/overflowing. But on mac (with clang) `Log probability` was on some test cases even lower without any nans.

I could not duplicate `nan` problem on mac. But calling `fit = sm.sampling(data=data_list, chains=1, test_grad=True)` without `init=initfun` raises error after the gradient is calculated (see end of the post). 

with `seed=11`

    fit = sm.sampling(data=data_list, chains=1, init=2, test_grad=True, seed=11)

    TEST GRADIENT MODE

     Log probability=-49028.9

     param idx           value           model     finite diff           error
             0        0.843605        -48.7725        -48.7725     6.80205e-07
             1        -1.33932         4381.85         4381.85    -2.58088e-05
             2        -1.25325        -39918.8        -39918.8    -2.76518e-06
             3       -0.405121         1530.68         1530.68    -9.10331e-07
             4         -1.9586         80.7359         80.7359     1.53294e-05

and with `seed=13`

    fit = sm.sampling(data=data_list, chains=1, init=2, test_grad=True, seed=13)

    TEST GRADIENT MODE

     Log probability=-37886

     param idx           value           model     finite diff           error
             0        -1.18483        -142.088        -142.088    -2.99887e-05
             1        -1.58283         3743.88         3743.88     1.96017e-07
             2        -1.48111        -31806.1        -31806.1    -4.10133e-05
             3          1.3394         1279.13         1279.13    -1.13331e-05
             4        0.230747         1564.25         1564.25      1.5787e-05


Same with `init=initfun`

`seed=11`

    fit = sm.sampling(data=data_list, chains=1, init=initfun, test_grad=True, seed=11)

    TEST GRADIENT MODE

     Log probability=-2462.93

     param idx           value           model     finite diff           error
             0        0.847298         31.1045         31.1045     8.20793e-07
             1        -1.38629        -220.747        -220.747    -1.57516e-07
             2        -3.89182         207.221         207.221     5.88676e-07
             3              20        -43.9063        -43.9063     3.00129e-08
             4         2.99573        -112.535        -112.535      4.7318e-07

`seed=13`

    fit = sm.sampling(data=data_list, chains=1, init=initfun, test_grad=True, seed=13)
    
    TEST GRADIENT MODE

     Log probability=-2462.93

     param idx           value           model     finite diff           error
             0        0.847298         31.1045         31.1045     8.20793e-07
             1        -1.38629        -220.747        -220.747    -1.57516e-07
             2        -3.89182         207.221         207.221     5.88676e-07
             3              20        -43.9063        -43.9063     3.00129e-08
             4         2.99573        -112.535        -112.535      4.7318e-07


Runtime error:

    RuntimeError                              Traceback (most recent call last)
    <ipython-input-86-8f6235dfb2ef> in <module>()
    ----> 1 fit = sm.sampling(data=data_list, chains=1, init=2, test_grad=True)#, seed='3986075333') # , init=2, seed=3986075333

    /Users/ahartikainen/miniconda2/envs/py35/lib/python3.5/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)
        717         call_sampler_args = izip(itertools.repeat(data), args_list, itertools.repeat(pars))
        718         call_sampler_star = self.module._call_sampler_star
    --> 719         ret_and_samples = _map_parallel(call_sampler_star, call_sampler_args, n_jobs)
        720         samples = [smpl for _, smpl in ret_and_samples]
        721 

    /Users/ahartikainen/miniconda2/envs/py35/lib/python3.5/site-packages/pystan/model.py in _map_parallel(function, args, n_jobs)
         80             map_result = pool.map(function, args)
         81     else:
    ---> 82         map_result = list(map(function, args))
         83     return map_result
         84 

    stanfit4anon_model_59be8dfba346d63e83aa81bdc1e97aff_189740154871589178.pyx in stanfit4anon_model_59be8dfba346d63e83aa81bdc1e97aff_189740154871589178._call_sampler_star (/var/folders/bw/cqyhp7rs5l1_96nr8lsqyk400000gn/T/tmpzhy4x0gj/stanfit4anon_model_59be8dfba346d63e83aa81bdc1e97aff_189740154871589178.cpp:8321)()

    stanfit4anon_model_59be8dfba346d63e83aa81bdc1e97aff_189740154871589178.pyx in stanfit4anon_model_59be8dfba346d63e83aa81bdc1e97aff_189740154871589178._call_sampler (/var/folders/bw/cqyhp7rs5l1_96nr8lsqyk400000gn/T/tmpzhy4x0gj/stanfit4anon_model_59be8dfba346d63e83aa81bdc1e97aff_189740154871589178.cpp:8973)()

    RuntimeError: Something went wrong after call_sampler.

`_check_seed` function

    from pystan.constants import (MAX_UINT, sampling_algo_t, optim_algo_t,
                                  variational_algo_t, sampling_metric_t, stan_args_method_t)
    def _check_seed(seed):
        """If possible, convert `seed` into a valid form for Stan (an integer
        between 0 and MAX_UINT, inclusive). If not possible, use a random seed
        instead and raise a warning if `seed` was not provided as `None`.
        """
        if isinstance(seed, (Number, string_types)):
            try:
                seed = int(seed)
            except ValueError:
                warnings.warn("`seed` must be castable to an integer")
                seed = None
            else:
                if seed < 0:
                    warnings.warn("`seed` may not be negative")
                    seed = None
                elif seed > MAX_UINT:
                    warnings.warn("`seed` is too large; max is {}".format(MAX_UINT))
                    seed = None
        elif isinstance(seed, np.random.RandomState):
            seed = seed.randint(0, MAX_UINT)
        elif seed is not None:
            warnings.warn('`seed` has unexpected type')
            seed = None

        if seed is None:
            seed = random.randint(0, MAX_UINT)

        return seed

**Comment by ariddell** [comment]
Seems like PyStan should abort rather than warning, right?

**Comment by ahartikainen** [comment]
In rstan

     ## only one seed is needed by virtue of the RNG 
  seed <- if (missing(seed)) sample.int(.Machine$integer.max, 1) else check_seed(seed)

**Comment by ariddell** [comment]
It is in RStan:
```
check_seed <- function(seed, warn = 0) {
  if (is.character(seed) && grepl("[^0-9]", seed)) {
    if (warn == 0) stop("seed needs to be string of digits")
    else message("seed needs to be string of digits")
    return(NULL)
  } 
  if (is.numeric(seed)) seed <- as.integer(seed)
  if (is.na(seed)) seed <- sample.int(.Machine$integer.max, 1)
  seed 
}
```
The ``as.integer(seed)`` will return NA with a very large number.

In any event, PyStan should raise a ValueError. I wish I could recall why it needs to be such a small integer or if we don't need to worry about it after Python 2 support is dropped (someday).
