### ISSUE TITLE
Fitting model crashes Jupyter notebook

### ISSUE THREAD

**Issue by poliquin** [stan-dev/pystan#318]
#### Summary:
Estimating a model inside a [Jupyter](http://jupyter.org) notebook does not work. It causes the kernel to die.

#### Description:
A simple model causes the kernel to crash and restart when running inside a notebook. There are no helpful error messages. See the image below.

The same model runs fine with Python on the command line.

#### Reproducible Steps:
Here is the full code...

```python
import pystan
import numpy as np

test = """
    data {
        int<lower=0> N;
        vector[N] y;
    }
    parameters {
        real mu;
        real<lower=0> sigma;
    }
    model {
        y ~ normal(mu, sigma);
    }
"""

st = pystan.StanModel(model_code=test, model_name='test')

N = 1000
fit = st.sampling(  # this line causes the problem!
    data={'N': N, 'y': np.random.normal(size=N)}, n_jobs=1
)

print(fit)
```

#### Current Output:

![kernel_crash](https://cloud.githubusercontent.com/assets/360123/24685261/6926b8e0-197a-11e7-8929-fdc89a91e32b.png)

#### Expected Output:
I expect roughly the following output in the notebook, which is what I get when running the same code from the command line:

```
Inference for Stan model: test_6c3f57429bde26462df851f85b22bb9f.
4 chains, each with iter=2000; warmup=1000; thin=1;
post-warmup draws per chain=1000, total post-warmup draws=4000.

        mean se_mean     sd   2.5%    25%    50%    75%  97.5%  n_eff   Rhat
mu     -0.05  5.3e-4   0.03  -0.11  -0.07  -0.05  -0.03   0.01   3440    1.0
sigma   0.99  4.2e-4   0.02   0.95   0.97   0.99    1.0   1.03   2787    1.0
lp__  -488.2    0.02   0.96 -490.8 -488.6 -488.0 -487.5 -487.2   1510    1.0
```

#### PyStan Version:
2.14.0.0

#### Python Version:
3.5.3 (Anaconda)

Cython: 0.25.2
Numpy: 1.12.1

#### Operating System:
macOS Sierra 10.12.4

**Comment by ariddell** [comment]
Interesting. Do you have any other versions of Python installed -- or is jupyter notebook being launched with the same Python which you used to verify things were working in the terminal?

Is there any useful output in the terminal from which you launched the jupyter notebook?

**Comment by poliquin** [comment]
It turns out Jupyter using a different Python and `pystan` was the problem, but it's a little subtle. It seems `pystan` does not work when installed in the root Anaconda environment.  

I had initially installed it in root, then tried creating a new environment. My Jupyter notebooks were still using the broken installation from the root environment, while `python` from the terminal was using the correct environment.

The following works:
1. Create a non-root environment for stan: `conda create -n bayes python=3.5 pystan jupyter`
2. Select that environment when creating a new notebook:

![screen shot 2017-04-06 at 10 19 32 am](https://cloud.githubusercontent.com/assets/360123/24759184/a8c7f1b0-1ab2-11e7-9a74-122c0b2bd690.png)

The issue therefore is really about why `pystan` cannot be used from the root Anaconda environment. I managed to install it in root, but it always crashes both from the notebook and terminal. For example, installing `pystan` in root produces:

```
(root) ~$ pip install pystan
Collecting pystan
  Using cached pystan-2.14.0.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied: numpy>=1.7 in ./anaconda/lib/python3.5/site-packages (from pystan)
Requirement already satisfied: Cython!=0.25.1,>=0.22 in ./anaconda/lib/python3.5/site-packages (from pystan)
Installing collected packages: pystan
Successfully installed pystan-2.14.0.0
```

But estimating the above model with the root environment produces:

```
(root) ~$ python stan_test.py
INFO:pystan:COMPILING THE C++ CODE FOR MODEL test_6c3f57429bde26462df851f85b22bb9f NOW.
Iteration:    1 / 2000 [  0%]  (Warmup) (Chain 0)
Segmentation fault: 11
```

So perhaps the simplest solution is to tell people on macOS not to use their root Anaconda environment?

**Comment by poliquin** [comment]
Sorry, but it's broken again. Installing `r-essentials` into the conda environment (following [Continuum's recommended procedure](https://docs.continuum.io/anaconda/r_language)) breaks the `pystan` installation for some reason.

Here is my terminal output before (working) and after (broken) installing `r-essentials`.

[before_r.txt](https://github.com/stan-dev/pystan/files/903906/before_r.txt)
[after_r.txt](https://github.com/stan-dev/pystan/files/903907/after_r.txt)

Uninstalling `r-essentials` doesn't work; once it's been installed in the Anaconda environment, `pystan` is forever broken, even if `r-essentials` is removed.

Installing `r-essentials` before `pystan` doesn't work either. The output is the same.

This means my above comment about `pystan` not working in an Anaconda root environment could be wrong. I had installed `r-essentials` in my root environment.

I think it's important to have Python, R, and PyStan working in a single Anaconda environment so that it's possible to use Python, R, and both together via [`rpy2`](http://rpy2.readthedocs.io/en/version_2.8.x/) on a single project.

**Comment by ariddell** [comment]
Is this a bug against PyStan? Or does it have to do with Anaconda?

**Comment by ahartikainen** [comment]
Is conda R installing some libstd++/gcc files (setting up R + c++ compiler can be a tricky thing) and these are "overloading" your default files?

We had this problem with ubuntu + Anaconda

**Comment by poliquin** [comment]
I initially thought this was a PyStan problem, but the issue appears to be what @ahartikainen describes.

For anyone finding this in the future, I got it working with the following sequence...

```
conda create -n stan python=3.5 jupyter
source activate stan
conda install -c r r-essentials
conda install rpy2  # (for communication between R and Python)
conda install gcc   # (fixes whatever r-essentials did to gcc)
pip install pystan
```

There is indeed some kind of gcc incompatibility between the `r-base` package and `pystan`. Using `conda install gcc` after installing R does not seem to have adversly affected my R environment and the Stan models correctly compile and run.

**Comment by ariddell** [comment]
Thanks for tracking this down!
