### ISSUE TITLE
pystan.StanFit4model.extract documentation improvement

### ISSUE THREAD

**Issue by randommm** [stan-dev/pystan#319]
#### Summary:
pystan.StanFit4model.extract documentation improvement suggestion

#### Description:
Right now, if argument `permuted`of `extract` is `False`, then `pars` is ignored, but the documentation doesn't say so and this is pontetially misleading. I can actually change this myself and send you the pull request if you wish.

#### Reproducible Steps:
Run example model, then:

In [108]: fit.extract("mu",False).shape
Out[108]: (500, 4, 19)

In [109]: fit.extract(["mu","tau"],False).shape
Out[109]: (500, 4, 19)

In [110]: (fit.extract(["mu","tau"],False) == fit.extract("mu",False)).all()
Out[110]: True

#### Current Output:
pars : {str, sequence of str}
    parameter (or quantile) name(s)
permuted : bool
    If True, returned samples are permuted. All chains are merged and
    warmup samples are discarded.
inc_warmup : bool
   If True, warmup samples are kept; otherwise they are discarded. If
   `permuted` is True, `inc_warmup` is ignored.

#### Expected Output:
pars : {str, sequence of str}
    parameter (or quantile) name(s). **If
   `permuted` is True, `pars` is ignored.**
permuted : bool
    If True, returned samples are permuted. All chains are merged and
    warmup samples are discarded.
inc_warmup : bool
   If True, warmup samples are kept; otherwise they are discarded. If
   `permuted` is True, `inc_warmup` is ignored.

#### PyStan Version:
pystan.__version__
'2.14.0.0'

#### Python Version:
3.5.2

#### Operating System:
Linux

**Comment by ariddell** [comment]
A PR would be great. Thanks for catching this.
