### ISSUE TITLE
implement documentation lookup function

### ISSUE THREAD

**Issue by ljwolf** [stan-dev/pystan#321]
#### Summary:
When using pystan, it'd be nice to have an equivalent to `rstan`'s [`lookup` ](https://rdrr.io/cran/rstan/man/lookup.html)

#### Description:
It's kind of annoying to have to continuously refer to the pdf reference manual, and would be nice to have a way to access the documentation directly from pystan. This would help improve package usability significantly. 

#### Reproducible Steps:
there is no `pystan.lookup` function. 

#### Current Output:
`''`

#### Expected Output:
feature parity with rstan's lookup function,

#### PyStan Version:
2.14

#### Python Version:
python 3

#### Operating System:
linux

**Comment by ariddell** [comment]
Oh this is rather neat. Seems like this might be equally/more useful as a webpage. Perhaps something like this: http://hyperpolyglot.org/numerical-analysis but with "Stan", "R", "NumPy" columns?

**Comment by bgoodri** [comment]
It is literally a lookup table, so just grab from

https://github.com/stan-dev/rstan/tree/develop/rstan/rstan/tools

**Comment by ahartikainen** [comment]
This is fixed by https://github.com/stan-dev/pystan/pull/337

Closing this issue.
