### ISSUE TITLE
bug during build ("could not create 'build'")

### ISSUE THREAD

**Issue by mrv-king** [stan-dev/pystan#321]
#### Describe the bug

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/stan/model.py", line 512, in build
    return asyncio.run(go())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/stan/model.py", line 481, in go
    raise RuntimeError(resp.json()["message"])
RuntimeError: Exception while building model extension module: `DistutilsFileError("could not create 'build': Permission denied")`, traceback: `['  File "/home/ubuntu/.local/lib/python3.8/site-packages/httpstan/views.py", line 114, in handle_create_model\n    compiler_output = await httpstan.models.build_services_extension_module(program_code)\n', '  File "/home/ubuntu/.local/lib/python3.8/site-packages/httpstan/models.py", line 168, in build_services_extension_module\n    compiler_output = await asyncio.get_running_loop().run_in_executor(\n', '  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run\n    result = self.fn(*self.args, **self.kwargs)\n', '  File "/home/ubuntu/.local/lib/python3.8/site-packages/httpstan/build_ext.py", line 80, in run_build_ext\n    build_extension.run()\n', '  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run\n    self.build_extensions()\n', '  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions\n    self._build_extensions_serial()\n', '  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial\n    self.build_extension(ext)\n', '  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension\n    objects = self.compiler.compile(sources,\n', '  File "/usr/lib/python3.8/distutils/ccompiler.py", line 565, in compile\n    self._setup_compile(output_dir, macros, include_dirs, sources,\n', '  File "/usr/lib/python3.8/distutils/ccompiler.py", line 348, in _setup_compile\n    self.mkpath(os.path.dirname(obj))\n', '  File "/usr/lib/python3.8/distutils/ccompiler.py", line 916, in mkpath\n    mkpath(name, mode, dry_run=self.dry_run)\n', '  File "/usr/lib/python3.8/distutils/dir_util.py", line 73, in mkpath\n    raise DistutilsFileError(\n']`
#### Describe your system

Virtual Machine: Linux 20.04 64-bit (under Windows 10 x64)
c++ compiler version 9.3.0
python version 3.8.10
#### Steps/Code to Reproduce

after executing of: "posterior = stan.build(schools_code, data=schools_data, random_seed=1)" string.

**Comment by riddell-stan** [comment]
@mrv-king The key bit of information here seems to be in the error message: `could not create 'build'`. Can you tell us more about your environment? I gather you're using WSL2?

**Comment by mrv-king** [comment]
17:46, 20 августа 2021 г., "riddell-stan" ***@***.***>:
@mrv-king The key bit of information here seems to be in the error message: could not create 'build'. Can you tell us more about your environment? I gather you're using WSL2?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
I am using VMware with Linux OS. I did not install WSL2. -- Отправлено из мобильного приложения Яндекс.Почты

**Comment by ahartikainen** [comment]
Is there a possibility that your python needs sudo rights?

**Comment by mrv-king** [comment]
I have tried so, but in this case I have this18:09, 20 августа 2021 г., Ari Hartikainen ***@***.***>:
Is there a possibility that your python needs sudo rights?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
-- Отправлено из мобильного приложения Яндекс.Почты
