### ISSUE TITLE
Fail to run pystan

### ISSUE THREAD

**Issue by evanzhu2013** [stan-dev/pystan#329]
#### Summary:
After reinstall pystan, the error happened. 

#### Description:
In [1]: import pystan
   ...: model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
   ...: model = pystan.StanModel(model_code=model_code)  # this will take a minu
   ...: te
   ...: y = model.sampling(n_jobs=1).extract()['y']
   ...: y.mean()  # should be close to 0
   ...: 
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-19d1f2b2eeb1> in <module>()
      1 import pystan
      2 model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
----> 3 model = pystan.StanModel(model_code=model_code)  # this will take a minute
      4 y = model.sampling(n_jobs=1).extract()['y']
      5 y.mean()  # should be close to 0

/Users/evan/miniconda3/lib/python3.6/site-packages/pystan/model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args)
    313                 os.dup2(orig_stderr, sys.stderr.fileno())
    314 
--> 315         self.module = load_module(self.module_name, lib_dir)
    316         self.module_filename = os.path.basename(self.module.__file__)
    317         # once the module is in memory, we no longer need the file on disk

/Users/evan/miniconda3/lib/python3.6/site-packages/pystan/model.py in load_module(module_name, module_path)
     48         pyximport.install()
     49         sys.path.append(module_path)
---> 50         return __import__(module_name)
     51     else:
     52         import imp

ImportError: dlopen(/var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmpwg679t6n/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_7904206874007668380.cpython-36m-darwin.so, 2): Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
  Referenced from: /var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmpwg679t6n/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_7904206874007668380.cpython-36m-darwin.so
  Expected in: flat namespace
 in /var/folders/95/3238q_5n5yg9r0gcmp221w4w0000gn/T/tmpwg679t6n/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_7904206874007668380.cpython-36m-darwin.so

#### Reproducible Steps:

import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0

#### Operating System: macOS Sierra 10.12.14 
Xcode version: 8.3.2 
GCC : brew install gcc

**Comment by ahartikainen** [comment]
Do you have Anaconda installed or numba? What version is your gcc?

**Comment by evanzhu2013** [comment]
GCC : gcc version 6.3.0 (Homebrew GCC 6.3.0_1 --without-multilib)
Conda :

Current conda install:

               platform : osx-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 2.1.10
         python version : 3.6.1.final.0
       requests version : 2.13.0
       root environment : /Users/evan/miniconda3  (writable)
    default environment : /Users/evan/miniconda3
       envs directories : /Users/evan/miniconda3/envs
                          /Users/evan/.conda/envs
          package cache : /Users/evan/miniconda3/pkgs
                          /Users/evan/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.6.1 Darwin/16.5.0 OSX/10.12.4
                UID:GID : 501:20

And numba is not installed.

Thanks for your help!!

**Comment by ahartikainen** [comment]
Hmm, ok. try conda env if that helps. 

If it will work then conda has been probably installing some libstdc++ files to your main conda environment that work only with gcc < 5.x (atleast 4.x will work).

**Comment by evanzhu2013** [comment]
I created a new conda environment. After installing the pystan, it did fail.

**Comment by ahartikainen** [comment]
It could be a problem with a libc++ vs libstdc++.

http://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean

Stan uses external libraries so it might be that gcc 6.x is not working with those. Could you try following in new environment

    conda install gcc

**Comment by evanzhu2013** [comment]
It works after creating a new package and conda install gcc.

I  really appreciate your help.
