### ISSUE TITLE
multi_normal missing?

### ISSUE THREAD

**Issue by dirknbr** [stan-dev/pystan#334]
I am getting this error 

```Ill-typed arguments to '~' statement. No distribution 'multi_normal' was found with the correct signature.Traceback (most recent call last):```

So for some strange reason that distribution is not supported. I updated my pystan to latest version with pip. But the latest stan version shows it exists.

https://mc-stan.org/docs/2_28/functions-reference/multivariate-normal-distribution.html

Is maybe the error message misleading?

**Comment by dirknbr** [comment]
Ok I found the bug, my Y was a matrix but needs to be vector.

Error message was confusing

**Comment by bob-carpenter** [comment]
@dirknbr:  We're working on trying to formulate error messages that'll be clearer to users.  Do you have a suggestion for how we can rephrase the one you ran into (keeping in mind that `multi_normal` has [multiple signatures](https://mc-stan.org/docs/2_28/functions-reference/multivariate-normal-distribution.html))?

> Ill-typed arguments to '~' statement. No distribution 'multi_normal' was found with the correct signature.

P.S.  If you want to vectorize, the variate can be an array of vectors (as can the location param, I believe).
