### ISSUE TITLE
pystan does not support python 2.7? What is the requirement on python version?

### ISSUE THREAD

**Issue by chenmin1107** [stan-dev/pystan#335]
AttributeError                            Traceback (most recent call last)
<ipython-input-13-9455a5c36040> in <module>()
----> 1 fit = pystan.stan(model_code=model_code, data=model_data, iter=100, chains=4)

/usr/local/lib/python2.7/dist-packages/pystan/api.pyc in stan(file, model_name, model_code, fit, data, pars, chains, iter, warmup, thin, init, seed, algorithm, control, sample_file, diagnostic_file, verbose, boost_lib, eigen_lib, n_jobs, **kwargs)
    393                      sample_file=sample_file, diagnostic_file=diagnostic_file,
    394                      verbose=verbose, algorithm=algorithm, control=control,
--> 395                      n_jobs=n_jobs, **kwargs)
    396     return fit

/usr/local/lib/python2.7/dist-packages/pystan/model.pyc in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)
    719         call_sampler_args = izip(itertools.repeat(data), args_list, itertools.repeat(pars))
    720         call_sampler_star = self.module._call_sampler_star
--> 721         ret_and_samples = _map_parallel(call_sampler_star, call_sampler_args, n_jobs)
    722         samples = [smpl for _, smpl in ret_and_samples]
    723 

/usr/local/lib/python2.7/dist-packages/pystan/model.pyc in _map_parallel(function, args, n_jobs)
     77         if n_jobs == -1:
     78             n_jobs = None
---> 79         with multiprocessing.Pool(processes=n_jobs) as pool:
     80             map_result = pool.map(function, args)
     81     else:

AttributeError: __exit__

**Comment by ahartikainen** [comment]
This is the same error as in #331

Fix: Update to 15.0.1

https://github.com/stan-dev/pystan/releases

**Comment by ariddell** [comment]
It's coming. It takes forever to build the OS X wheels.

**Comment by chenmin1107** [comment]
tried 2.14.0.0 and it works.

**Comment by ariddell** [comment]
Fixed. 2.15.0.1 is up on PyPI.
