### ISSUE TITLE
Documentation on sampling

### ISSUE THREAD

**Issue by pipme** [stan-dev/pystan#336]
#### Describe the problem with the documentation

How to pass parameters to `model.sample` is unclear. For example I don't know how to set `init`, `warmup` and `seed` properly. `ValueError: {'json': {'seed': ['Unknown field.']}}` is raised when doing `seed=1`. 

#### Suggest a potential alternative/fix

A more complete code example/tutorial need to be added.

**Comment by riddell-stan** [comment]
You're absolutely right about this documentation being missing. We had, in effect, an issue for this: https://github.com/stan-dev/pystan/issues/245

Contributions on this would certainly be welcome.
