### ISSUE TITLE
Calling posterior.unconstrain_pars with invalid input causes segfault

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan#338]
#### Describe the bug

When a user calls `posterior.unconstrain_pars` method and has a wrong input, the python process segfaults.

This was noticed while trying to answer how `posterior.unconstrain_pars` should be used

https://discourse.mc-stan.org/t/diagnostic-file-in-pystan/25936/3

#### Describe your system

WSL+Ubuntu 20

#### Steps/Code to Reproduce

```python
posterior.unconstrain_pars(invalid_constrained_params)
```

**Comment by riddell-stan** [comment]
Thanks! Likely needs to be addressed in httpstan if it involves a segfault. PyStan just serializes/deserializes.
