### ISSUE TITLE
Please add support & wheels for Python 3.10

### ISSUE THREAD

**Issue by MichaelClerx** [stan-dev/pystan#339]
This has been out for a couple of months now, and is the default version used by github actions at the moment. However, `pip install pystan` on Python 3.10 doesn't find a wheel, tries to install from source, and then fails.

**Comment by ahartikainen** [comment]
PyStan is compatible with all Python 3 versions and httpstan supports python 3.10.

PyStan 2.x is not supported anymore. That does not mean exclude adding new wheels for newer Pythons.


Have you considered updating pystan (/or use CmdStanPy?)

**Comment by riddell-stan** [comment]
Closing this because the report does not apply to PyStan. PyStan has supported Python 3.10 since November 2021.

If you need to move from PyStan 2.x to PyStan 3.x there is a migration guide here: <https://pystan.readthedocs.io/en/latest/upgrading.html>.

**Comment by MichaelClerx** [comment]
Thanks!
