### ISSUE TITLE
Instantiate Stan model object via 3-arg constructor so that RNG functions all use same seed

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/pystan#341]
#### Summary:
Check whether or not in pystan the RNG in the transformed data block is insensitive to seed.
See https://github.com/stan-dev/stan/issues/2241 for details.

**Comment by ariddell** [comment]
Almost positive PyStan is using the 2 arg constructor.

We should add a test in any event for the bug. The Stan model code is in stan-dev/stan#2241.

**Comment by ariddell** [comment]
This wasn't fixed in cmdstan for 2.16 so I'll push it to 2.17.

Sibling issues are:
- stan-dev/rstan#413
- stan-dev/cmdstan#551

**Comment by ariddell** [comment]
I'm (somewhat) wrong. The fix was merged into Stan but cmdstan release v2.16.0 without merging the fix stan-dev/cmdstan#552

Plan is to release v2.16.0 and then deal with this.

**Comment by ariddell** [comment]
Fixed by PR #355
