### ISSUE TITLE
Timeline for dropping testing and explicit support for Python 3.3 and Python 3.4

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#344]
Many projects have dropped 3.3 support. I'm tempted to drop 3.4 support in a year or so.

Given that only 3.5 and higher are supported on Windows, dropping tests for 3.3 and 3.4 is especially tempting.

My suspicion is that everything will still work for 3.3 and 3.4, PyStan will just not test against these versions.

If I don't hear any objections, I'll drop testing 3.3 now.

**Comment by bob-carpenter** [comment]
No objections from me.  The users list might be a place to get feedback on what people are using and what might be causing them to be locked into earlier versions.

**Comment by ahartikainen** [comment]
Sounds good.

My guess is that if anyone is still using python 3.3/3.4, it's on a server. In that case they are probably not going to update their setup.

**Comment by ariddell** [comment]
OK. In the next release, I'll drop (testing of) 3.3 and announce dropping testing for 3.4 on Nov 1, 2018.
