### ISSUE TITLE
Installation error on M1 mac. 

### ISSUE THREAD

**Issue by tbenthompson** [stan-dev/pystan#348]
#### Describe the bug

I get compilation errors when installing via `pip install pystan`. The relevant lines of the error output are below. I've also attached the entire output of the pip install run here: [error.txt](https://github.com/stan-dev/pystan/files/8163425/error.txt)
```
      INFO: clang: pystan/_misc.cpp
      pystan/_misc.cpp:15723:5: error: expression is not assignable
          ++Py_REFCNT(o);
          ^ ~~~~~~~~~~~~
      pystan/_misc.cpp:15725:5: error: expression is not assignable
          --Py_REFCNT(o);
          ^ ~~~~~~~~~~~~
      pystan/_misc.cpp:16018:5: error: expression is not assignable
          ++Py_REFCNT(o);
          ^ ~~~~~~~~~~~~
      pystan/_misc.cpp:16020:5: error: expression is not assignable
          --Py_REFCNT(o);
          ^ ~~~~~~~~~~~~
      pystan/_misc.cpp:16260:5: error: expression is not assignable
          ++Py_REFCNT(o);
          ^ ~~~~~~~~~~~~
      pystan/_misc.cpp:16262:5: error: expression is not assignable
          --Py_REFCNT(o);
```

#### Describe your system

I'm running on Mac OS on an M1 chip (arm64) and installing into a fresh conda environment. Compiler version:
```
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

#### Steps/Code to Reproduce

I created a fresh conda environment and then installed into that:
```
mamba create -n stan python=3.10
pip install pystan > error.txt 2>&1
```

**Comment by riddell-stan** [comment]
PyStan doesn't make pip-installable wheels for M1 right now. You can try installing httpstan from source (at which point pystan can be installed via pip).

If you encounter problems, feel free to post on the forum, https://discourse.mc-stan.org/
