### ISSUE TITLE
Release PyStan 2.16

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#353]
Title says it all.

**Comment by ahartikainen** [comment]
Are we going to include C++11 / C++14 to this release?

**Comment by bob-carpenter** [comment]
2.16 is intended to be the last C++03 compatible release.

**Comment by ariddell** [comment]
Thanks for the note @bob-carpenter . I've added the turn on C++11 flag to the 2.17 milestone.

I think we just need to update the source. I'll do this now.

Would be good to add a test for #341.
