### ISSUE TITLE
Order of samples from to_frame() is scrambled (?)

### ISSUE THREAD

**Issue by loulakiX** [stan-dev/pystan#357]
#### Describe the bug

The order of parameters returned from (py)stan (or at least the order of parameters from the `to_frame()` method seems to be scrambled when compared with an equivalent output of an OLS. Essentially after building a model, and sampling it with data being in a order, the output is not in the expected order. More on the code below. 

When I run the OLS (with statsmodels) as in `y ~ f1 + f2 + f3 + f4`, I get a sequence of coefficients which maintains the order `f1, f2, f3, f4`. However, the equivalent when doing the same regression with stan outputs `beta1, beta2, beta3, beta4` but the coefficients are scrambled. so `beta1` has the coefficient that is in eg `f3` from OLS, etc. I have noticed that the order is not consistent. Is this expected? Most probably I am doing something wrong (or understand something wrong) so would appreciate any guidance.

Since the code is with random numbers, let me illustrate a table here of 1 run that shows the issue:

`OLS`
<html>
<body>

  | coef | std err | t | P>\|t\| | [0.025 | 0.975]
-- | -- | -- | -- | -- | -- | --
|Intercept|-771.0307 | 56.405 | -13.669 | 0.000 | -883.009 | -659.052
|f1| 0.0523 | 0.020 | 2.618 | 0.010 | 0.013 | 0.092
|f2| 0.0652 | 0.042 | 1.562 | 0.122 | -0.018 | 0.148
|f3| 0.7690 | 0.058 | 13.334 | 0.000 | 0.654 | 0.883
|f4| -0.0140 | 0.007 | -2.083 | 0.040 | -0.027 | -0.001

</body>
</html>

`STAN`

  | mean | std
-- | -- | --
alpha | -769.905 | 57.38756
beta.1 | 0.064788 | 0.042176
beta.2 | -0.01387 | 0.006887
beta.3 | 0.052726 | 0.0202
beta.4 | 0.767813 | 0.058688

#### Describe your system

Ubuntu in Windows (Linux DESKTOP-49RJEMJ 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)
Python ver: Python 3.8.10
gcc version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

#### Code Sample, a copy-pastable example
```c
data {
  int<lower=0> N;   // number of data items
  int<lower=0> K;   // number of predictors
  
  matrix[N, K] x;   // predictor matrix
  vector[N] y;      // outcome vector
 }
transformed data {
  matrix[N, K] Q_ast;
  matrix[K, K] R_ast;
  matrix[K, K] R_ast_inverse;

// thin and scale the QR decomposition
  Q_ast = qr_thin_Q(x) * sqrt(N - 1);
  R_ast = qr_thin_R(x) / sqrt(N - 1);
  R_ast_inverse = inverse(R_ast);
}

parameters {
  real alpha;           // intercept
  vector[K] theta;      // coefficients on Q_ast
  real<lower=0> sigma;  // error scale
}

model {
  y ~ normal(Q_ast * theta + alpha, sigma);  // likelihood
}
generated quantities {
  vector[K] beta;
  beta = R_ast_inverse * theta; // coefficients on x
}
```

```python
# Your code here
N = 100
y= np.random.normal(100, 10, N)
f1 = y+np.random.normal(np.mean(y), np.std(y), len(y))
f2 = y+np.random.normal(1.5*np.mean(y), 6*np.std(y), len(y))
f3 = y+np.random.normal(3*np.mean(y), 2*np.std(y), len(y))
f4 = y+np.random.normal(10*np.mean(y), 0.5*np.std(y), len(y))
n0 = np.matrix([f1,f2,f3,f4]).T
obj = {
        "y"      : y,
        "N"      : N,
        "x"      : n0,
        "K"      : 4
}

posterior = stan.build(stan_code, data=obj)
fit = posterior.sample(num_chains=4, num_samples=1000)

df = fit.to_frame()
print(df.describe().T)

import statsmodels.formula.api as sm
X = pd.DataFrame(n0, columns={"f1","f2","f3","f4"})
X['y']=y
results = sm.ols(formula="y ~ f1+f2+f3+f4", data=X).fit()
results.summary()  
```

**Comment by treszkai** [comment]
@loulakiX When creating the DataFrame `X`, you define its columns as a [set](https://docs.python.org/3.8/library/stdtypes.html#types-set), which does not maintain insertion order:

```python
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> s = {'f1', 'f2', 'f3', 'f4'}
>>> list(s)
['f2', 'f4', 'f3', 'f1']
```

As the column name order matters (it shall be the same as the column order in `n0`), you should either define the columns as a list:

```python
X = pd.DataFrame(n0, columns=["f1","f2","f3","f4"])
```

or specify the DataFrame as a dictionary (which also preserves order, by the way):

```python
X = pd.DataFrame({"f1": f1, "f2": f2", "f3": f3, "f4": f4})
```

**Comment by loulakiX** [comment]
@treszkai 
It is one of those things that you check a hundred times and you cannot see the problem. I have to be honest with you, when I read your reply I said 'This guy doesn't get it'. Well, you do :), and thank you for taking the time to answer. I appreciate it.

You are absolutely right, the DataFrame construction method is the problem, not stan or anything else.
