### ISSUE TITLE
Runtime error while running the pystan model 

### ISSUE THREAD

**Issue by Harshitha-HM1999** [stan-dev/pystan#360]
Hi team, 

I'm getting the following error while running the pystan model,

`` RuntimeError: Exception: multiply: m1 must have a positive size, but is 0; dimension size expression = cols()  (in 'unknown file name' at line 25)
``

How can I resolve this?

Thanks in advance.

**Comment by ahartikainen** [comment]
Hi,

please ask this in Stan discourse (with the Stan code which is related to this error). GitHub issues is for the source code bugs etc.

https://discourse.mc-stan.org/
