### ISSUE TITLE
Models cannot compile on OSX due to Boost issue

### ISSUE THREAD

**Issue by rgerkin** [stan-dev/pystan#361]
#### Summary:
Models cannot compile on OSX due to Boost issue

#### Description:
If I try to compile the 8 schools model I get the following compiler errors shown below.    

#### Reproducible Steps:
```python
import pystan
schools_code = """
data {
    int<lower=0> J; // number of schools
    real y[J]; // estimated treatment effects
    real<lower=0> sigma[J]; // s.e. of effect estimates
}
parameters {
    real mu;
    real<lower=0> tau;
    real eta[J];
}
transformed parameters {
    real theta[J];
    for (j in 1:J)
    theta[j] = mu + tau * eta[j];
}
model {
    eta ~ normal(0, 1);
    y ~ normal(theta, sigma);
}
"""
schools_dat = {'J': 8,
               'y': [28,  8, -3,  7, -1,  1, 18, 12],
               'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}

sm = pystan.StanModel(model_code=schools_code)
```
I can't get the compiler stdout/stderr to show from a normal python shell, so I execute the above Python code from a Jupyter notebook with a Python 3 kernel, and then in the terminal output for the session that launched the notebook I get the errors shown in the Current Output section.  

I see other issues ([1](https://groups.google.com/forum/#!msg/stan-users/Q5aCotBsC8U/55dsJRHPDgAJ), [2](https://groups.google.com/forum/#!topic/stan-users/VcV9QrJ6-c0), [3](https://groups.google.com/forum/#!topic/stan-dev/pJb__w7Wjus)) discussing this error, with no clear solution, although pointing Stan to the correct Boost version may be part of it.  I did a`brew install` of the latest version of Boost (1.64) but that did not solve the problem.  

I get this error whether I `pip install pystan` or compile it from source.  

#### Current Output:
Here are the error lines: 
```
/miniconda3/lib/python3.5/site-packages/pystan/stan/lib/stan_math/stan/math/prim/arr/functor/integrate_ode_rk45.hpp:80:37: error: no member named 'max_step_checker' in namespace
      'boost::numeric::odeint'
      using boost::numeric::odeint::max_step_checker;
            ~~~~~~~~~~~~~~~~~~~~~~~~^
/miniconda3/lib/python3.5/site-packages/pystan/stan/lib/stan_math/stan/math/prim/arr/functor/integrate_ode_rk45.hpp:135:23: error: use of undeclared identifier 'max_step_checker'
                      max_step_checker(max_num_steps));
In file included from /miniconda3/lib/python3.5/site-packages/pystan/stan/src/stan/io/validate_zero_buf.hpp:4:
/Users/rgerkin/Dropbox/miniconda3/lib/python3.5/site-packages/pystan/stan/lib/stan_math/lib/boost_1.62.0/boost/lexical_cast/bad_lexical_cast.hpp:33:32: error: redefinition of 'bad_lexical_cast'
    class BOOST_SYMBOL_VISIBLE bad_lexical_cast :
                               ^
/Users/rgerkin/Dropbox/miniconda3/include/boost/lexical_cast.hpp:75:32: note: previous definition is here
    class BOOST_SYMBOL_VISIBLE bad_lexical_cast :
```

#### Expected Output:
I expect the model to compile.  

#### PyStan Version:
2.16.0.1dev

#### Python Version:
3.5

#### Operating System:
OSX 10.12.5

**Comment by bioinfonm** [comment]
I've got this running on OS X 10.11.6 using Anaconda 3.6 install. And then using the Anaconda pip. 
I am not sure if you want to muck around with Anaconda.

**Comment by ariddell** [comment]
I'm not sure what's going on here. It does look like a Boost issue but this is also unlikely because stan-math ships its own Boost. That and PyStan is being tested on macOS 10.11. Did something particular change in 10.11.6?

**Comment by ahartikainen** [comment]
Hi, let's first test if this bug is seen under conda env.

    conda update conda
    conda create -n stan python=3.6 numpy cython matplotlib jupyter notebook -c conda-forge
    activate stan
    pip install pystan
    # compile model with jupyter notebook. Add `verbose=True` to `pystan.StanModel(...)` and copy-paste compiler version.

**Comment by rgerkin** [comment]
Running @ahartikainen's code, the model compiles.  Lookin at the generated gcc command for the virtualenv version and my version I noticed that in both cases the first include path is the top level python include directory, i.e. `.../miniconda3/include` normally, and  `.../miniconda3/envs/stan/include` for the virtualenv.  In the normal (not virtualenv) include directory I found a boost directory.  Changing the name temporarily to boost.bak results in models compiling successfully outside the virtualenv.  

**Short-term solution**
So this is solved for now, by identifying the rogue boost include directory and changing its name (or deleting it), but I think that boost include directory might be used by something else that installed it there.  Probably not something incredibly common (like numpy) or someone else would have noticed it by now, but something I was probably using.  So I assume I'll have a problem in the future when I try to use whatever package was using that boost include directory.  

**Long-term Solution**
Can the order of the compiler includes in the system call generated Stan be changed so that the Stan-specific directories (e.g. `.../miniconda3/lib/python3.5/site-packages/pystan/stan/lib/stan_math/lib/boost_1.62.0` come before the default python ones?  That way the boost that Stan needs will be found first by the compiler.

**Comment by smatting** [comment]
I'm experiencing this issue as well on Python 3.4.2 with pystan==2.16.0.0 from pypi

On my mac the short-term solution worked like this
`mv /usr/local/Cellar/boost /usr/local/Cellar/boost.bak`

The compliation command that raises the error has these cc_args . I'm puzzled because `/usr/local/Cellar` is not listed in the include dirs.
```
['-DBOOST_RESULT_OF_USE_TR1',
 '-DBOOST_NO_DECLTYPE',
 '-DBOOST_DISABLE_ASSERTS',
 '-I/var/folders/dy/tmgtf_cx40z7l53j437ysbbm0000gn/T/tmpr5lu9jk1',
 '-I/usr/local/lib/python3.4/site-packages/pystan',
 '-I/usr/local/lib/python3.4/site-packages/pystan/stan/src',
 '-I/usr/local/lib/python3.4/site-packages/pystan/stan/lib/stan_math',
 '-I/usr/local/lib/python3.4/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3',
 '-I/usr/local/lib/python3.4/site-packages/pystan/stan/lib/stan_math/lib/boost_1.62.0',
 '-I/usr/local/lib/python3.4/site-packages/pystan/stan/lib/stan_math/lib/cvodes_2.9.0/include',
 '-I/usr/local/lib/python3.4/site-packages/numpy/core/include',
 '-I/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/include/python3.4m',
 '-c']
```

**Comment by ariddell** [comment]
Could clang or gcc be inserting /usr/local/Cellar/boost as an include directory somehow? Perhaps you can spot something in the compilation/error output?

**Comment by smatting** [comment]
I've found the root of the problem: `distutils.unixcompiler` is using this as the base compiler command: `['clang', '-Wno-unused-result', '-fno-common', '-dynamic', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-Wstrict-prototypes', '-I/usr/local/include', '-I/usr/local/opt/sqlite/include']` and thereby gives `/usr/local/include` precedence over all other include paths listed above. Homebrew has symlinked `/usr/local/include/boost` to `/usr/local/Cellar/boost/1.57.0/include/` on my machine, causing the problem.

Note that the same issue might also lead to problems if you have any of the other libraries (eigen, boost, cvodes) globally installed via Homebrew.

**Comment by bob-carpenter** [comment]
Thanks @smatting --- hopefully that'll be an easy fix that @seantalts or @syclik can deal with.
