### ISSUE TITLE
PyStan case studies

### ISSUE THREAD

**Issue by bioinfonm** [stan-dev/pystan#362]
#### Summary:
I am in the process of learning Pystan for work. I am putting together some cases studies for common models we use. I am building these in the juypter notebook under Python 3.6 . I was wondering if there was place to host or link these for other folks we are getting into Pystan. I noticed that Stan has many examples of case studies. 

Thanks,
ara

**Comment by ariddell** [comment]
Hi @bioinfonm! Thanks for the note.

There is a place to host examples, https://github.com/stan-dev/example-models

I don't believe anyone has contributed a Python example model but the README explicitly invites Python submissions.

**Comment by bioinfonm** [comment]
Thanks! I will submit it over there.

**Comment by bob-carpenter** [comment]
Yes, there's a case study by Chris Fonnesbeck, one of the PyMC3 authors, replicating Andrew and Phil Price's radon hierarchical model.

We can host the actual case studies or we can just put the results on the web.  We'd rather do the latter for case studies.
