### ISSUE TITLE
unconstrain_pars method crashes python if variables missing

### ISSUE THREAD

**Issue by mbrubake** [stan-dev/pystan#363]
#### Summary:
When passing a dictionary of parameters to unconstrain_pars if a parameter in the model is missing from the dictionary an unhandled C++ exception is thrown which crashes the entire python session.

#### Reproducible Steps:
The code: 
```
import pystan

model = pystan.StanModel(model_code='parameters { real x; } model { }')
fit = model.fit_class({})
fit.unconstrain_pars({})
```
Will produce a crash of the python interpreter.

```$ ipython
Python 2.7.13 (default, Apr 23 2017, 16:50:46) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pystan
   ...: 
   ...: model = pystan.StanModel(model_code='parameters { real x; } model { }')
   ...: fit = model.fit_class({})
   ...: fit.unconstrain_pars({})
   ...: 
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_618c519cb7159bec5904984ba3c147e8 NOW.
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: variable x missing
Abort trap: 6
```

#### Expected Output:
A standard python warning/error message.

#### PyStan Version:
Tested with 2.15 and 2.16

#### Python Version:
2.7

#### Operating System:
Tested on both OS X and Linux.

**Comment by ariddell** [comment]
This is an easy fix. I think we need to flag that particular Cython function as one which can raise exceptions.
