### ISSUE TITLE
`#include ...` does not work 

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan#365]
#### Summary:

`#include local_file.stan`

#### Description:

In stan 2.16 one can import external files with `#include file.stan` syntax. This does not currently work with Pystan.

#### Reproducible Steps:
from http://discourse.mc-stan.org/t/includes/1040

main stanfile: `bar.stan`

    parameters {
    #include baz.stan
    }
   model {
      target += normal_lpdf(theta | 0, 1);
    }

external file: `baz.stan`

    real theta;

In python:

    import pystan
    sm = pystan.StanModel(file="./bar.stan")

#### Current Output:

`could not find include file` that comes from [stan/io/program_reader.hpp](https://github.com/stan-dev/stan/blob/9470fc19596d53adc24071517bdee3a1d9efe470/src/stan/io/program_reader.hpp)

#### Expected Output:

Model should compile

#### PyStan Version:

2.16

#### Python Version:

3.6

#### Operating System:

Linux / osx

**Comment by bgoodri** [comment]
I think you need to specify the include paths. In RStan, they are by default the directory that the main Stan program is in, followed by the working directory (which are often the same). This commit implemented it:
https://github.com/stan-dev/rstan/commit/4a8380cb7a7a6becbf345fcc64f3704296c6050b

**Comment by ariddell** [comment]
This shouldn't be too hard to add. We'll need some tests too.

**Comment by ahartikainen** [comment]
We need to update the following

- [stanc.pxd](https://github.com/stan-dev/pystan/blob/develop/pystan/stanc.pxd)
- [stanc.hpp](https://github.com/stan-dev/pystan/blob/develop/pystan/stanc.hpp)
- [api.py](https://github.com/stan-dev/pystan/blob/develop/pystan/api.py)
- [_api.pyx](https://github.com/stan-dev/pystan/blob/develop/pystan/_api.pyx)
- [model.py](https://github.com/stan-dev/pystan/blob/develop/pystan/model.py)

They need to have keyword for `include_paths` that eventually goes to [`compile` function](https://github.com/stan-dev/stan/blob/d33b9b9067f48eb40d3f221bf6ff5a196dee252e/src/stan/lang/compiler.hpp). 

Default value should be list containing `cwd`?

**Comment by bob-carpenter** [comment]
Feel free to change or suggest changes to the underlying include mechanism---it may need changes in light of integration with PyStan and/or RStan.

**Comment by ariddell** [comment]
I made an issue stan-dev/stan#2351. Having Stan C++ reach into the filesystem is a problem, I think. R and Python both have particular ways of dealing with paths, so letting them figure out where the file(s) is/are seems like the right way to do things. And, of course, having Stan deal with paths is a showstopper for an interface (like httpstan) which doesn't have a concept of a filesystem.

**Comment by ahartikainen** [comment]
Should we expose the current set-up (`include_paths`), rewrite it as *`dict` method or do both?

In `dict` method, should user input str(path to file), str(model_code) or either one? Are there any scenario where this could fail (`os.path.exists`/`os.path.isfile`)?

**Comment by ariddell** [comment]
A minimum viable version would use absolute paths. Or does this already work? I haven't tried to use ``#include`` yet.

The next step would be to allow user-specified paths. Cython can automatically convert a list of (byte)strings to std::vector<std::string>, which is what stan::lang::compile wants (see https://github.com/stan-dev/stan/blob/develop/src/stan/lang/compiler.hpp )

The mismatch between what C++ expects (std::string, which is not necessarily valid utf8) and what a valid "path" is on any given platform is another reason to be careful about letting Stan poke around in the filesystem. To go down this particular rabbit hole I'll refer everyone to PEP519, https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep519

**Comment by sakrejda** [comment]
@ariddell You're bringing up a bigger issue here about `stan-dev/stan` touching the filesystem.  Could you put it in an issue on `stan-dev/stan` or document your argument in the stan-dev wiki?  This stinks of another rabbit hole if it's not addressed properly.

**Comment by ahartikainen** [comment]
Does C++ currently initialize to empty vector? This means it never tests if include exists and returns an error.

**Comment by ariddell** [comment]
@sakrejda There's stan-dev/stan#2351 , I think @bob-carpenter has seen it.

@ahartikainen stan::lang::compile initialize include_paths to an empty vector in C++.

It looks like the docs are wrong in compile.hpp

```
@param include_paths array of names of included files
```
I think it is really is a list of directories to search, not filenames.

**Comment by bob-carpenter** [comment]
Yes, that's definitely the list of directories to search.  The file names are appends of what's included to the end of the paths.

**Comment by bob-carpenter** [comment]
I created the issue to fix the doc on stan-dev/stan:  https://github.com/stan-dev/stan/issues/2353

But we'll probably generalize this first.

**Comment by ahartikainen** [comment]
Are we going to implement the current method before next release (2.17)?

And if we are implementig this, should it be able to read absolute paths? (the problem with empty directory list)

**Comment by ariddell** [comment]
I don't think the fix was merged in 2.17. I'm fine with not supporting this until there's a reliable way of doing this. Giving C++ some guesses about where the included files might be doesn't seem like the best solution.

**Comment by bob-carpenter** [comment]
The compiler accepts a bunch of paths, but I don't think
I ever wrote the more general callbacks.  @bgoodri also wants
it to accept space before the # sign for RStan backward
compatibility.

I can do that soon, but I don't think we want to wait on 2.17 for it.

-Bob

**Comment by ariddell** [comment]
Sounds good. I think accepting spaces before the ``#`` sign would also be helpful in PyStan given how many people use it. I myself tend not to use an external ``.stan`` file, so there are always leading spaces.

**Comment by bob-carpenter** [comment]
# sign is now deprecated for comments if that's what you mean by leading spaces without including external files.

**Comment by ahartikainen** [comment]
Usually, one writes the model code with multiline comment `""" ... """` and indentation (2/4/8 spaces). Example

    model_code = """
    ...
    model {
      #include x.bar
    ...
    """

and this translates to `"\nmodel {\n  #include x.bar\n..."`

**Comment by bob-carpenter** [comment]
@ahartikainen  How do you figure out line numbers for errors?  

Presumably the triple-apostrophe, triple-period escape will at least allow apostrophes (transpose) and double quotes (print, reject) inside the code.

**Comment by ahartikainen** [comment]
One could parse the model string by splitting `\n`. Also stripping start and is good idea.

In python this could be 

    model_code.strip().split('\n') # or .splitlines()

**Comment by ariddell** [comment]
There's also the ``textwrap.dedent``. I'm somewhat reluctant to transform a user's program code before sending it to Stan. If the code is going to be sanitized or transformed, I think Stan C++ should handle it if at all possible.

**Comment by ahartikainen** [comment]
I have done some edits, but it does not work yeat. I will do a PR and we can discuss the problems there.

**Comment by ahartikainen** [comment]
Fixed by #438 and #448
