### ISSUE TITLE
Cannot import StanModel

### ISSUE THREAD

**Issue by gcgibson** [stan-dev/pystan#367]
I am trying to run pystan but I keep getting 

from pystan import StanModel
ImportError: cannot import name 'StanModel'

$ pip freeze | grep pystan
pystan==2.16.0.0

**Comment by ahartikainen** [comment]
Is `import pystan; pystan.StanModel(...)` working?

Try to reinstall pystan

Either

    pip install pystan -U -f

or

    pip remove pystan
    pip install pystan

**Comment by gcgibson** [comment]
Hi @ahartikainen 

Neither format of import works. I successfully reinstalled pystan using the comments above but same error.

**Comment by gcgibson** [comment]
I was going to try and install from source but I get a 404 on this url

wget https://pypi.python.org/packages/source/p/pystan/pystan-2.16.0.0.tar.gz

**Comment by ahartikainen** [comment]
Can you try to download from here?

https://pypi.python.org/pypi/pystan/2.16.0.0

What os do you have and have you updated pip?

    pip install pip -U

To get latest github version

    pip install git+https://github.com/stan-dev/pystan.git

**Comment by gcgibson** [comment]
Hi, I have mac os 10.12.6... I have updated pip and installed the github master version. I am not sure what   is going on but maybe it is just a corrupted python? Pymc3 seems to work fine for me so I'm not sure.

**Comment by ariddell** [comment]
Thanks for the report. Could you uninstall pystan and then include the messages you see when you do a ``python3 -m pip install pystan``?

It's probably a good idea to install the wheel from PyPI rather than installing from source. There's a little bit less which can go wrong. It's also faster.

**Comment by ariddell** [comment]
I think this is probably a corrupted install or something like that.
