### ISSUE TITLE
Segmentation fault when trying to sample a hierarchical model

### ISSUE THREAD

**Issue by amodig** [stan-dev/pystan#368]
### Summary
Python kernel dies because of a segmentation fault when trying to sample a hierarchical model. The model and sampling works in RStan.

#### Background 
We have done Bayesian A/B testing analysis with an old Stan model ([legacy_updated.stan](https://github.com/amodig/stan_example/blob/master/legacy_updated.stan)). Usual data are transactions (each with a certain revenue) numbering in hundreds of thousands. For a faster analysis, we have used grouped sales data (i.e. transactions with the same revenue and test group are counted together). An example of this data is in [data_sales_grouped.csv](https://github.com/amodig/stan_example/blob/master/data_sales_grouped.csv).

Now we want to make a step towards A/B/C/.../N testing, and for this purpose, I've created a new hierarchical model [hier2.stan](https://github.com/amodig/stan_example/blob/master/hier2.stan) (similar to the partial pooling model here: http://mc-stan.org/users/documentation/case-studies/pool-binary-trials.html). I've tested that this model works in RStan. However, because of production purposes, we wish to implement this in PyStan.

#### Current issue
I can successfully create the hierarchical model [hier2.stan](https://github.com/amodig/stan_example/blob/master/hier2.stan), but when trying to fit/sample it, Python kernel simple dies because of a segmentation fault. First I thought this may be a parallelization issue, but the segmentation fault occurs even if `n_jobs=1`.

### Reproducible Steps
I've shared an example project on GitHub:
https://github.com/amodig/stan_example

The project has implementations in both PyStan and RStan ([stan_example.ipynb](https://github.com/amodig/stan_example/blob/master/stan_example.ipynb) and [stan_example.R](https://github.com/amodig/stan_example/blob/master/stan_example.R)). The scripts include both the legacy model (which runs OK in PyStan and RStan) and the new hierarchical model, and also a model comparison in RStan. The example data has only 2 test groups, but I have tested that the RStan implementation works with several more test groups.

### Current Output:
Segmentation fault.

### OS and versions:
```
CPython 3.6.2
IPython 6.1.0

numpy 1.13.1
pandas 0.20.3
seaborn 0.8.0
matplotlib 2.0.2
pystan 2.16.0.1dev
notebook 5.0.0

compiler   : GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)
system     : Darwin
release    : 16.7.0
machine    : x86_64
processor  : i386
CPU cores  : 8
interpreter: 64bit
```

**Comment by ariddell** [comment]
Thanks for this detailed report! PyStan shouldn't crash if RStan doesn't crash.

Is there a script available which we could use to reproduce the crash? A minimal version would be helpful. (It looks like ``https://github.com/amodig/stan_example/blob/master/stan_example.py`` has some jupyter/IPython stuff in it.)

**Comment by ahartikainen** [comment]
Hi,

I noticed you use Anaconda. Please first test to sample in a new conda environment. Anaconda has some c++ lib files that could interfere with the process.

    conda update conda
    conda create -n myenv python=3.6
    source activate myenv
    pip install  ... / conda install ...

**Comment by amodig** [comment]
I tried in a fresh conda env. Didn't help...

**Comment by ahartikainen** [comment]
I did try it on Windows, model compiled and sampling worked.

Could it be the clang compiler?

For conda environment try to install gcc

    conda install gcc libpython

**Comment by amodig** [comment]
Yes! That did it!

I added
```
os.environ["CC"] = "gcc"
os.environ["CXX"] = "g++"
os.environ["CXXFLAGS"] = "-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function"
```
to my script. This worked even with clang-compiled PyStan, but I re-compiled PyStan from source with gcc just to be safe:
```
export CC="gcc"
export CXX="g++"
export CXXFLAGS="-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function"
cd pystan
python setup.py install
```
The flags were suggested here, not sure if they're very useful with gcc:
https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Mac-or-Linux

I'm not very familiar with C++ so testing with a different compiler didn't come to my mind. Thank you very much!

(BTW, apparently you need conda `libpython` only on Windows.)
