### ISSUE TITLE
How to build a model without data and avoid building at run time?

### ISSUE THREAD

**Issue by eboileau** [stan-dev/pystan#373]
This is not a bug _per se_ , but rather I feel that this question has not been addressed, or at least I can't find a definitive answer.
But I think it is important enough to deserve it's own "bug report", rather than a post on the forums.

From experience, and from [#137](https://github.com/stan-dev/pystan/issues/137), or _e.g._ [here](https://discourse.mc-stan.org/t/can-a-pystan-3-model-be-compiled-without-data/23497), it does NOT seem possible to build a model without data in Pystan3. I don't think [#172](https://github.com/stan-dev/pystan/issues/172) is helping to solve the problem, and I can't find out how other developers are wrapping their head around this... I haven't found a suitable solution.

I am moving to Pystan3. Previously, I had several models that were each compiled once (and pickled) _e.g._ during program installation. 
During each program execution, these were loaded using `pickle.load`, and input for the models was constructed on the run _e.g._

```python
# construct the input for Stan and sample form each model
data = {...}
fit = [
        m.sampling(
            data=data,
            ...,
        )
        for m in models
    ]
```

Here, there could be many hundreds of input data (so the above snippet is typically called many times, possibly in parallel), and the data are NOT available prior to running the program, _i.e._ at installation. I don't even see how building models hundreds of time, each time you run the program, would make sense (and if this would work in parallel).

So any suggestions, ideas, recommendations would be very much welcome. Pystan is great, but I feel this is missing from the documentation, or maybe this needs to be considered more carefully (allowing building with empty data, _etc._ ), as I'm sure this issue is affecting many developers (as can be seen just googling the question...). Thanks.

**Comment by riddell-stan** [comment]
Thanks for the comment.

It should be easy to modify the pystan code to do what you describe. There's not much complexity in the pystan source code itself. You could also likely use cmdstan.

In order to make sure that pystan continues to be easy to maintain, we're keeping the set of features limited. If a feature isn't likely to be used by a lot of people, we tend to avoid adding it.

**Comment by eboileau** [comment]
Thanks for your quick reply.

After trying a few things, it seems possible to build/pickle a model using random data, load it later and sample from it (each call to build using new/different data should be relatively quick and without overhead, in principle, although I haven't tested it on real data), _(i)_ assuming that pystan can find the model and/or that the cache has not been cleaned, which might in general be difficult to control _e.g._ on cluster infrastructure, _etc._  _(ii)_ Another problem, if any, is that providing random data is a bit of a hack... see #143 

I think the problem is the requirement to provide data when compiling/building and, to be honest, I don't understand the rationale behind it.

Thanks, I will try to investigate how suitable CmdStan (or CmdStanPy) are, and how difficult it would be to re-write our programs/modify the pystan code.

**Comment by ahartikainen** [comment]
So the problem you have is calling build multiple times in parallel (maybe on multiple machines?)

In serial you only build once and then use the cache.

One option is to build that model with a fill data once and then save / fill httpstan cache next time you need to run the model (given multiple machines)?
