### ISSUE TITLE
Add testing and build for Python 3.11

### ISSUE THREAD

**Issue by MichaelClerx** [stan-dev/pystan#375]
Currently doesn't appear in the workflows. Presumably requires a 3.11 build of httpstan to be released too?
Other dependencies seem available: https://github.com/MichaelClerx/pystan/actions/runs/3409628420/jobs/5671634629

**Comment by riddell-stan** [comment]
Thanks for checking the dependencies. Remarkable that they are already available.

Building httpstan wheels is the first step. I opened a PR here https://github.com/stan-dev/httpstan/pull/626

**Comment by riddell-stan** [comment]
Python 3.11 httpstan wheels are up.
