### ISSUE TITLE
File descriptor leak

### ISSUE THREAD

**Issue by AlexHls** [stan-dev/pystan#377]
#### Describe the bug
Sampling a model leaks file descriptors, which becomes a problem when running many fits in sequence using the same process (e.g. during bootstrap resampling). Increasing the number of possible open files is a possible temporary fix, but does not work for huge number of resampling sequences. In my case, I need to run ~5*10^6 fits, which inevitably leads to and OSError [Errno 24]. It seems to originate from some bad file descriptors left behind by the `/tmp/httpstan_*.sock` files and some sockets (i.e. when trying to manually close the file descriptors, `os.fstat` returns a BadFileDescriptor error). I've attached a MWE illustarting the increase in the number of used file descriptors. This might be an upstream problem, but I could not verify this.

#### Describe your system
- Operating system: EndeavourOS (Arch-based)
- CPU type: x86-64
- C++ compiler version: GCC 12.2

#### Steps/Code to Reproduce

```python
import stan
import os

model = """
data {
  int<lower = 0> N;
  vector[N] x;
  vector[N] y;
  int<lower = 0, upper = 1> resample;
}
transformed data {
  simplex[N] uniform = rep_vector(1.0 / N, N);
  int<lower = 1, upper = N> boot_idxs[N];
  for (n in 1:N)
    boot_idxs[n] = resample ? categorical_rng(uniform) : n;
}
parameters {
  real alpha;
  real beta;
  real<lower = 0> sigma;
}
model {
  y[boot_idxs] ~ normal(alpha + beta * x[boot_idxs], sigma);
}
"""

schools_data = {"J": 8,
                "y": [28,  8, -3,  7, -1,  1, 18, 12],
                "sigma": [15, 10, 16, 11,  9, 11, 10, 18]}
data = {
    "N": 4,
    "x": [28, 8, -3, 7],
    "y":[15, 10, 16, 11],
    "resample": 1,
}

def get_fds():
    return len(set(os.listdir('/proc/self/fd')))

print("File descriptors before build: %d" % get_fds())
posterior = stan.build(model, data=data)
print("File descriptors before fit: %d" % get_fds())
fit = posterior.sample(num_chains=2, num_samples=1000)
print("File descriptors before second fit: %d" % get_fds())
fit = posterior.sample(num_chains=2, num_samples=1000)
print("File descriptors after second fit: %d" % get_fds())

```

Output (without stanc messages):
```console
File descriptors before build: 10
Building: found in cache, done.
File descriptors before fit: 10
Sampling: 100% (4000/4000), done.
File descriptors before second fit: 28
Sampling: 100% (4000/4000), done.
File descriptors after second fit: 30
```

**Comment by riddell-stan** [comment]
Thanks for the investigation.

What version of httpstan are you using? This should have been fixed in https://github.com/stan-dev/httpstan/pull/614

**Comment by AlexHls** [comment]
Apparently my httpstan version did not update when updating pystan. Updating manually to the newest version of httpstan seems to fix the issue. Thanks for the hint.
