### ISSUE TITLE
Question: output precision of pystan.stan

### ISSUE THREAD

**Issue by mdastro** [stan-dev/pystan#379]
#### Summary:
The output of the fit I am generating with pystan appears only with precision of 2 decimals.

#### Description:
I am running a logit model on pystan and when I print or save the results of my fit, the precision of all the parameters are only 2 decimals. I need a higher precision (3, 4, ... decimals). How can I set pystan to give me that? 

EDIT: Just to be clear, when I check the extract() method, my generated quantities appear with higher precision, but I have not added the quartiles to appear there. Since I just started using pystan, I still have several doubts on how to do a few things. If one could help add these outputs in the generated quantities, I would be very glad. The code I am running is available here:
https://github.com/mdastro/UV_ETGs/blob/master/Coding/Model/model_testing.ipynb

#### Reproducible Steps:
Any example of pystan will give you that. You just need to print the fit results to see it.

#### Current Output:
```
Inference for Stan model: anon_model_71dbacab9ac722a76ae9b8bb0d11db7d.
3 chains, each with iter=7000; warmup=3000; thin=1; 
post-warmup draws per chain=4000, total post-warmup draws=12000.

              mean se_mean     sd   2.5%    25%    50%    75%  97.5%  n_eff   Rhat
beta[0]      -2.99  5.7e-3   0.25  -3.49  -3.16  -2.99  -2.82  -2.52 1901.0    1.0
beta[1]      16.74    0.07   3.14  10.68  14.54  16.74  18.88  22.88 1761.0    1.0
beta[2]      -33.0    0.21    9.1  -51.0 -39.13 -33.12 -26.59 -15.57 1845.0    1.0
eta[0]       -1.98  1.6e-3   0.09  -2.17  -2.04  -1.98  -1.92   -1.8 3334.0    1.0
eta[1]       -0.97  1.0e-3   0.07  -1.12  -1.02  -0.97  -0.92  -0.83 5135.0    1.0
eta[2]       -2.13  2.1e-3   0.11  -2.35   -2.2  -2.13  -2.05  -1.92 2670.0    1.0
```

#### Expected Output:

I changed only the first two columns as an example.

```
Inference for Stan model: anon_model_71dbacab9ac722a76ae9b8bb0d11db7d.
3 chains, each with iter=7000; warmup=3000; thin=1; 
post-warmup draws per chain=4000, total post-warmup draws=12000.

              mean     se_mean     sd   2.5%    25%    50%    75%  97.5%  n_eff   Rhat
beta[0]      -2.9923  5.7332e-3   0.25  -3.49  -3.16  -2.99  -2.82  -2.52 1901.0    1.0
beta[1]      16.7434   0.0744   3.14  10.68  14.54  16.74  18.88  22.88 1761.0    1.0
beta[2]      -33.0567  0.2155    9.1  -51.0 -39.13 -33.12 -26.59 -15.57 1845.0    1.0
eta[0]       -1.9865  1.6666e-3   0.09  -2.17  -2.04  -1.98  -1.92   -1.8 3334.0    1.0
eta[1]       -0.9711  1.0887e-3   0.07  -1.12  -1.02  -0.97  -0.92  -0.83 5135.0    1.0
eta[2]       -2.1322  2.1777e-3   0.11  -2.35   -2.2  -2.13  -2.05  -1.92 2670.0    1.0
```

#### PyStan Version:
2.16.0.0

#### Python Version:
2.7

#### Operating System:
Linux Mint 14

**Comment by ahartikainen** [comment]
Hi,

the current develop and next release (2.17) has `stansummary` function. In there is a function to get a subset of parameters, setting up quantiles and option to set number of digits.

Currently, that function is under `pystan.misc._print_stanfit`.

**Comment by mdastro** [comment]
Wow, thank you for being so fast! I will try that ASAP! Thank you so much!

**Comment by mdastro** [comment]
It worked perfectly, thank you!
