### ISSUE TITLE
seg fault with pystan v2.19.1.1

### ISSUE THREAD

**Issue by cdeepali** [stan-dev/pystan#383]
#### Describe the bug
The script https://github.com/AnacondaRecipes/pystan-feedstock/blob/master/recipe/run_test.py with pystan v2.19.1.1 fails with segmentation fault. 

```
python run_test.py
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_0fe254f3c524d4153537de9712f3f235 NOW.
Segmentation fault (core dumped)
```

#### Describe your system
- Operating system - x86
- Anaconda's GCC - 11.2 
- Anaconda's Python - 3.9

#### Steps/Code to Reproduce
install pystan v2.19.1.1
execute script https://github.com/AnacondaRecipes/pystan-feedstock/blob/master/recipe/run_test.py

**Comment by cdeepali** [comment]
Found that this segfault is seen with latest version of scipy. 

with `scipy v1.9.3` the test example works.

**Comment by ahartikainen** [comment]
PyStan 2.x is not supported anymore, so there are multiple reasons why it starts to fail.

Good you find a solution.
