### ISSUE TITLE
Installation via conda leads to error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by dallascard** [stan-dev/pystan#384]
#### Summary:
Using conda to install pystan currently installs an older version of both pystan and cython than are installed via pip. Perhaps as a result of this, the version of pystan installed through conda throws an error when trying to compile a model.

#### Description:
I generally use conda as a package manager. I tried running an old model in pystan, and got an error ending in the following: 
`CompileError: command 'gcc' failed with exit status 1`
This seemed similar to https://github.com/stan-dev/pystan/issues/378 but it was unclear how that issue was resolved. 
I tried setting up a new conda environment with just the minimal packages required, but it still gives the same error.
I then tried creating a new environment (in conda), but installing packages via pip. This installed slightly newer versions of pystan and cython, and the model worked fine.

The versions installed via conda are:
python=3.6.2
numpy=1.13.1
cython=0.26
pystan=2.14.0.0

The versions installed via pip are:
numpy=1.13.1
cython=0.27.1
pystan=2.16.0.0

#### Reproducible Steps:
To reproduce this problem, install an environment with the following commands:
> conda create -n cstan python=3 numpy cython pystan
> source activate cstan
> conda install ipython

As a simple model, I used:
```
data = {'k': k, 'n': n}
model = """
data { 
  int<lower=1> n; 
  int<lower=0> k;
} 
parameters {
  real<lower=0,upper=1> theta;
} 
model {
  // Prior Distribution for Rate Theta
  theta ~ beta(1, 1);
  
  // Observed Counts
  k ~ binomial(n, theta);
}
"""
fit = pystan.stan(model_code=model, data=data, iter=1000, chains=4)
```

To get it working, I installed an environment using the following commands:
> conda create -n stan python=3 numpy
> source activate stan
> pip install cython
> pip install pystan
> pip install ipython

My gcc information is here:
which gcc = /usr/bin/gcc
gcc --version:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

#### Current Output:
Running the model with packages installed via conda gives:
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_8ed43513319d18ff0cf6006bf8266124 NOW.

DistutilsExecError                        Traceback (most recent call last)
~/anaconda/envs/cstan/lib/python3.6/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    117             self.spawn(compiler_so + cc_args + [src, '-o', obj] +
--> 118                        extra_postargs)
    119         except DistutilsExecError as msg:

~/anaconda/envs/cstan/lib/python3.6/distutils/ccompiler.py in spawn(self, cmd)
    908     def spawn(self, cmd):
--> 909         spawn(cmd, dry_run=self.dry_run)
    910 

~/anaconda/envs/cstan/lib/python3.6/distutils/spawn.py in spawn(cmd, search_path, verbose, dry_run)
     35     if os.name == 'posix':
---> 36         _spawn_posix(cmd, search_path, dry_run=dry_run)
     37     elif os.name == 'nt':

~/anaconda/envs/cstan/lib/python3.6/distutils/spawn.py in _spawn_posix(cmd, search_path, verbose, dry_run)
    158                           "command %r failed with exit status %d"
--> 159                           % (cmd, exit_status))
    160             elif os.WIFSTOPPED(status):

DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

CompileError                              Traceback (most recent call last)
<ipython-input-4-53438e118227> in <module>()
----> 1 fit = pystan.stan(model_code=model, data=data, iter=1000, chains=4)

~/anaconda/envs/cstan/lib/python3.6/site-packages/pystan/api.py in stan(file, model_name, model_code, fit, data, pars, chains, iter, warmup, thin, init, seed, algorithm, control, sample_file, diagnostic_file, verbose, boost_lib, eigen_lib, n_jobs, **kwargs)
    377         m = StanModel(file=file, model_name=model_name, model_code=model_code,
    378                       boost_lib=boost_lib, eigen_lib=eigen_lib,
--> 379                       obfuscate_model_name=obfuscate_model_name, verbose=verbose)
    380     # check that arguments in kwargs are valid
    381     valid_args = {"chain_id", "init_r", "test_grad", "append_samples", "enable_random_init",

~/anaconda/envs/cstan/lib/python3.6/site-packages/pystan/model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args)
    307 
    308         try:
--> 309             build_extension.run()
    310         finally:
    311             if redirect_stderr:

~/anaconda/envs/cstan/lib/python3.6/distutils/command/build_ext.py in run(self)
    337 
    338         # Now actually compile and link everything.
--> 339         self.build_extensions()
    340 
    341     def check_extensions_list(self, extensions):

~/anaconda/envs/cstan/lib/python3.6/distutils/command/build_ext.py in build_extensions(self)
    446             self._build_extensions_parallel()
    447         else:
--> 448             self._build_extensions_serial()
    449 
    450     def _build_extensions_parallel(self):

~/anaconda/envs/cstan/lib/python3.6/distutils/command/build_ext.py in _build_extensions_serial(self)
    471         for ext in self.extensions:
    472             with self._filter_build_errors(ext):
--> 473                 self.build_extension(ext)
    474 
    475     @contextlib.contextmanager

~/anaconda/envs/cstan/lib/python3.6/distutils/command/build_ext.py in build_extension(self, ext)
    531                                          debug=self.debug,
    532                                          extra_postargs=extra_args,
--> 533                                          depends=ext.depends)
    534 
    535         # XXX outdated variable, kept here in case third-part code

~/anaconda/envs/cstan/lib/python3.6/distutils/ccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    572             except KeyError:
    573                 continue
--> 574             self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    575 
    576         # Return *all* object filenames, not just the ones we just built.

~/anaconda/envs/cstan/lib/python3.6/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    118                        extra_postargs)
    119         except DistutilsExecError as msg:
--> 120             raise CompileError(msg)
    121 
    122     def create_static_lib(self, objects, output_libname,

CompileError: command 'gcc' failed with exit status 1

#### Expected Output:
Running the same model with the packages installed via pip gives:
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_8ed43513319d18ff0cf6006bf8266124 NOW.

Gradient evaluation took 3e-05 seconds
Gradient evaluation took 3.3e-05 seconds
...

#### PyStan Version:
see above

#### Python Version:
3.6.2

#### Operating System:
macOS Sierra 10.12.6

**Comment by ahartikainen** [comment]
Try `conda-forge` channel

    conda create -n cstan python=3.6 numpy cython pystan -c conda-forge

**Comment by dallascard** [comment]
Using the conda-forge channel worked! (and installed the same versions as pip).

I wasn't even sure if this should be an issue or not, but I thought it might be useful to others to have this solution online.

**Comment by ariddell** [comment]
@dallascard I was thinking the same thing. The conda-forge channel is new and we're just getting used to it.
