### ISSUE TITLE
'Fit' object has no attribute 'plot'

### ISSUE THREAD

**Issue by beew** [stan-dev/pystan#388]
I am trying to learn stan by running some examples but apparently there are a lot of changes from pystran2 to pystan3 and a lot of old examples one can find no longer work .

I am trying to invoke fit.plpt()

but get the error
"'Fit' object has no attribute 'plot'"

What is the way to do this in pystan3?  I have tried to find out but the documentations appear to be very incomplete.

Thanks

**Comment by ahartikainen** [comment]
Hi, you can use ArviZ.

https://python.arviz.org/en/stable/
