### ISSUE TITLE
Compiling From Source

### ISSUE THREAD

**Issue by ARudiuk** [stan-dev/pystan#389]
#### Summary:
I am trying to follow the instructions to install from git source and I am running through an issue.

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
`git clone ...`
`cd pystan`
`python setup.py install`

#### Current Output:
In file included from pystan/_api.cpp:567:0:
pystan/stanc.hpp:1:28: fatal error: stan/version.hpp: No such file or directory
compilation terminated.

#### PyStan Version:
-develop branch
#### Python Version:
-3.6.2
#### Operating System:
-ubuntu

If you want my entire output I can post that as well. If you want me to work on a pull request I am up for doing that as well!

**Comment by bgoodri** [comment]
I think you need to do

git clone --recursive ...


On Thu, Oct 19, 2017 at 12:27 PM, Alexander Rudiuk <notifications@github.com

**Comment by ARudiuk** [comment]
That worked! Thank you
