### ISSUE TITLE
Updating deprecated function

### ISSUE THREAD

**Issue by ARudiuk** [stan-dev/pystan#390]
#### Summary:
Update logging.warn to logging.warning

#### Description:
logging.warn is deprecated

#### Reproducible Steps:
Call extract function with permutation=False

#### Current Output:
DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead

#### PyStan Version:
development
#### Python Version:
3.x
#### Operating System:
ubuntu

I could make a pull request for this if you want, should be a simple fix!

**Comment by ariddell** [comment]
Thanks! This is something that should be fixed.
