### ISSUE TITLE
Where is label 2.19.1.1?

### ISSUE THREAD

**Issue by KathyGCY** [stan-dev/pystan#390]
# Describe the bug

I use orbit package and that pinned pystan to 2.19.1.1 in this requirement file [here](https://github.com/uber/orbit/blob/89c391ca9028400888a59ae378c5daae4c62b09b/requirements.txt#L4)

# Describe your system
-python 3.10

**Comment by bob-carpenter** [comment]
Assuming this is just asking where to get 2.19.1.1, see https://pypi.org/project/pystan/#history

**Comment by ahartikainen** [comment]
Hi, the source for pystan 2.x can be found in https://github.com/stan-dev/pystan2

**Comment by ahartikainen** [comment]
Also, latest orbit uses cmdstanpy, so have you considered updating your orbit version?

https://pypi.org/project/orbit-ml/

`pip install orbit-ml -U`
