### ISSUE TITLE
pickle a complied model and fit object together

### ISSUE THREAD

**Issue by ruyuanzhang** [stan-dev/pystan#391]
#### Summary:
I run pystan sampling on a server and pickle the compiled model and fit object together as a dict. Code are posted as below. 

```python
sm = pystan.StanModel(file='HierarchicalStan.stan')
fit = sm.sampling(data=act_motion_data, iter=nIter, warmup=nWarmup, chains=nChain, pars=watch_list)
stanACTresult = {'model': sm, 'fit': fit, 'data': act_motion_data}
if save == 1:
    f = open('{}motionstanACTresult.pkl'.format(prefix), 'wb')
    pickle.dump(stanACTresult, f)
    f.close()
```
However, if I try to download the .pkl file into my local machine, it reports error
I am trying to do:
```python
f = open('{}motionstanACTresult.pkl'.format(prefix), 'rb')
act_motion_result = pickle.load(f)
f.close()
```
```
In [49]:
    ...: f = open('{}motionstanACTresult.pkl'.format(prefix), 'rb')
    ...: act_motion_result = pickle.load(f)
    ...: f.close()
    ...: 
WARNING:pystan:No module named 'stanfit4anon_model_60d1f7a8f3c48eba2997b7bf9e81ea7c_1184005037104418924'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-49-4f61a7b7770d> in <module>()
      1 # ======== load the stan results
      2 f = open('{}motionstanACTresult.pkl'.format(prefix), 'rb')
----> 3 act_motion_result = pickle.load(f)
      4 f.close()

ModuleNotFoundError: No module named 'stanfit4anon_model_60d1f7a8f3c48eba2997b7bf9e81ea7c_1184005037104418924'
```

I've tested that if a pickle file can be correctly loaded if I only compile the model and only pickle the model on the local machine. 

I also try to separately pickle the compiled model and fit object. the model can be successfully recovered in my local machine. but the fit object cannot. it said:
```
In [56]: tmp = pickle.load(f)
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-56-30831f636c0b> in <module>()
----> 1 tmp = pickle.load(f)

EOFError: Ran out of input
```

#### PyStan Version:
Server: 2.17
local machine: 
#### Python Version:
Server: 3.6.2
local machine 3.6.1
#### Operating System:
Server: Ubuntu 14.04
local machine: OSX 10.11.6

**Comment by ahartikainen** [comment]
Not sure if a model compiled on linux will work on osx.
When you say, that you can load the model on osx, can you sample from it?

Please recheck the filesize for the last pickle file. Thats usually the error message for empty files.

Also make sure that you first unpickle model and after that fit object. The order matters.

**Comment by ruyuanzhang** [comment]
Thanks for your reply!

I just check. Even though I can unpickle a model on OSX, I can not sample it.

And yes, the last pickle file is empty. 

It seems the model and fit objects obtained in linux can only be rerun under linux. Hopefully this issue can be resolved in the future.

Thanks again.

**Comment by ahartikainen** [comment]
If you need to run your pickled models on osx, please try ubuntu on virtual machine / Docker. With suitable set-up, the Docker is quite easy to use.

See one (unofficial) example here https://github.com/ahartikainen/Docker-notes to get you started.

**Comment by ariddell** [comment]
Perhaps PyStan should provide a better error message here? The warning could include the question "are you trying to unpickle a model on a different operating system?"

**Comment by ariddell** [comment]
This is fixed in httpstan/pystan3 since models.py distinguishes among models compiled on different platforms.
