### ISSUE TITLE
Add warning about NumPy requirement in 2.18 release notes.

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan#394]
Packages including matplotlib have problems with very old versions of NumPy. To avoid these problems, PyStan will require a version of NumPy greater or equal to 1.8.2.

The requirement will be changed in 2.19 (i.e., in requirements.txt). A note about the changing requirement will be added in 2.18.

**Comment by riddell-stan** [comment]
@ahartikainen is NumPy 1.8.2 high enough?

**Comment by ahartikainen** [comment]
Sure, it is not about matplotlib/numpy only. It's about the numpy version they used to compile matplotlib on conda.

So let's say we would use Docker environments for testing we could run matplotlib with pip and I believe that could still work with 1.8.2.

Or we could even test just some old numpy and skip the plotting (that is just one test).

**Comment by riddell-stan** [comment]
I've thought about this a bit. I'm not sure we need to worry about this. If someone needs to use a newer version of matplotlib, they'll need to upgrade numpy. ``pip`` will take care of this for them. But none of this will be a problem for pystan, as pystan doesn't use any new or deprecated numpy features.

Please re-open if there's a need to require NumPy greater than 1.8 or 1.9. Currently 1.7 or higher is required.
