### ISSUE TITLE
document a programmatic way to get n_eff and Rhat

### ISSUE THREAD

**Issue by Eh2406** [stan-dev/pystan#396]
It would be very nice to have programmatic access to these results.
For example I want to know which variables did not mix well. I'd like to do:
`print(data.columns[fit.get_sampler_stats('n_eff')['beta'] < 100])` or something.
Edit:
This is possible, can we add it to the documentation?

**Comment by randommm** [comment]
You can do this with a not so simple method:

            irhat = fit.summary()['summary_colnames']
            irhat = irhat.index("Rhat")
            irhat = fit.summary()["summary"][:, irhat]

**Comment by Eh2406** [comment]
Thank you! I searched the documentation and the source code for `n_eff`, but did not find that.

Can we this as an example to the docs for the `summary` method?
Acutely, I don't see the docs for the `summary` method?

**Comment by ahartikainen** [comment]
Hi, to create pandas dataframe from the summary:

    import pandas as pd
    ....
    s = fit.summary()
    summary = pd.DataFrame(s['summary'], columns=s['summary_colnames'], index=s['summary_rownames'])

**Comment by Eh2406** [comment]
That is really slick! Where is `.summary()` documented? I'd love to do a pr to make this more visible, I at least did not find it in searching the docs, nore in searching the code.

**Comment by ahartikainen** [comment]
`fit.summary()` function lies inside [pystan/stanfit4model.pyx](https://github.com/stan-dev/pystan/blob/develop/pystan/stanfit4model.pyx)

The function is calling `_summary` function from [pystan/misc](https://github.com/stan-dev/pystan/blob/develop/pystan/misc.py)

    def summary(self, pars=None, probs=None):
        return pystan.misc._summary(self, pars, probs)

Where the start of the `_summary` function is.

    def _summary(fit, pars=None, probs=None, **kwargs):
        """Summarize samples (compute mean, SD, quantiles) in all chains.
        REF: stanfit-class.R summary method
        Parameters
        ----------
        fit : StanFit4Model object
        pars : str or sequence of str, optional
            Parameter names. By default use all parameters
        probs : sequence of float, optional
            Quantiles. By default, (0.025, 0.25, 0.5, 0.75, 0.975)
        Returns
        -------
        summaries : OrderedDict of array
            Array indexed by 'summary' has dimensions (num_params, num_statistics).
            Parameters are unraveled in *row-major order*. Statistics include: mean,
            se_mean, sd, probs_0, ..., probs_n, n_eff, and Rhat. Array indexed by
            'c_summary' breaks down the statistics by chain and has dimensions
            (num_params, num_statistics_c_summary, num_chains). Statistics for
            `c_summary` are the same as for `summary` with the exception that
            se_mean, n_eff, and Rhat are absent. Row names and column names are
            also included in the OrderedDict.
        """
        ...

We could probably make a bit more advanced tutorial for the docs, including the preferred workflow:

https://github.com/betanalpha/jupyter_case_studies/tree/master/pystan_workflow

**Comment by Eh2406** [comment]
Wow, how did I miss that when I searched github for 'n_eff'? That looks like good and clear documentation. Although I am not seeing it in the rendered documentation. https://pystan.readthedocs.io/en/latest/api.html# In fact I don't see a section for pystan/misc. (But I missed it searching github so my ability to find this may not be a great metrick.)

I think the workflow is a great place to talk about this! May I suggest the the sentence. "The first diagnostics we check are universal to Markov chain Monte Carlo and are displayed using the print method of the fit object," be extended with "or access using the `fit.summary()` method."

**Comment by ariddell** [comment]
@Eh2406 we could use some comment on diagnostics in the docs. It would be great to have the comment aligned with what appears in cmdstan and RStan docs. A new issue on this would be great.

I'll close this now since it's a different issue.
