### ISSUE TITLE
stan.build throws ValueError when python program is launched with nice

### ISSUE THREAD

**Issue by simkovic** [stan-dev/pystan#403]
#### Description:

stan.build throws ValueError when python program is launched with nice command

#### Reproducible Steps:
I copied the quick-start code from https://pystan.readthedocs.io/en/latest/index.html to schools.py file. Then I ran:

`nice -10 python schools.py`

#### Current Output:

`ValueError: The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.`

#### Additional Information:
Only crashes when a compilation is necessary. `python schools.py` works on my machine.

#### Current Version:
Pystan 3.7.0

**Comment by riddell-stan** [comment]
I'm not able to reproduce on Linux, Ubuntu 23.04. What operating system and platform are you using?

**Comment by simkovic** [comment]
I deleted the user Stan cache and now the nice command works. Since I can't reproduce the problem anymore I'm closing this issue.  For the record I'm using Arch Linux, Kernel 6.6.6-arch1-1
