### ISSUE TITLE
Create a 2.17.1 version based on Stan 2.17.1

### ISSUE THREAD

**Issue by pirg** [stan-dev/pystan#406]
#### Summary:
Request to add a new tag 2.17.1 using the 2.17.1 Stan version which fixes a performance bug added in 2.17.0

**Comment by ariddell** [comment]
In progress! Thanks for the reminder.

**Comment by ariddell** [comment]
The release is delayed due to problems with Travis-CI, which builds wheels for pystan.

If you're in a rush, you can install PyStan 2.17.1.0 from a tarball posted here: https://github.com/stan-dev/pystan/releases/tag/v2.17.1.0
