### ISSUE TITLE
Visualise chains using Bokeh

### ISSUE THREAD

**Issue by braaannigan** [stan-dev/pystan#412]
Is there interest in having visualisation routines available using Bokeh?  

#### Description:
The current traceplot routine uses the pymc function.  The output isn't particularly great when working in a jupyter notebook as the matplotlib plots may not be interactive.  I've written a short function that plots the output using Bokeh.  This makes for an interactive visualisation that in a jupyter notebook or opens up a tab in your browser if you're working in a shell.  A nice feature is that you can link the subplots, so that if you zoom in an part of the chain in one parameter, the other parameter all zoom in as well.

#### Reproducible Steps:
I've set out the example below.  I'm using:
numpy: '1.13.1'
pystan: '2.14.0.0'
bokeh: '0.12.7'
python: 3.6.1

#### Expected Output:
A window will open in your browser if you run the code below from the shell or it will appear in the notebook in the normal way when using jupyter.

```
import numpy as np
import pystan
from bokeh.plotting import figure, show
from bokeh.layouts import column

def chainsplot(fit):
    """Plotting function for the outputs of the MCMC chains
    Input:
    fit - Fitted stan model
    Outputs:
    None - A figure window opens in the browser if run from a terminal,
    or the figure window appears in the notebook in a Jupyter notebook
    """
    fig_dict = {}
    params = fit.extract()
    param_list = fit.unconstrained_param_names()
    # Loop over the parameters
    for idx,param_name in enumerate(param_list):
        # To link the plots, need the x_range of the first plot
        # To link the plots, need the x_range of the first plot
        if idx == 0:
            # Array that counts the iteration number
            iteration = np.arange( params[param_name].shape[0])
            fig_dict[param_name] = figure(title= param_name, height = 200, width = 600)
            x_range = fig_dict[param_name].x_range
        else:
            fig_dict[param_name] = figure(title= param_name, height = 200, width = 600,
            x_range=x_range)
        if "." not in param_name:
            # If the parameter is 1D
            fig_dict[param_name].line(iteration, params[param_name])
        else:
            # If the parametr is 2D
            param_short_name, feature_index = param_name.split(".")
            feature_index = int(feature_index) -1
            fig_dict[param_name].line(iteration, params[param_short_name][:,feature_index])
        fig_dict[param_name].xaxis.axis_label = "Sample number"
        fig_dict[param_name].yaxis.axis_label = "Sample value"
    show(column(list(fig_dict.values())))

beta = [1,-1]
X = np.random.normal(0,1,size = [100,len(beta)])
y = np.dot(X,beta)

model_code = """
    /* Spec for linear regression model */

    data {
        int<lower=0> N;                     // count of observations
        int<lower=0> K;                     // count of features
        matrix[N, K] X;                     // feature matrix
        vector[N] y;                        // outcome vector
    }
    parameters {
        real alpha;                         // intercept
        vector[K] beta;                     // slopes
        real<lower=0> sigma;                // linear model error
    }
    transformed parameters {}
    model {
        alpha ~ normal(0, 1);              // explicit prior for intercept (normal)
        beta ~ normal(0, 3);              // explicit prior for slopes (normal)
        sigma ~ normal(0, 3);              // explicit prior for error (half-normal)
        y ~ normal(alpha + X * beta, sigma);  // normal likelihood
    }
"""

sm = pystan.StanModel(model_code=model_code)

data = {'N': len(y), 'K':X.shape[1], 'X':X, 'y':y}
fit = sm.sampling(data=data, iter=2000, chains=4, warmup=1000)

chainsplot(fit)
```

**Comment by bioinfonm** [comment]
I like it! I'll give it a try. Most of my modeling work is down in the notebook.

**Comment by ariddell** [comment]
There still is hope everyone can share plotting utilities. Check out https://github.com/mcmcplotlib/mcmcplotlib . The goal is to use that library instead of something internal to PyStan. See #315 .

It would be fantastic if someone wanted to work on this. I'm not familiar enough with plotting code to be much use.

**Comment by braaannigan** [comment]
Should we close this issue?  The code above is there for anyone who is interested, otherwise people can work on the mcmc plotting or use the plotting built-in to pandas with the to_dataframe #425 PR.

**Comment by ahartikainen** [comment]
Let's close this issue. 

Please see https://github.com/arviz-devs/arviz (old mcmcplotlib). I hope we can get different backend there in the future.
