### ISSUE TITLE
Method to extract samples from fit to a Pandas dataframe

### ISSUE THREAD

**Issue by braaannigan** [stan-dev/pystan#413]
#### Summary:
We should have a method that allows a simple extraction of the samples to a pandas dataframe e.g. fit.extract().to_dataframe()

This would 
1) make it simple to get the full set of samples

2) give the output in a form that is easy to analyse further with pandas inbuilt analysis tools

3) make the output easy to visualise with pandas built-in plotting and other packages (e.g. #315) that make it easy to plot dataframes e.g. seaborn, bokeh and holoviews.

Pandas is a complicated package.  However, the routine I'm envisaging would simply read the parameters into a dataframe.  This part of the api has been stable for a long time (relative to the lifespan of pandas) and so should not be a difficult dependance to manage. 

Would people be interested in a PR along these lines?

**Comment by ariddell** [comment]
Yes, this would be great, if you're interested in working on this.

**Comment by ahartikainen** [comment]
Sounds great. 

Should we have also an option to export xarray objects? E.g. one dimension could be 'sample'. (I'm thinking about the ndimensional objects in Stan).

**Comment by braaannigan** [comment]
Hi @ariddell and @ahartikainen 

Great.

I was also thinking about the xarray option, so I'm happy to do that as well.  I'm giving some introductory stan workshops in the next few week, so the PR will be after that.

One question about dependencies: I was thinking that we would avoid introducing pandas and xarray as dependancies.  Instead, there would be an exception and an explanation of how to proceed if there is a ModuleNotfound error.  How does that sound?

**Comment by ahartikainen** [comment]
I think that is the smartest way to add these functions.

One more options could be to export summary table as a dataframe. Now it kind of returns its components (colnames, index, and data).

**Comment by braaannigan** [comment]
Hi @ariddell - I'm getting going on this now.

I'm a bit confused about where I should make the edits - do I add the method to the extract function in stanfit4model.pyx?  I'm not sure how to interpret the but about that file being a template rather than a proper cython file at the start.

**Comment by ahartikainen** [comment]
one option is to add a function to misc.py and then call it inside a fit-object.

**Comment by braaannigan** [comment]
Ok, just to make sure I've understood, the *basic* idea is to have:

_to_dataframe(fit,....) in misc.py and then a method of the fit object with call signature along the lines of to_dataframe(self) in stanfit4model.pyx that calls pystan.misc._to_dataframe(self,...).

**Comment by ahartikainen** [comment]
That sounds good.

We can handle the other options in PR (e.g. add diagnostic stuff)

**Comment by braaannigan** [comment]
Great, will have the PR for yous early next week.

**Comment by ahartikainen** [comment]
Fixed with `.to_dataframe` method, done in  https://github.com/stan-dev/pystan/pull/425

Closing this issue.
