### ISSUE TITLE
Declare variables in Model block?

### ISSUE THREAD

**Issue by djross2222** [stan-dev/pystan#414]
I'm switching from RStan to PyStan. One of my Stan models, which works with RStan, fails to compile in Pystan. 

The problem seems to be that I'm declaring new variables in the Model block of the Stan code. The start of the error message is: 
ValueError: Failed to parse Stan model 'anon_model_...'. Error message: SYNTAX ERROR, MESSAGE(S) FROM PARSER: variable "real" does not exist.
and it flags the first line of the Model block in the Stan code where I'm attempting to declare a new variable:
`model {`
`  real log_norm_Z;`

Before getting into the details, I wanted to first check on whether this is an intentional difference between RStan and PyStan - 

Thanks-

**Comment by bob-carpenter** [comment]
Thanks for reporting.

No, there should not be differences between RStan and PyStan.  

It would be very helpful if you could include a complete (preferably minimal) example of the problem.

**Comment by djross2222** [comment]
A minimal example is the mixture model code that is in the Stan reference (version 2.17.0, on page 194 of the pdf). In the code below, I fixed a couple of errors related to vector vs. array declaration, but otherwise left it the same code as in the Stan reference. It will compile in RStan but not in PyStan.

In this case, it throws an error at the first line of the Model block: "variable "vector" does not exist."


```
data {
  int<lower=1> K; // number of mixture components
  int<lower=1> N; // number of data points
  real y[N];      // observations
}

transformed data {

}

parameters {
  simplex[K] theta; // mixing proportions
  ordered[K] mu; // locations of mixture components
  vector<lower=0>[K] sigma; // scales of mixture components
}

model {
  vector[K] log_theta;
  
  log_theta = log(theta); // cache log calculation
  
  sigma ~ lognormal(0, 2);
  mu ~ normal(0, 10);
  
  for (n in 1:N) {
    vector[K] lps;
    lps = log_theta;
    for (k in 1:K) {
      lps[k] = lps[k] + normal_lpdf(y[n] | mu[k], sigma[k]);
    }
    target += log_sum_exp(lps);
  }
}
```

**Comment by bob-carpenter** [comment]
Thanks for the reproducible example.  Hopefully this will be easy to track down.

**Comment by ahartikainen** [comment]
I could not reproduce the error on unix (android).

Some question here:
What compiler are you using?
What is the text editor you use (and its encoding).
Do you have tabs instead of spaces in your code?
Is there an invisible char somewhere(end of line?)? Try to fix this by removing all the leading whitespace manually.

**Comment by bob-carpenter** [comment]
Thanks for looking, Ari.  I also suspect it may be an encoding problem.  Tabs shouldn't be a problem nor should invisible breaks, etc. in ASCII.  

Maybe https://github.com/djross2222 could cut and paste this and try it:

```
parameters {
  real y;
}
model {
  vector[2] z;
  y ~ normal(0, 1);
}
```

**Comment by djross2222** [comment]
To answer Ari's questions first:
Compiler: mingw32
Text editor: RStudio (ACSII)
I originally copied and pasted the example code from the Stan Reference pdf file. But when I checked, it didn't look like it had any tabs.
I tried cutting out all the extra white space - and got the same result: it compiles in RStan but not PyStan.

Also, I tried moving the variables declarations and assignments from the model block to the transformed  parameters block. That code compiled in both RStan and PyStan.

I tried Bob's simple example and it will compile in RStan but fails to compile in PyStan with the error: "variable "vector" does not exist."

I also tried a modified version of Bob's example:
```
parameters {
  real y;
}
transformed parameters {
  vector[2] z;
}
model {
  y ~ normal(0, 1);
}
```
This compiles successfully in both RStan and PyStan.

**Comment by bob-carpenter** [comment]
Thanks much for following up with this.  I need to move our docs to the web to avoid the vagaries of cutting-and-pasting LaTeX to pdf.

I'm surprised a 32-bit compiler can even handle our code.  I wonder if that's causing some kind of issue.  For R, we use the Rtools distribution of the C++ toolchain, which is 64-bit.

**Comment by djross2222** [comment]
My answer about which compiler I am using was based on looking in the distutils.cfg file.

After reading the online PyStan documentation more carefully (at https://pystan.readthedocs.io/en/latest/windows.html), and checking to see what packages are installed in my Python environment, it looks like it is set up consistent with the directions in the section "Setting up mingw-w64 on Windows."
So, m2w64-toolchain and libpython are installed. One difference is that instead of msys2, it has msys2-conda-epoch installed.

My Python environment was set up by installing Anaconda and then installing pystan from within Anaconda Navigator (i.e. **not** via pip). I didn't even think to look at the "PyStan on Windows" part of the online docs - since everything just seemed to work (until I tried a model with variable declarations in the Model block).

**Comment by ahartikainen** [comment]
Ok, I tested this with windows 10 and m2w64-toolchain + PyStan 2.17.1

Encodings utf8, ansi (ascii?) and one file created with notepad.

Used Bob's model.

All compiled fine.

So:

Try this first

    with open("path_to_file.stan", "rb") as f:
        print(f.read())

Are there anything special/unusual?

Next, try rewriting the stan file with python

    path = "path_to_file.stan"
    with open(path, "rb") as f:
        string = f.read()
    
    with open(path, "w") as f:
        print(string.decode('utf-8', 'ignore'), file=f)

And then try to compile the model.

ps. Have you updated your PyStan to the latest version?

**Comment by djross2222** [comment]
Ok.
First, I ran
```
with open("path_to_file.stan", "rb") as f:
    print(f.read())
``` 
the output was:
`b'parameters {\r\n  real y;\r\n}\r\nmodel {\r\n  vector[2] z;\r\n  y ~ normal(0, 1);\r\n}\r\n'`
So, nothing that looks weird to me.

Then after rewriting with python followed by the same `with open... print...`
the output was:
`b'parameters {\r\r\n  real y;\r\r\n}\r\r\nmodel {\r\r\n  vector[2] z;\r\r\n  y ~ normal(0, 1);\r\r\n}\r\r\n\r\n'`

Same result as before when I attempt to comile the re-written Stan file: it will compile in RStan but not PyStan.

I'm using PyStan version 1.17.0.0, which I didn't realize was no longer the latest.

**Comment by djross2222** [comment]
Sorry that it took me a while to get back to this - I got busy with another project.

Anyway, attempting to compile the simple example in the new conda environment produces the same result: 
```
ValueError: Failed to parse Stan model 'anon_model_d22d4fdb9cbe69251669c5446b3d68ff'. Error message:
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

variable "vector" does not exist.
  error in 'unkown file name' at line 9, column 9
  -------------------------------------------------
     7: model {
     8: 
     9:   vector[2] z;
                ^
    10: 
  -------------------------------------------------
```

**Comment by bob-carpenter** [comment]
Thanks for reporting.  I have no idea why a different environment would cause our parser to behave differently.   I can't imagine where this problem would arise in the parser.  

Was this a binary download?  If so, does anyone know what C++ compiler was used to produce stanc?  It uses a ridiculous amount of template programming through Boost in the parser and semantics, and various Windows compilers have had hard times with it in the past.

**Comment by djross2222** [comment]
I'm planning to switch to a different environment (probably Linux). 

Also, I've got a functional work-around: declaring and assigning to variables in the transformed parameters block instead of the model block.

So, since it looks like this issue is peculiar to my environment and likely outside the scope of something that could be easily fixed within the PyStan code, I'm ok with closing the issue.

If any of the PyStan developers want to continue digging, I'm willing to help to the extent that I can - just let me know if you'd like any additional information or if you'd like me to try anything else.

Thanks-

**Comment by mjurak1** [comment]
Hey everybody. 

I have the exact same problem as @djross2222 and I'm really new to using PySTAN and STAN in general. 

This is my model : 

paretonbd_model="""
data{
int<lower=0> n_cust; //number of customers 
vector<lower=0>[n_cust] x; 
vector<lower=0>[n_cust] tx; 
vector<lower=0>[n_cust] T; 
}

parameters{
// vectors of lambda and mu for each customer. 
// Here I apply limits between 0 and 1 for each 
// parameter. A value of lambda or mu > 1.0 is unphysical 
// since you don't enough time resolution to go less than 
// 1 time unit. 
vector <lower=0,upper=1.0>[n_cust] lambda; 
vector <lower=0,upper=1.0>[n_cust] mu;

// parameters of the prior distributions : r, alpha, s, beta. 
// for both lambda and mu
real <lower=0>r;
real <lower=0>alpha;
real <lower=0>s;
real <lower=0>beta;
}


model{

vector<lower=0> [n_cust] like1; // likelihood
vector<lower=0> [n_cust] like2; // likelihood 

// Establishing hyperpriors on parameters r, alpha, s, and beta. 
r ~ normal(0.5,0.1);
alpha ~ normal(10,1);
s ~ normal(0.5,0.1);
beta ~ normal(10,1);

// Establishing the Prior Distributions for lambda and mu : 
lambda ~ gamma(r,alpha); 
mu ~ gamma(s,beta);

// The likelihood of the Pareto/NBD model : 
like1 = x .* log(lambda) + log(mu) - log(mu+lambda) - tx .* (mu+lambda);
like2 = (x + 1) .* log(lambda) - log(mu+lambda) - T .* (lambda+mu);

// Here we increment the log probability density (target) accordingly 
target+= log(exp(like1)+exp(like2));
}
"""

When I try to compile the code the error is as follows : 

Unknown variable: vector
variable "vector" does not exist.
  error in 'unknown file name' at line 29, column 7
  -------------------------------------------------
    27: 
    28: // temporary variables : 
    29: vector<lower=0> [n_cust] like1; // likelihood
              ^
    30: vector<lower=0> [n_cust] like2; // likelihood 
  -------------------------------------------------


I'm using exact same environment as David. Is there any workaround, so the code would work ? Thank you very much.

**Comment by riddell-stan** [comment]
Hi, you want to post this question on the forum. The url is 
http://discourse.mc-stan.org/

This is the place for reporting bugs.

**Comment by ahartikainen** [comment]
Interesting. So do you use 2.17? Try the latest 2.18 (`pip install pystan -U`)

Running this with 2.18 on Windows throw me with

    require unconstrained. found range constraint.
    error in 'unknown file name' at line 27, column 34

Discourse is the correct place to get more help with your model.

**Comment by mjurak1** [comment]
Apologies, I'll move it. 
And sorry I was running it at 2.18, Windows 10.

Thank you anyways.

**Comment by djross2222** [comment]
The work-around that I found is to move the declaration and manipulation of
the local variable to the "transformed parameters" block. So, you would
need to modify your model code to read:

paretonbd_model="""
data{
int<lower=0> n_cust; //number of customers
vector<lower=0>[n_cust] x;
vector<lower=0>[n_cust] tx;
vector<lower=0>[n_cust] T;
}

parameters{
// vectors of lambda and mu for each customer.
// Here I apply limits between 0 and 1 for each
// parameter. A value of lambda or mu > 1.0 is unphysical
// since you don't enough time resolution to go less than
// 1 time unit.
vector <lower=0,upper=1.0>[n_cust] lambda;
vector <lower=0,upper=1.0>[n_cust] mu;

// parameters of the prior distributions : r, alpha, s, beta.
// for both lambda and mu
real <lower=0>r;
real <lower=0>alpha;
real <lower=0>s;
real <lower=0>beta;
}

*transformed parameters{*

*vector<lower=0> [n_cust] like1; // likelihoodvector<lower=0> [n_cust]
like2; // likelihood *



*  // The likelihood of the Pareto/NBD model :like1 = x .* log(lambda) +
log(mu) - log(mu+lambda) - tx .* (mu+lambda);like2 = (x + 1) .* log(lambda)
- log(mu+lambda) - T .* (lambda+mu);*

*}*

model{

// Establishing hyperpriors on parameters r, alpha, s, and beta.
r ~ normal(0.5,0.1);
alpha ~ normal(10,1);
s ~ normal(0.5,0.1);
beta ~ normal(10,1);

// Establishing the Prior Distributions for lambda and mu :
lambda ~ gamma(r,alpha);
mu ~ gamma(s,beta);

// Here we increment the log probability density (target) accordingly
target+= log(exp(like1)+exp(like2));
}
"""

**Comment by mirkhosro** [comment]
@djross2222 's workaround solved my problem as well. Thank you!
I'm running pystan 2.18 under Windows 10, Python 3.6.5 (Anaconda 4.5.11), g++ (Rev5, Built by MSYS2 project) 5.3.0

**Comment by ahartikainen** [comment]
Nice work @vtraag

Could you try this in a new conda environment? Still install from Anaconda channel. I wonder if it is linking to some boost version that ships with Anaconda by default.

**Comment by vtraag** [comment]
Thanks!

I did try it in a new `conda` environment. Perhaps it links to a `boost` version from `conda-forge`, perhaps that channel has priority. I'll look into it and get back to you, good suggestion.

**Comment by vtraag** [comment]
The use of `conda-forge` does not seem to be the cause of the problem. Even installing using `conda install pystan -c anaconda`  (giving the `anaconda` channel a higher priority) leads to the same problem.

I see that the `conda-forge` recipe seems [ready](https://github.com/conda-forge/pystan-feedstock/pull/11) to go. Your @ahartikainen [bugfix](https://github.com/stan-dev/pystan/commit/2a08f6621874216d0978cf2a77e06315b8191a97) seems to solve the compilation problem on [AppVeyor](https://ci.appveyor.com/project/conda-forge/pystan-feedstock/build/1.0.24/job/3frvp3ckvq4bxetc), but perhaps it needs a trigger to recompile? Then the `2.18.0` version should be correctly available from `conda-forge`. Still, this does not solve the problem of the package in the `anaconda` channel of course.

**Comment by Solarsw** [comment]
Hi, this still seems to be an issue. I am using pystan 2.18.0 with Anaconda on windows 7, and I get the above error. Can't find a workaround.

**Comment by vtraag** [comment]
@solarsw the workaround is to install from pip: pip install pystan==2.18.0

**Comment by Solarsw** [comment]
That is what I did originally where it gives the above error (at least if I remember correctly, I think with "conda install pystan" the installation already failed. I am trying "conda install -c conda-forge pystan" now, which goes to pystan 2.17.1. Otherwise I will try yours again.
