### ISSUE TITLE
Future warning while executing

### ISSUE THREAD

**Issue by JuanVeron** [stan-dev/pystan#419]
#### Summary:
While compiling C++ code I get a Future Warning 

#### Description:
While running my script I get the following warning:

/usr/local/lib/python3.5/dist-packages/pystan/misc.py:399: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`

The script runs just fine after that.

#### Reproducible Steps:
Just running any script

#### PyStan Version:
2.17.1
#### Python Version:
3.5.2
#### Operating System:
Ubuntu 16.04.3 LTS

**Comment by ariddell** [comment]
Thanks for the report. This should be easy to fix.
