### ISSUE TITLE
fit.to_frame()

### ISSUE THREAD

**Issue by seantalts** [stan-dev/pystan#421]
#### Summary:
I would love a fit.to_frame() or something. Difficult to get the data out in a form that's easy to work with. See https://github.com/betanalpha/jupyter_case_studies/blob/master/pystan_workflow/stan_utility.py#L97 for what we are currently doing. Would also make translating between RStan and PyStan much easier, since RStan has easy methods for getting dataframes or matrices out of fit objects.

**Comment by ahartikainen** [comment]
See discussion in #413

**Comment by seantalts** [comment]
Oops! Let me close this. Thanks for the link.
