### ISSUE TITLE
Traceplot uses permuted=True

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan#423]
Plots enable pars argument, which means that the extract returns permuted samples and can not use warm-up. The option to plot chains independently with or without warm-up can be important tool.

edit. Original issue had erroneous information.

**Comment by ahartikainen** [comment]
I have updated the plotting code.  We can use it until mcmcplotlib is stable.

Functions are divided for data generating functions and plotting functions. So implementing different backends is easier.

I will implement still a few different plots (forest, parcoords) and then make a PR (this will use the new permuted=False+pars option in extract).

@ariddell I will add some interactive plots and I don't want to add them in pystan/plots.py. Can we make folder for experimental stuff (what was the name you suggested sometime ago?). If people like them and they are stable we can move them somewhere else.

**Comment by ariddell** [comment]
@ahartikainen Yes, let's create a submodule for the experimental stuff. If ``experimental`` is too long (``pystan.experimental``) then there's also ``hazmat`` or ``x`` (so ``pystan.hazmat`` or ``pystan.x``).

**Comment by ahartikainen** [comment]
Fixed temporary by #474 

In future, this is fixed in ArviZ library.
