### ISSUE TITLE
Error when compiling from source: stan/version.hpp: No such file or directory

### ISSUE THREAD

**Issue by braaannigan** [stan-dev/pystan#424]
I'm putting together a PR for #413.  However, I can't test the changes on my system due to a compilation error: 

I've forked and cloned the repo and then changed to the pystan directory.  However, when I run
 ```python setup.py install```
I get an error message:
```
In file included from pystan/_api.cpp:557:0:
pystan/stanc.hpp:1:28: fatal error: stan/version.hpp: No such file or directory
 #include <stan/version.hpp>
```
The pystan/stan sub-directory in my forked repo is empty, though in my online repo that sub-directory links back to the main stan repo.  

I'm running python 3.6.1 on Ubunt 14.04.

Any suggestions for how to sort this?

Thanks!

**Comment by ahartikainen** [comment]
remember `--recursive`

    git clone --recursive https://github.com/braaannigan/pystan

**Comment by braaannigan** [comment]
Thanks @ahartikainen 

I still had import errors when I added the pystan directory to my pythonpath:
```
ModuleNotFoundError: No module named 'pystan._api'
```
To resolve it, I had to set the path to run to the sub-directory where the model build actually happened:
```
/path_to_cloned_repo/build/lib.linux-x86_64-3.6/
```

**Comment by ahartikainen** [comment]
This issue seems to be solved. 

I'm closing this issue.
