### ISSUE TITLE
Integrate Betancourt's stan_utility functions into PyStan

### ISSUE THREAD

**Issue by jjramsey** [stan-dev/pystan#427]
This is just a feature suggestion.

Betancourt wrote some useful postprocessing functions for a PyStan workflow: https://github.com/betanalpha/jupyter_case_studies/blob/master/pystan_workflow/stan_utility.py

It might make sense to add at least some of these functions into PyStan itself, especially the ones that check divergence, tree depth, and E-BFMI, since those are already done in RStan.

**Comment by bob-carpenter** [comment]
Ideally it'd be nice to have a generic posterior analysis setup, but many things like divergences are algorithm specific, so it's not as easy as it sounds.  A lot of these metrics, if not all of them, are available in ShinyStan and BayesPlot, which are not part of RStan.  The goal of breaking things up is to make development (including doc and testing) and maintenance more modular.

**Comment by betanalpha** [comment]
The functions in stan_utility.py just manipulate the default PyStan output to make it
easier to access diagnostics and check the diagnostics.  The same functionality
is available for RStan in the accompanying stan_utility.R.  To facilitate a robust
workflow where users check diagnostics with each run these functions are 
extremely useful and should be considered for incorporation into the interfaces.

**Comment by jjramsey** [comment]
> The same functionality is available for RStan in the accompanying stan_utility.R. 

Not only that, but at least a subset of that functionality is already in RStan itself, which (unlike PyStan) automatically warns about divergences, tree depth, and low E-BFMI. One could probably add the equivalent of that functionality by adding `check_all_diagnostics(fit)` (or a tweaked version of it) just before the line `return fit` in the `sampling()` function in the file [`model.py`](https://github.com/stan-dev/pystan/blob/readthedocs/pystan/model.py) of PyStan.

**Comment by jjramsey** [comment]
I've written what I *think* is a better integration of diagnostics into PyStan. If this looks good to you, I can see about trying to make a proper pull request. The values of adapt_delta and max_treedepth directly from the fit object, as they should be. I put the diagnostics in a separate submodule this time instead of shoving them into `misc.py`. Also, the diagnostics have been modified from Boolean return values, which may be useful when doing, say, scripting to process multiple fit objects at once (since a large number of fit objects could be made if, say, one were doing multiple imputation.) I'm not sure if allowing the `verbose` argument to be numerical would be considered a good thing, but I'll let you be the judge of that.

[diagnostics.py.txt](https://github.com/stan-dev/pystan/files/1713956/diagnostics.py.txt)
[__init__.py.txt](https://github.com/stan-dev/pystan/files/1713957/__init__.py.txt)
[model.py.txt](https://github.com/stan-dev/pystan/files/1713958/model.py.txt)

**Comment by ahartikainen** [comment]
Hi, I took a quick look. Looks good. Please make a PR.

How many levels of verbosity do you have?

There are some vectorization that can be done, but with usual datasize that could be unnecessary.

**Comment by jjramsey** [comment]
> How many levels of verbosity do you have?

The levels of verbosity are the following:
- No messages at all; only Booleans returned (`verbose` = `False` or `verbose` <= 0)
- Print messages only if there is a problem (`verbose` = `True` or `verbose` == 1)
- Print some sort of message even if there's no problem, such as a message indicating that a diagnostic check passed (`verbose` > 1)

**Comment by ahartikainen** [comment]
That scheme is reasonable.

Docstrings should follow numpydoc format.

Also we could add information per chain (where it is possible, e.g. n divergences).

Make a PR and we can discuss this in there.

**Comment by jjramsey** [comment]
I tried to create a pull request, but when I tried to do `git push -u origin feature/issue-427-add-diagnostics-from-betancourt`, I got the following errors:

```
remote: Permission to stan-dev/pystan.git denied to jjramsey.
fatal: unable to access 'https://github.com/stan-dev/pystan.git/': The requested URL returned error: 403
```

**Comment by bob-carpenter** [comment]
@jjramsey --- that only works for developers with merge permission on stan-dev.  We're moving to not granting that to people and asking people to fork and submit a pull request from their own repos.  Otherwise, @seantalts has the process set up so that everything else in the code review and continuous integration work the same way (at least for the core Stan C++ repos).

**Comment by ahartikainen** [comment]
Yes, do pull request from fork. Tests on PyStan will run after the PR is made.

**Comment by jjramsey** [comment]
Okay, I think I've got the pull request set up.

**Comment by ahartikainen** [comment]
Closed by #433

**Comment by sursu** [comment]
Hi, is there any documentation available for these functions?
When I run:
`pystan.diagnostics.check_hmc_diagnostics(fit)`
I get:
```
{'n_eff': True,
 'Rhat': True,
 'divergence': True,
 'treedepth': True,
 'energy': True}
```
These outputs are different when compared to the ones Michael has [here](https://mc-stan.org/users/documentation/case-studies/qr_regression.html) for instance.

**Comment by ahartikainen** [comment]
Try with `verbosity=2`.

I think we are missing good docs concerning this functionality.

**Comment by sursu** [comment]
I get same output:
```
{'n_eff': True,
 'Rhat': True,
 'divergence': True,
 'treedepth': True,
 'energy': True}
```

But then I noticed in the function description: `If ``verbose`` is greater than 2, then extra diagnostic messages are printed.`.

Tried with 3 and got this output:
```python
INFO:pystan:n_eff / iter looks reasonable for all parameters
INFO:pystan:Rhat looks reasonable for all parameters
INFO:pystan:No divergent transitions found.
INFO:pystan:No transitions that ended prematurely due to maximum tree depth limit
INFO:pystan:Chain 1: E-BFMI (= 1.02) equals or exceeds threshold of 0.2.
INFO:pystan:Chain 2: E-BFMI (= 0.936) equals or exceeds threshold of 0.2.
INFO:pystan:Chain 3: E-BFMI (= 1.06) equals or exceeds threshold of 0.2.
INFO:pystan:Chain 4: E-BFMI (= 0.991) equals or exceeds threshold of 0.2.
INFO:pystan:E-BFMI indicated no pathological behavior
```

**Comment by ahartikainen** [comment]
Oh, thanks. Yes I meant 3.
