### ISSUE TITLE
split_potential_scale_reduction can yield spurious nan values

### ISSUE THREAD

**Issue by jjramsey** [stan-dev/pystan#441]
The culprit is here:
```
if var_within < pystan.constants.EPSILON:
    srhat = float('nan')
else:
    srhat = sqrt((var_between/var_within + n_samples / 2 - 1)/ (n_samples / 2))
```
The problem is that it is quite possible to get a value of `var_within` less than `pystan.constants.EPSILON` (which is only 1e-6) even if the parameter in question isn't pathological.  Furthermore, since `cdivision` is True for `split_potential_scale_reduction`, even if var_within is zero, there shouldn't be a `ZeroDivisionError` exception. Rather, `srhat` would just be NaN. Thus, there's no need for that comparison.

**Comment by ahartikainen** [comment]
#442 fixed this.

I will close this issue.
