### ISSUE TITLE
Conflict with parameter names for dataframe

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan#443]
Will this fail with the current implementation of parameter names?

    parameters {
        vector[2] X;
        real X_1;
    }

`X` --> `X_1` & `X_2`
`X_1` then overwrites it.

Can we use double underscore (`__`) to separate name and indices? Currently, all the `sampler_params` are 1D so it wouldn't interfere with them. And parameter with double underscore is illegal in Stan (true or false?).

**Comment by ariddell** [comment]
This is about pandas, right?

When I use pandas, I never use the attribute access. I always type df['colname']. I don't think it's a bad thing if we have column names like `eta[1]`. This mirrors what the stansummary outputs anyway.

**Comment by ahartikainen** [comment]
Yeah, I guess thats the way to go. 
I use `.loc` and `.iloc` for parameter/point access so `X[1]` could work.

**Comment by ahartikainen** [comment]
#444 fixed this

I will close this issue.
