### ISSUE TITLE
Cannot build pystan - missing boost/variant/recursive_variant.hpp

### ISSUE THREAD

**Issue by pgarapon** [stan-dev/pystan#449]
I am trying to build pystan from source on windows 10 with VS 2015, and I am running into a compile error:

```
python setup.py install
[...]
building 'pystan._api' extension
[...]
Found executable C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe
_api.cpp
[...]
pystan/stan/src\stan/lang/ast/base_expr_type.hpp(4): fatal error C1083: Cannot open include file: 'boost/variant/recursive_variant.hpp': No such file or directory
```
the compilation stops on an error in that line:

```
error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DBOOST_DISABLE_ASSERTS -DBOOST_NO_DECLTYPE -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_RESULT_OF_USE_TR1 -DFUSION_MAX_VECTOR_SIZE=12 -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen_3.3.3 -Ipystan/stan/lib/stan_math/lib/boost_1.64.0 -Ipystan/stan/lib/stan_math/lib/cvodes_2.9.0/include -I"C:\Program Files\Anaconda3\include" -I"C:\Program Files\Anaconda3\include" -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tppystan/_api.cpp /Fobuild\temp.win-amd64-3.5\Release\pystan/_api.obj /EHsc -DBOOST_DATE_TIME_NO_LIB" failed with exit status 2
```

The file in question is located in the boost package: 
```
pystan-develop\pystan\stan\lib\stan_math\lib\boost_1.66.0
```
but it seems to be missing a prefix ? 

PyStan Version: current master 2.17.10

Python Version: Python 3.5.1 :: Anaconda 4.0.0 (64-bit)

Operating System: Windows 10 on x64 - intel

**Comment by pgarapon** [comment]
not sure how that happened but the version of boost I get is 1.66 while the makefile expect 1.64
fixed it and build proceeds .... (to the next error ? ) 

resolving anyway

**Comment by ahartikainen** [comment]
Did you do

    git clone --recursive https://github.com/stan-dev/pystan

or did you manually download the source?

Notice that PyStan uses specific releases of Stan lib (Stan 2.17 --> PyStan 2.17).

**Comment by pgarapon** [comment]
in fact I did (or tried) to manually zip the modules and submodules. (some firewall issue)
the build finished, but could not compile models. 

Re-attempting after figuring out a way to recursively clone ...
