### ISSUE TITLE
fatal error C1060 - compiler is out of heap space

### ISSUE THREAD

**Issue by pgarapon** [stan-dev/pystan#450]
After building pystan from source on windows10 / VS2015, whiel trying to compile a very simple model, I get( some warnings and):

```
C:\Program Files\Anaconda3\lib\site-packages\pystan\stan\lib\stan_math\stan/math/prim/mat/err/check_pos_definite.hpp(40): fatal error C1060: compiler is out of heap space

[...]
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2

```

the model is the test:
```
 model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
````
and the call is:
```
model = pystan.StanModel(model_code=model_code)
```

which then results in some python error msg. 

The build seems to be fine, any ideas ? 

PyStan Version: latest 1.27.10

Python Version: 3.5 Anaconda

Operating System: Windows10 / VS2015 / x64 Intel

**Comment by ariddell** [comment]
How much RAM does your system have?

**Comment by pgarapon** [comment]
16G - does not seem right to be taking that much to compile a very simple model
I saw something somewhere about a similar issue where some header files being compiled.

**Comment by pgarapon** [comment]
I see a bunch of warning about type conversion, that look benign but then I see some of those, about templates being compiled
```
C:\Program Files\Anaconda3\lib\site-packages\pystan\stan\src\stan/services/util/validate_dense_inv_metric.hpp(24): note: see reference to function template instantiation 'void stan::math::check_pos_definite<double>(const char *,const char *,const Eigen::Matrix<double,-1,-1,0,-1,-1> &)' being compiled
``` 
and then heap space runs out.

**Comment by ahartikainen** [comment]
Did you install PyStan with pip?

There are problems with MSVC, so it is possible that it has stopped working with the current codebase.

Have you tested gcc compiler? See https://pystan.readthedocs.io/en/latest/windows.html

And also updated step here https://github.com/stan-dev/pystan/pull/445

**Comment by pgarapon** [comment]
I built pystan from source with Visual C++ 14 (ships with VS2015)
It will be tricky (understatement?) to install a gcc compiler on my machine since I am not admin on it ( :) )
but I can give it a try, what is the recommended platform to run pystan ?

**Comment by ahartikainen** [comment]
Set up conda environment. No need for the admin rights. Instructions are in the link.

**Comment by pgarapon** [comment]
re-installed with pip and still get same error. 
```
$ pip install pystan
Collecting pystan
  Using cached pystan-2.17.1.0-cp35-cp35m-win_amd64.whl
Requirement already satisfied (use --upgrade to upgrade): Cython!=0.25.1,>=0.22 in c:\program files\anaconda3\lib\site-packages (from pystan)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7 in c:\program files\anaconda3\lib\site-packages (from pystan)
Installing collected packages: pystan
```
Is there a way to inspect the pystan package to make sure my python picks up the right version (pretty sure I cleaned up the install but just to double check)

next step ? Try gcc ?

**Comment by ahartikainen** [comment]
Yes, try to install GCC based on the instructions given in the earlier message. 

This is done with conda + text editor

**Comment by ahartikainen** [comment]
Hi, did you installed also Windows 10 SDK?

**Comment by ahartikainen** [comment]
I don't believe these two errors are the same.

This issue is about msvc error, that we don't support, your error seems to be a problem with memory. Can you install from wheels?

What python version are you using?

**Comment by win-t** [comment]
Oh, thanks, that solve my problem
So I just need to downgrade to Python 3.6 for now
