### ISSUE TITLE
Automatic diagnostics call in sampling method

### ISSUE THREAD

**Issue by Bonnevie** [stan-dev/pystan#452]
At the moment there is a call to the diagnostics routines at the end of the `sampling` method. I think this should be a switchable feature, as it can be a resource drain when running small chains for testing where the diagnostics are going to be nonsensical anyway. 
Alternatively, the automatic call should be removed completely and left to the user.

**Comment by ahartikainen** [comment]
What does RStan do? 

We could add keyword and maybe some check that it doesn'y run if there is less than n samples (n~10).

In general case I think automatic diagnostics are a good thing.

**Comment by Bonnevie** [comment]
Haven't used RStan I am afraid. I agree that auto-diagnostics are to be preferred, but I think anything called automatically as part of the absolutely most central function of PyStan should be switchable to accomodate the largest amount of different use cases.

I have noticed some other quirks. As it runs on both parameters and transformed parameters I get weird results (massive negative n_eff) if one of the transformed parameters is fixed (so zero standard dev., probably resulting in a division by zero). 

The diagnostics are also quite slow at the moment, and none of the provided functions return rhat or n_eff as anything but a string, making it hard to inspect e.g. issues with large matrix variables.

**Comment by Bonnevie** [comment]
Looks great :) Thanks for adding it. 
I think the helper function would be useful.
The diagnostics seem to run into some kind of computational bottleneck at times - is there anything that could be done to speed them up? Or maybe run them selectively on small blocks of parameters instead of the entire? I have a lot of matrix parameters and some near-constant generated quantities which might be causing havoc.

**Comment by ahartikainen** [comment]
`fit.summary` can take the `pars` argument. 

You can run diagnostics by hand later.

These are probably your bottlenecks (take test all the parameters)

    pystan.diagnostics.check_n_eff
    pystan.diagnostics.check_rhat

**Comment by ahartikainen** [comment]
Fixed by #456
