### ISSUE TITLE
Python 3.6 and Windows won't compile

### ISSUE THREAD

**Issue by cindylouwhovian** [stan-dev/pystan#460]
I am running python 3.6.4 (shipped with latest anaconda) with pystan 2.17.1.0 on Windows 7

I have both MSVC 14.0 and GCC 64 bit installed according to instructions on 
https://pystan.readthedocs.io/en/latest/windows.html

I am able to build and run schools example with MSVC 14.0.

I make edit to distutils.cfg adding

[build]
mingw32

I get error on schools code build:

 sm = pystan.StanModel(model_code=schools_code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pystan\model.py", line 313, in __init__
    build_extension.run()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 308, in run
    force=self.force)
  File "C:\ProgramData\Anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "C:\ProgramData\Anaconda3\lib\distutils\cygwinccompiler.py", line 285, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "C:\ProgramData\Anaconda3\lib\distutils\cygwinccompiler.py", line 129, in __init__
    if self.ld_version >= "2.10.90":
TypeError: '>=' not supported between instances of 'NoneType' and 'str'

My main goal is to use vectorized functions with pystan, however :

https://pystan.readthedocs.io/en/latest/windows.html#

which led me to think I needed GCC. 

What is the path forward?  Do I need to use an earlier version of python? If so, is there an easy way to downgrade version without uninstalling/reinstalling anaconda and all other packages?

CindyLouWhovian

**Comment by ahartikainen** [comment]
Change 

    [build]
    mingw32

To

    [build]
    compiler=mingw32

I fixed this in a recent PR, but the docs are not yet updated.

**Comment by cindylouwhovian** [comment]
Unfortunately that change did not do the trick.  I get the same error tree as above with the 
[build]
compiler=mingw32

Can you verify that even though I installed pkgs:

conda install libpython
conda install -c msys2 m2w64-toolchain

that I should be setting compiler=mingw32  ?

Also I have cygwin installed from old but not within anaconda or python.  Is that an issue?

Thank you for any help

**Comment by cindylouwhovian** [comment]
I got it working...I needed to conda reinstall the libpython and the toolchain for some weird reason.

Thanks for all your help!

**Comment by ahartikainen** [comment]
> Can you verify that even though I installed pkgs:
> 
> conda install libpython
> conda install -c msys2 m2w64-toolchain
>
> that I should be setting compiler=mingw32 ?

Yes, it is just telling distutils to call gcc.
Sometimes installations can fail so reinstalling was a good idea.

Good that everything works now.

**Comment by jimmyodonnell** [comment]
Hi @cindylouwhovian , when you say you "needed to conda reinstall" those packages, can you specify what you did or what the problem was? Did you use `conda upgrade ...`, or did you `conda uninstall ...` and then `conda install ...`?

@ahartikainen I have used stan on Mac with ease and joy in the past, but my new company uses only Windows machines. The Windows documentation could probably be made a little more clear (e.g. there are internal inconsistencies about what environments are supported)--is there any way I can help? I don't see a guideline for contributions, but am happy to submit a PR.

At the minimum, I think it would be great to have a brief preamble that explains using pystan on Windows is tricky, and will not result in a fully featured STAN implementation (e.g. no vectorized functions with Microsoft Visual C++ (msvc) -- but is this still recommended? I've seen conflicting information about whether parallel processing works). Some explicit recommendations from the maintainers might be useful. For example, is it preferable to use RStan for a fully functional STAN installation?

Thanks for all your hard work on this -- I certainly do not have your patience for these tasks!

**Comment by cindylouwhovian** [comment]
Hello @jimmyodonnell 

I opened an anaconda prompt.  I changed the directory to the anaconda install location. In my case anaconda is located in C:\ProgramData\Anaconda3

Then I typed:

conda install libpython
conda install -c msys2 m2w64-toolchain

I had done these installs before exactly as above but from a "cmd as Administrator" prompt 

I also think I did these installs before from an anaconda prompt but not while in the folder of the anaconda install.

I tried a bunch of things, so I only know the **last thing** I did that worked. 

CindyLouWhovian

**Comment by ahartikainen** [comment]
Hi @jimmyodonnel, I can feel your furtrastion.

On Windows I recommend you install miniconda, install packages with conda (add `compiler=mingw32` to cfg file.

If you have any recommended system, use it.

**Comment by jimmyodonnell** [comment]
@cindylouwhovian That is very helpful, thank you so much! I have at least 5 terminal emulators on my Windows machine, which does not make much sense to me. I had been doing all of this in git-bash, but I will try it through the Anaconda prompt. Thanks!

**Comment by jimmyodonnell** [comment]
Thanks @ahartikainen ; I have installed Anaconda and followed the instructions to modify the `distutils.cfg` file. I will try @cindylouwhovian 's suggestion to do this from the Anaconda prompt. If I get things running, I'll write out clear instructions for a blog post, and am happy to contribute to the installation docs if you'd like.

**Comment by ahartikainen** [comment]
The problem might be the git-bash, it comes with its own set of tools (gcc).

On windows I run my stuff always on the command prompt (I use cmder interface). Also I use conda environments, which usually fixes the errors in path variables.

E.g. if your Anaconda bin folder is after let's some other program with gcc, then the gcc is going to be wrong. One easy way to do this "without" conda environments is to activate your base user.

    activate base

**Comment by cindylouwhovian** [comment]
I need to qualify that I may have opened the **anaconda prompt as Administrator.** 
Fingers crossed here. 
If you still can't get it going, post your error tree for us to examine.  

CindyLouWhovian

**Comment by jimmyodonnell** [comment]
Thanks, I will report back when I have time to give this another try.

**Comment by JimmyRico** [comment]
> I got it working...I needed to conda reinstall the libpython and the toolchain for some weird reason.
> 
> Thanks for all your help!

Hi there, I have the same issue however I'd like to overcome it without using conda and installing both components from pip, however I haven't been able to do it for the toolchain. Could you please help me out with this part? Thank you!

**Comment by ahartikainen** [comment]
Hi, sorry, I don't know any easy solution for this without conda.
