### ISSUE TITLE
Problems with extracting the samples

### ISSUE THREAD

**Issue by pug18** [stan-dev/pystan#461]
#### Summary:
Please provide a short couple sentence summary.
What goes wrong the I get this error message 

#### Description:
Describe the issue as clearly as possible.
Traceback (most recent call last):
  File "/afs/rz.uni-jena.de/home/n/nu65jem/pyscripts/sample_uncorrelated_CCOCOCO_washout.py", line 205, in <module>
    main()
  File "/afs/rz.uni-jena.de/home/n/nu65jem/pyscripts/sample_uncorrelated_CCOCOCO_washout.py", line 199, in main
    get_data_and_sample(number_t, number_h, folder_start , Ion_ch, path)
  File "/afs/rz.uni-jena.de/home/n/nu65jem/pyscripts/sample_uncorrelated_CCOCOCO_washout.py", line 171, in get_data_and_sample
    chains)
  File "stanfit4anon_model_cadb1d8840ead372b33b226816813031_3427516963286921765.pyx", line 630, in stanfit4anon_model_cadb1d8840ead372b33b226816813031_3427516963286921765.StanFit4Model.__get$
  File "stanfit4anon_model_cadb1d8840ead372b33b226816813031_3427516963286921765.pyx", line 576, in stanfit4anon_model_cadb1d8840ead372b33b226816813031_3427516963286921765.StanFit4Model.extra$
  File "/afs/rz.uni-jena.de/home/n/nu65jem/myenv/lib/python3.6/site-packages/pystan/misc.py", line 810, in _check_pars
    raise ValueError("No parameter {}".format(par))
ValueError: No parameter 0

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

**Comment by ahartikainen** [comment]
Hi, could you please describe more what is the problem, how you are calling your function, etc.

Do you have some script what calls `fit.extract` and uses some index instead if getting name ?

    fit.extract(par=i)

vs

    fit.extract(par=parlist[i])

**Comment by pug18** [comment]
Hi ahartikainen,
the fit object is coming from the sampling. There might by some of the trys not working...
Do see why this occuring recently?

Thanks for your help.

def save_data_new(fit, folder, data_start, data_dec, N_free_param):
    if not os.path.exists(folder):
        os.makedirs(folder)
    os.chdir(folder)
    print(os.getcwd())

    np.save("data_start", data_start)
    np.save("data_dec", data_dec)

    try:
        sampling_data = pd.DataFrame(fit.extract(["rates","ratio", ], permuted=True))
    except:
        print("cannot make a pandas data frame")

    try:
        sampling_data.to_csv("sampling_daten")
    except:
        print("could not save fit_data")
    try:
        N_traces = fit.extract("N_ion_trace", permuted=True)["N_ion_trace"]
        np.save("N_traces",np.array(N_traces))
    except:
        print("N_traces param to fit")

    try:
        lp__ = fit.extract("lp__", permuted=True)["lp__"]
        lp__ = pd.DataFrame(data=lp__)
        lp__.to_csv("lp__")
    except:
        print("lp_ saving doesn t work")

    try:
        latent_time = fit.extract("LATENT_TIME", permuted = True)["LATENT_TIME"]
        np.save("latent_time", np.array(latent_time))
    except:
        print("LATENT TIME doesn t exist")

    try:
        latent_time_decay = fit.extract("LATENT_TIME_DECAY", permuted=True)["LATENT_TIME_DECAY"]
        np.save("latent_time_decay", np.array(latent_time_decay))
    except:
        print("LATENT TIME doesn t exist")

    try:
        occupat_dec = fit.extract("occupat_decay", permuted=True)["occupat_decay"]
        np.save("occupat_dec2", np.array(occupat_dec))
    except:
        print("occupat_decay doesn t exist")
   
  #mu = fit.extract("mu", permuted = True)["mu"]
    #np.save("mu", np.array(mu))
    try:
        equi_values = fit.extract("equi_values", permuted=True)["equi_values"]
        np.save("equi_values2", np.array(equi_values))
    except:
        print("could not open equi_values")

    try:
        occupat = fit.extract("occupat", permuted=True)["occupat"]
        print(occupat)
        np.save("occupat2",np.array(occupat))
    except:
        print("could not save occupat")

    try:
        log_lik_t = fit.extract("log_lik_t", permuted=True)["log_lik_t"]
        np.save("log_lik_t2", np.array(log_lik_t))
    except:
        print("could not save log_lik_t")

    try:
        log_lik_h = fit.extract("log_lik_h", permuted=True)["log_lik_h"]
        np.save("log_lik_h2", np.array(log_lik_h))
    except:
        print("cold not save log_lik_h")

    column_names = list()
    for id in range(1,np.int(N_free_param/2+1)):
        column_names.append("theta["+str(id)+"]")

    try:
        i_single =fit.extract("i_single_channel", permuted = True)["i_single_channel"]
        np.save("i_single", np.array(i_single))
    except:
        print("i_single problems")

    try:
     

        theta = fit.extract("rates", permuted=True)
        theta = pd.DataFrame(data = theta["rates"], columns =column_names)
        theta.to_csv("test")
    except:
        print("could not save theta")
        exit()

    for id in range(1,np.int(N_free_param/2+1)):
        column_names.append("rates["+str(id)+"]")

    try:
        ratio = fit.extract("ratio", permuted=True)
        ratio = pd.DataFrame(data=ratio["ratio"])
    except:
        print("ratio to data frame ratio did not work")

    try:
        ratio.to_csv("ratio")
    except:
        print("could not save ratio")

**Comment by ahartikainen** [comment]
Code is failing in this function (`sample_uncorrelated_CCOCOCO_washout.py`)

    get_data_and_sample(number_t, number_h, folder_start , Ion_ch, path)

get_data_and_sample(number_t, number_h, folder_start , Ion_ch, path)
File "/afs/rz.uni-jena.de/home/n/nu65jem/pyscripts/sample_uncorrelated_CCOCOCO_washout.py", line 171, in get_data_and_sample
chains)

**Comment by pug18** [comment]
I probably just found the bug with your hint! So fingers crossed I just let it sample again and we will see.
In line 171 in get_data_and_sample. I called a functions inside which the sampling was done. Strangly that function only returned the fit object but was only supposed to return the fit object + the pickeld model. Weird that python didn't tell me that the return objects didn't really match what was to be expect from  the outside...

Thanx for your help

**Comment by ahartikainen** [comment]
This issue seems fixed.

Let's reopen if not.
