### ISSUE TITLE
Logging behavior is altered when pystan is loaded

### ISSUE THREAD

**Issue by collincburton** [stan-dev/pystan#465]
#### Summary:
If I load a logger with the basic config and say that it should write to a file, after I import pystan, it will write all of my error messages to the console.

#### Description:
Logging doesn't appear to be implemented correctly in pystan as it is altering the behavior of the logging functionality I have built into my script.

#### Reproducible Steps:
If you run this code with the import pystan either included or excluded, it will change the behavior of the logging.

```
import logging
import pystan


logging.basicConfig(filename='log_test.log', level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')

logging.debug("test debug message")
logging.info("Info message")
logging.warning("Warning message")
```

#### Current Output:
logging output is written to the console

#### Expected Output:
Logging output should be written to a file.

#### PyStan Version:
2.17.1.0

#### Python Version:
3.6.4

#### Operating System:
MacOS 10.13.5

**Comment by collincburton** [comment]
It looks like it's a problem with __init__.py at line 18
```
if len(logger.handlers) == 1:
    logging.basicConfig(level=logging.INFO)
```
Per the logging docs (https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library)

> Note It is strongly advised that you do not add any handlers other than NullHandler to your library’s loggers. This is because the configuration of handlers is the prerogative of the application developer who uses your library. The application developer knows their target audience and what handlers are most appropriate for their application: if you add handlers ‘under the hood’, you might well interfere with their ability to carry out unit tests and deliver logs which suit their requirements.

When you add the basicConfig, you are adding a lot of different handlers and it is interfering with the desired logging behavior of the end user.

**Comment by riddell-stan** [comment]
This is how things work in PyStan. We use the logging facility to print messages. PyStan is not really a library, it's an application. I realize this is an idiosyncratic choice and we might want to consider printing our messages for the users to stderr with the `print` function.

**Comment by bob-carpenter** [comment]
Sorry this is getting off topic, but I think it would be helpful to think of PyStan as a library in the same sense as RStan.  Other Python packages might want to import it and use it.  It's not a low-level library like NumPy, but some of the same considerations about controlling I/O apply.  It's been an ongoing struggle in RStan to get truly silent output, for example.

**Comment by riddell-stan** [comment]
I think this is on topic! We should add documentation about how to 
silence the pystan (logging) output entirely. It shouldn't be difficult. 
What one should do -- and I think this should work now -- is configure 
your own logger handler before ``import``ing pystan.

Might even be worth writing a test to make sure this is indeed the 
behavior observed.
