### ISSUE TITLE
Can't import pystan: ValueError

### ISSUE THREAD

**Issue by camontanezp** [stan-dev/pystan#468]
#### Summary:
When I run "import pystan" in the anaconda prompt or in spyder, I get ValueError: More than one filename match found for utility code Capsule

#### Description:
I installed pystan and received a message saying that it was installed succesfully.

Then, I tried to import it, but it didn't work.

#### Reproducible Steps:
1) Intall pystan on windows following direction on 
http://pystan.readthedocs.io/en/latest/windows.html

2) import pystan 

#### Current Output:

  File "C:\Users\cmontane\AppData\Local\Continuum\anaconda3\lib\site-packages\Cython\Compiler\ModuleNode.py", line 3114, in <module>
    capsule_utility_code = UtilityCode.load("Capsule")

  File "Cython\Compiler\Code.py", line 359, in Cython.Compiler.Code.UtilityCodeBase.load

ValueError: More than one filename match found for utility code Capsule

#### Expected Output:
correct import

#### PyStan Version:
2.17
#### Python Version:
3.6.5 Anaconda
#### Operating System:
Windows 10

**Comment by ahartikainen** [comment]
Hi, looks like something is wrong with the Cython.

First step is to try reinstall the package.

    conda uninstall cython
    conda install cython

**Comment by camontanezp** [comment]
Import worked! 

Thanks a lot

**Comment by ahartikainen** [comment]
Great that everything works!
