### ISSUE TITLE
StanFit4Model produces duplicate traceplot for parameter

### ISSUE THREAD

**Issue by MaxHoefl** [stan-dev/pystan#473]
#### Summary:
`StanFit4Model.traceplot()` and `StanFit4Model.plot()` produce duplicate plot when `pars` parameter is `str` or list of length 1. Workaround is calling `pyplot.tight_layout()` but shouldn't be necessary.

#### Reproducible Steps:
```
beta_true = [2.0, 3.0]
toy_data = {}
toy_data['nobs'] = 200
toy_data['x'] = uniform.rvs(size=toy_data['nobs'])
toy_data['y'] = np.random.normal(loc=beta_true[0] + beta_true[1]*toy_data['x'],scale=1.0,size=toy_data['nobs'])

stan_code = \
"""
data {
    int<lower=0> nobs;
    vector[nobs] x;
    vector[nobs] y;
}
parameters {
    real beta1;
    real beta2;
    real<lower=0> sigma;
}
model {
    vector[nobs] mu;
    mu = beta1 + beta2*x;
    y ~ normal(mu, sigma);
}
"""

fit = pystan.stan(model_name="GaussianGLM", model_code=stan_code, data=toy_data, iter=5000, chains=3, verbose=False)

fit.traceplot(pars=["beta1"])
```

#### Current Output:
![duplicate stan traceplot](https://user-images.githubusercontent.com/14946739/42134203-8f9f6d78-7d2e-11e8-85f9-9f774b5c8b49.png)

#### Expected Output:
figure with 1 row and 2 columns

#### PyStan Version:
2.17.1.0

#### Python Version:
Python 3.6.1 :: Anaconda custom (x86_64)

#### Operating System:
macOS 10

**Comment by ahartikainen** [comment]
And what I forgot to tell is that the notebook shows the output of the last command if not suppressed manually or bind to variable.

And figure object is shown as figure.

You can try this by binding it to variable and the calling the variable in different cell without anything else

    fig
