### ISSUE TITLE
Enable thread_local

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan#475]
Should we follow the same procedure (env variable) as in httpstan (windows), so advanved users can set up `n` threads for each process?

I mean, should we have a kw option added to StanModel /.sampling statement?

**Comment by riddell-stan** [comment]
I was thinking we'd not mess with threads in pystan 2. We might invite Windows users who want to use threads to use pystan-next (once wheels are available, which we could post to github).

**Comment by ahartikainen** [comment]
I'm fine with this.
