### ISSUE TITLE
Docs should accurately describe Windows support

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan#483]
- mingw + conda supported
- MSVC completely unsupported

**Comment by riddell-stan** [comment]
Should also address #400 , modifying eight schools to trigger MSVC bug.

**Comment by ahartikainen** [comment]
Okey, I have a working appveyor script with mingw-w64 as a compiler. All tests pass (there are some fixes included).

Works for both 32 and 64:

- python 2.7 (parallel sampling doesn't work, infinite import loop)
- python 3.5 (parallel sampling works, output from C++ is just mixed)
- python 3.6 (parallel sampling works, output from C++ is just mixed)

I'm thinking of adding a python 3.7 too. It takes 1h to run all tests, so it should be 8 hours per commit. We can probably drop py35 at some point.

There is still some things to do (mostly cleaning stuff). I will probably make a new branch here and transfer needed materials manually.

Also need to make instructions for the install.

Also I needed to touch some cython files (calculation of ess) and misc.py to print nans.

**Comment by ahartikainen** [comment]
Fixed by #485
