### ISSUE TITLE
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated

### ISSUE THREAD

**Issue by mrtkp9993** [stan-dev/pystan#493]
#### Summary:
While fitting a model, Python gives this warning:
`/usr/local/lib/python3.6/dist-packages/pystan/misc.py:399: FutureWarning: Conversion of the second argument of issubdtype from "float" to "np.floating" is deprecated. In future, it will be treated as "np.float64 == np.dtype(float).type".
  elif np.issubdtype(np.asarray(v).dtype, float):`

#### Reproducible Steps:
Just try to fit a model.

#### PyStan Version:
`pystan-2.17.1.0`

#### Python Version:
`'3.6.3 (default, Oct  3 2017, 21:45:48) \n[GCC 7.2.0]'`

#### Operating System:
`Linux fc6511ed50f9 4.14.33+ #1 SMP Wed Jun 20 01:36:48 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux` (Google Colab Notebook)

**Comment by ahartikainen** [comment]
Hi, thanks for the issue.

This is already fixed in develop branch by #420
