### ISSUE TITLE
Users should be able to provide mass matrix as input

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan#505]
I'm told this is already in CmdStan. If it's supported by RStan, it should certainly be supported by PyStan.

**Comment by CasperHogenboom** [comment]
Is there any update on this? would like to input my own trained mass matrix in to Pystan

**Comment by ahartikainen** [comment]
This needs some changes in `stan.hpp`. In ideal case I find some time to implement this, but currently my time has gone to ArviZ lib.

Currently you can use ArviZ to read CmdStan results to python.

**Comment by ahartikainen** [comment]
Fixed by #611
