### ISSUE TITLE
Not able to compile models (Python 3.6, Pystan 2.18, Windows)

### ISSUE THREAD

**Issue by DSfrmBkln** [stan-dev/pystan#523]
I'm not able to compile models from code in pystan 2.18.  I'm running Python 3.6.6 (via Anaconda) on Windows 7.

#### Description:

when I run the following...

```>>> import pystan
>>> model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
>>> model = pystan.StanModel(model_code=model_code)
>>> y = model.sampling().extract()['y']
>>> y.mean()  # with luck the result will be near 0
```

... I get the following traceback:

```TypeError                                 Traceback (most recent call last)
<ipython-input-13-4c1dd9e82b54> in <module>
      1 model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
----> 2 model = pst.StanModel(model_code=model_code)
      3 y = model.sampling().extract()['y']

C:\ProgramData\Miniconda3\envs\py36\lib\site-packages\pystan\model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, include_paths, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args)
    348 
    349         try:
--> 350             build_extension.run()
    351         finally:
    352             if redirect_stderr:

C:\ProgramData\Miniconda3\envs\py36\lib\distutils\command\build_ext.py in run(self)
    306                                      verbose=self.verbose,
    307                                      dry_run=self.dry_run,
--> 308                                      force=self.force)
    309         customize_compiler(self.compiler)
    310         # If we are cross-compiling, init the compiler now (if we are not

C:\ProgramData\Miniconda3\envs\py36\lib\distutils\ccompiler.py in new_compiler(plat, compiler, verbose, dry_run, force)
   1029     # with classes that expect verbose to be the first positional
   1030     # argument.
-> 1031     return klass(None, dry_run, force)
   1032 
   1033 

C:\ProgramData\Miniconda3\envs\py36\lib\distutils\cygwinccompiler.py in __init__(self, verbose, dry_run, force)
    283     def __init__(self, verbose=0, dry_run=0, force=0):
    284 
--> 285         CygwinCCompiler.__init__ (self, verbose, dry_run, force)
    286 
    287         # ld_version >= "2.13" support -shared so use it instead of

C:\ProgramData\Miniconda3\envs\py36\lib\distutils\cygwinccompiler.py in __init__(self, verbose, dry_run, force)
    127         # same as the rest of binutils ( also ld )
    128         # dllwrap 2.10.90 is buggy
--> 129         if self.ld_version >= "2.10.90":
    130             self.linker_dll = "gcc"
    131         else:

TypeError: '>=' not supported between instances of 'NoneType' and 'str'
```

I did a clean install in a new environment.  I followed the instructions [here](https://pystan.readthedocs.io/en/latest/windows.html) to the letter, and I've examined https://github.com/stan-dev/pystan/issues/460 and https://github.com/stan-dev/pystan/issues/306.

I'm lost.  Anyone have any thoughts?

**Comment by ahartikainen** [comment]
Looks like it can not find the compiler.

Did you install `m2w64-toolchain` and `libpython`?

Also make sure you installed everything in the correct environment (and activated it after).

If you type `gcc --version` to cmd.exe what do you see?

**Comment by DSfrmBkln** [comment]
Yes, I installed both `m2w64-toolchain` and `libpython` per the instructions.

When I type `gcc --version` into `cmd.exe`, I get 

> 'gcc' is not recognized as an internal or external command, operable program or batch file.

**Comment by ahartikainen** [comment]
Do you run your code with anaconda prompt?

On `cmd.exe` you need to activate your environment (activation add correct paths to your $PATH env variable which enables to run these C/C++ programs, this is done by the anaconda prompt, but you still need to activate your environment).

If you type `which gcc.exe` or `where gcc.exe` you can see if your gcc is in the environment.

Opening anaconda prompt will enable automatically your `base` env, which is basically the same as typing `conda activate base` to cmd.exe.

**Comment by ahartikainen** [comment]
Also, make sure you call your code with correct environment.

If you run from another environment, but change only your `jupyter kernel`, it might mean that your python doesn't see your external non-python packages.

**Comment by ahartikainen** [comment]
Interesting.

Could it be related to this https://github.com/stan-dev/pystan/issues/472 ?

I have had something similar before.

Can you try a new miniconda installation (on a local folder)?

**Comment by DSfrmBkln** [comment]
Yes, I'll give that a try and report back.  Thanks much.

**Comment by DSfrmBkln** [comment]
I can't tell if it is related to that issue (https://github.com/stan-dev/pystan/issues/472), but I did try a brand new local installation of Miniconda, followed the instructions [here](https://pystan.readthedocs.io/en/latest/windows.html#) and ran into the same problem.  I'm stumped.

**Comment by ahartikainen** [comment]
Ok, just to make sure, you have double checked `distutils.cfg` file that should come with `conda install libpython`

    C:\ProgramData\Miniconda3\envs\py36\Lib\distutils\distutils.cfg

And it should contain

    [build]
    compiler=mingw32

**Comment by DSfrmBkln** [comment]
I checked and ran everything again.  Same error.  I also tried on my local installation and encountered the same problem.

**Comment by ahartikainen** [comment]
Thanks. I believe there was something funny going on with your $PATH, not sure what, but great that everything works again. 

I will close this now.

**Comment by aloosley** [comment]
I have the exact same error, installing on an Azure DSVM inside a venv I'd previously used.  

After installing from scratch on a fresh conda py3.7 venv following [these instructions](https://pystan.readthedocs.io/en/latest/windows.html#windows), everything worked fine.
