### ISSUE TITLE
FutureWarning: Cython directive 'language_level' not set

### ISSUE THREAD

**Issue by jg-you** [stan-dev/pystan#524]
#### Summary:
A FutureWarning appeared in `pystan` due to an update to `Cython`.

#### Description:
When compiling stan models with an up to date version of Cython (0.29-1), a FutureWarning is triggered. 

Note that the model compiles just fine anyways.

#### Reproducible Steps:

I have not tested it with many models, but any simple model should do it.

#### Current Output:

This is the output of the compilation call

    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5241895518e1a45d51f2191abfac2647 NOW.
    /usr/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/tmpsmjgku3j/stanfit4anon_model_5241895518e1a45d51f2191abfac2647_8034507843384787882.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)

#### PyStan Version:
pystan 2.18.0.0

#### Python Version:
python 3.7.0

#### Operating System:
archlinux

**Comment by riddell-stan** [comment]
Thanks! I think #525 should solve it.
