### ISSUE TITLE
pystan does not return a dictionary

### ISSUE THREAD

**Issue by ldv1** [stan-dev/pystan#536]
The started point is the code provided by Michael Betancourt in [Bayes Sparse Regression](https://betanalpha.github.io/assets/case_studies/bayes_sparse_regression.html):

generate_data.stan is given by

```
transformed data {
  int<lower=0> M = 200;
  int<lower=0> N = 100;
  real alpha = 3;
  real sigma = 1;
  real<lower=0, upper=1> sig_prob = 0.05;
}

generated quantities {
  matrix[M, N] X;
  real y[N];

  vector[M] beta;
  for (m in 1:M) {
    if (bernoulli_rng(sig_prob))
      if (bernoulli_rng(0.5))
        beta[m] = normal_rng(10, 1);
      else
        beta[m] = normal_rng(-10, 1);
    else
      beta[m] = normal_rng(0, 0.25);
  }

  for (n in 1:N) {
    for (m in 1:M)
      X[m, n] = normal_rng(0, 1);

    y[n] = normal_rng(X[1:M,n]' * beta + alpha, sigma);
  }
}
```

Originally, it was done in R, but I use pystan (version 2.18.0.0 on Suse 15.0):

```
import pystan

sm = pystan.StanModel(file='generate_data.stan')
fit = sm.sampling(iter=1, chains=1, seed=194838, algorithm="Fixed_param")

ex = fit.extract(permuted=False)
print(type(ex))
print(ex.shape)
```

I thought `ex` must be a dictionary, and I can access X, y, ... but it is an array of size (1,1,20301), so everything is there, but it is not convenient to extract all variables.
Is this behavior normal? If so, what can I do to get a dictionary?
 
thanks for any help,
Laurent

**Comment by ahartikainen** [comment]
Hi, it is a bit confusing. I have given some different option what you can do.

Default (this is ok for mean and std, but be aware of the permutation that "ruins" relative plots, histogram etc are fine.)

`fit.extract(pars=None, permuted=True) == dictionary with all samples permuted, shape = (nchain * ndraw, *par_shape)`

ndarray

`fit.extract(pars=None, permuted=False) == ndarray with all samples non-permuted, shape = (nchain, ndraw, nflattened_pars)`

non-permuted draws, 3D

`# all pars + lp --> fit.sim[pars_oi]`
`fit.extract(pars=fit.sim[pars_oi], permuted=False) == dictionary with all samples non-permuted, shape = (nchain, ndraw, *par_shape)`

pandas DataFrame

`fit.to_dataframe()`

FYI. the current develop ( `pip install git+https://github.com/stan-dev/pystan` ) has much faster extract and to_dataframe implementations (100k pars extraction is 10s where the older (current release, 2.18) it can take really long (4-6h).

There is also now ArviZ which is the recommended plotting library,. It has `InferenceData` object, which uses xarray.dataset to store values.

    import arviz as az
    inference_data = az.from_pystan(posterior=fit) # current master, latest release has az.from_pystan(fit=fit)
    inference_data.posterior.X

To install alpha-release / current master

    pip install arviz
    pip install git+https://github.com/arviz-devs/arviz

**Comment by ldv1** [comment]
thanks for your options! indeed, for a newbie, it is confusing that by simply setting permuted to `False` instead of `True` (it is `True` in all tutorials I read), the type of what is returned is no longer a dictionary.

just a few remarks:
1/ `pip install git+https://github.com/stan-dev/pystan` did not work, it hangs;
2/ `fit.to_dataframe()` leads to an error with version 2.18.0.0. I get
    
```
df = fit.to_dataframe()
  File "stanfit4anon_model_bffbbb74b4966d0346cdca26c00349a3_3663674612252554313.pyx", line 926, in stanfit4anon_model_bffbbb74b4966d0346cdca26c00349a3_3663674612252554313.StanFit4Model.to_dataframe
  File "/usr/lib64/python3.6/site-packages/pystan/misc.py", line 1231, in to_dataframe
    diag_list.append(fit.get_sampler_params()[n][diag + '__'][-n_save:].astype(diag_dtype))
KeyError: 'divergent__'
```
3/ the option `fit.extract(pars=fit.sim[pars_oi], permuted=False)` leads to
```
    ex = fit.extract(pars=fit.sim[pars_oi], permuted=False)
NameError: name 'pars_oi' is not defined
```

**Comment by ahartikainen** [comment]
Hmm, it might be that there is a bug in 2.18 version, if one has used `Fixed_param`, current develop should work.

Oh, I had a typo `pars_oi` --> `"pars_oi"`
Sorry for that.

You need to have git installed, but downloading and building Stan takes time (10min?), so be patient

For more verbose install

    pip install git+https://github.com/stan-dev/pystan -vvvv

**Comment by ldv1** [comment]
indeed, it takes time; I was more patient this time, and it worked (except for some errors at the end because I am using Python 3 and there are some print without ());

`fit.to_dataframe()` and `fit.extract(pars=fit.sim[pars_oi], permuted=False)` work with this version;

thank you once again for your prompt help!

**Comment by ahartikainen** [comment]
Those prints are from Boost / Eigen (test/validation?), so you should not be worried.
