### ISSUE TITLE
Question: substitute command for pystan.stan

### ISSUE THREAD

**Issue by mdastro** [stan-dev/pystan#546]
My question is really simple, I would like to know how should one run the equivalent of `pystan.stan` after deprecation.

I am getting the following warning from pystan when running a model:

> WARNING:pystan:DeprecationWarning: pystan.stan was deprecated in version 2.17 and will be removed in version 3.0. Compile and use a Stan program in separate steps.

Could someone just give me an example? Will it be only removed or replaced?

Thank you!

**Comment by ahartikainen** [comment]
```
model = pystan.StanModel(model_code=-..)

fit = model.sampling(data=data)
```

**Comment by riddell-stan** [comment]
All the examples in the docs use (or should use) the two-step process. 
The docs are here: 
https://pystan.readthedocs.io/en/latest/getting_started.html

The relevant two lines are:

```
sm = pystan.StanModel(model_code=schools_code)
fit = sm.sampling(data=schools_dat, iter=1000, chains=4)
```

So you first make a model instance and then call the `sampling` method 
using that instance.

Does this make sense?

**Comment by mdastro** [comment]
Thank you so much. :-)
