### ISSUE TITLE
size of Effective Sample Size

### ISSUE THREAD

**Issue by s144117** [stan-dev/pystan#548]
#### Summary:
Hi,
I am using pyStan with default settings.
A small section of the fit is shown below:

>> Inference for Stan model: None_c4ed8c57c14f2eabbd4599b428df4a4c.
>> 4 chains, each with iter=2000; warmup=1000; thin=1; 
>> post-warmup draws per chain=1000, total post-warmup draws=4000.

>>    mean     se_mean      sd    2.5%     25%     50%     75%   97.5%   n_eff   Rhat
>> m[1]  -5.2e4  9.8e-5 7.7e-3 -5.2e4 -5.2e4 -5.2e4 -5.2e4 -5.2e4   6190    1.0
>> m[2]  3138.7  1.0e-4 8.7e-3 3138.7 3138.7 3138.7 3138.7 3138.7   7062    1.0
>> m[3]  680.29  1.1e-4 8.8e-3 680.28 680.29 680.29  680.3 680.31   6155    1.0

If I am understanding it correctly, probably not, Then each chain provide 1000 samples giving a total of 4000 samples. How is it then possible to end up with an effective sample size larger than 4000?

If I have read correctly it is calculated as
>> n_eff = N/(1+2*sum(corr(lag)))

Thanks in advance
Michael

**Comment by bob-carpenter** [comment]
We recently fixed the ESS calculations to do the right thing when correlation is negative.  That's how you can get a larger effective sample size than the number of draws.

**Comment by s144117** [comment]
Which means reinstalling pyStan would solve it?

**Comment by ahartikainen** [comment]
Ess function is not broken on PyStan.

See https://mc-stan.org/docs/2_18/reference-manual/effective-sample-size-section.html

**Comment by bob-carpenter** [comment]
Right.  This isn't a bug.  The effective sample size can be larger than the number of draws.  We tested this with calibration (the effective sample size determines estimation error distribution, which serves as the basis of calibration).
