### ISSUE TITLE
Run time

### ISSUE THREAD

**Issue by s144117** [stan-dev/pystan#551]
Hi,
I am aware this is a vague question and am only looking for ideas and suggestions.

I am using NUTS for sampling spherical harmonics (SH). I am currently playing around with SH-degree 20-30, resulting in 500-1000 model parameters.
I use default settings: 4 chains with 1000 warm-up and 1000 post warm-up iterations, 10 tree-depth (never been necessary to increase). Always get Rhat=1.

Here's the question:
Sometimes a run can take 4 hours and sometimes 24 hours (Independent of whether I increase of decrease the amount of model paramters). 
I am not using the computer for anything else, thus nothing should interfere with the resources available. The applied model and data does not change. The posterior is uni-modal.
Do any of you have any suggestions as to why it can vary so much?

Thanks in advance
Michael

**Comment by ahartikainen** [comment]
Given that your model is high dimensional, there is some probability that initial values or just sampling goes to space which is hard to sample.

For more in-depth answer ask this in our discourse. https://discourse.mc-stan.org

**Comment by s144117** [comment]
Thank you for the quick answer, I will definitely try asking on discourse!
