### ISSUE TITLE
stan_cache

### ISSUE THREAD

**Issue by s144117** [stan-dev/pystan#552]
Hi,

When I installed pystan the first time I ran into problems with a missing stan_cache.
I solved it by simply changing the code in utils.py

But now I have installed on the institutes server (requested it). Again I meet the same problem:
No such file or directory: '/home/micmad/.stan_cache/cached-model-c4ed8c57c14f2eabbd4599b428df4a4c.pkl'

I do not have root access, making it hard to manually change the code. Is there a way to specify a location as your cache?

Thanks in advance
Michael

**Comment by ahartikainen** [comment]
Where do we use cache?

**Comment by s144117** [comment]
Sorry, entirely forgot that part:
compile_model(stanmodel_file)

**Comment by s144117** [comment]
Yes, it is stan_utility, simply followed [https://betanalpha.github.io/assets/case_studies/pystan_workflow.html](url)
which properly means I should ask this another place.

**Comment by ahartikainen** [comment]
Ok, yes, Add the issue in here https://github.com/betanalpha/jupyter_case_studies 

Currently, those functionalities should be in `pystan.diagnostics`, but potential updates are not hard-synced together. So you can probably use `pystan.diagnostics` functions.

**Comment by s144117** [comment]
Thank you!
