### ISSUE TITLE
Can't load fits generated from different linux distributions

### ISSUE THREAD

**Issue by jwalton3141** [stan-dev/pystan#554]
#### Summary:
I run pystan on two machines. One machine runs Ubuntu 16.04 and the other machine runs Centos 7.3

I can successfully run and save models and fits on each machine.

However, on the Ubuntu machine I can only load the model and fit that were compiled and run on the Ubuntu machine. That is, my Ubuntu machine will not load the fit that was created by the Centos machine.

The converse is also true: Centos will load the model and fit produced on Centos, but it will not load the model and fit from Ubuntu.

#### Example:

On both machines I run the 8 schools example from the pystan readthedocs page.

```py
#!/usr/bin/env python3

import pickle
import pystan
import platform

schools_code = """
data {
    int<lower=0> J; // number of schools
    vector[J] y; // estimated treatment effects
    vector<lower=0>[J] sigma; // s.e. of effect estimates
}
parameters {
    real mu;
    real<lower=0> tau;
    vector[J] eta;
}
transformed parameters {
    vector[J] theta;
    theta = mu + tau * eta;
}
model {
    eta ~ normal(0, 1);
    y ~ normal(theta, sigma);
}
"""

schools_dat = {'J': 8,
               'y': [28,  8, -3,  7, -1,  1, 18, 12],
               'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}

sm = pystan.StanModel(model_code=schools_code)
fit = sm.sampling(data=schools_dat, iter=1000, chains=4)

with open('{}_model.pkl'.format(platform.dist()[0]), "wb") as f:
	pickle.dump(sm, f, protocol=-1)

with open('{}_fit.pkl'.format(platform.dist()[0]), "wb") as f:
	pickle.dump(fit, f, protocol=-1)
```

This produces the files  ```Ubuntu_fit.pkl```, ```Ubuntu_model.pkl```, ```centos_fit.pkl``` and ```centos_model.pkl```. I copy over the pickle files so that both machines have all the files. Next I run the following on both machines:

```py
#! /usr/bin/env python3

import pickle
import platform

def try_load(file):
    try:
        with open(file, "rb") as f:
            _ = pickle.load(f)
        print("\n{} loaded {}\n".format(platform.dist()[0], file))
    except:
        print("\n{} couldn't load {}\n".format(platform.dist()[0], file))

files = ["Ubuntu_model.pkl", "Ubuntu_fit.pkl", "centos_model.pkl", "centos_fit.pkl"]

for file in files:
    try_load(file)
```

Running the above code on the centos machine I get:

```sh
user@centos$ ./load_test.py
WARNING:pystan:No module named 'stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_447963108405636165'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
centos loaded Ubuntu_model.pkl
centos couldn't load Ubuntu_fit.pkl
centos loaded centos_model.pkl
centos loaded centos_fit.pkl
```

And running the load code on my ubuntu machine I get

```sh
user@ubuntu$ ./load_test.py
Ubuntu loaded Ubuntu_model.pkl
Ubuntu loaded Ubuntu_fit.pkl
WARNING:pystan:No module named 'stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_3889597361207356136'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
Ubuntu loaded centos_model.pkl
Ubuntu couldn't load centos_fit.pkl
```

#### Versions:

On both OS's I am using pystan version 2.18.1.0 and numpy version 1.16.1.

On the Centos machine I have Cython version 0.29.4 and Ubuntu I have Cython version 0.29.5.

On the Centos machine I run Python 3.6.1 and on Ubuntu I run Python 3.5.2 (though I didn't think this should cause an issue)

#### Python versions:

I don't have sudo rights on either machine, so I haven't aligned python versions. I also didn't think this should be a problem, but if you do I can try building python from source on one of the machines to make sure both are running the same version.

**Comment by riddell-stan** [comment]
Unfortunately this is a known issue. Binary incompatibilities with 
compiled python extensions create the problem.

This will be fixed in PyStan 3.

**Comment by jwalton3141** [comment]
Thanks for the quick response. For anyone else who comes across this issue, a workaround is to use the ```df = fit.to_dataframe()``` method and pickle fits as pandas dataframe objects with ```df.to_pickle```

**Comment by ahartikainen** [comment]
You can also use ArviZ to save InferenceData -> netCDF4

**Comment by jwalton3141** [comment]
ArviZ looks like a good project. Since ```df.to_msgpack``` is still listed as experimental in pandas 0.24.1 it seems prudent to use ArviZ or stick to ```df = fit.to_dataframe()``` for now

**Comment by ahartikainen** [comment]
True, `msgpack` has been like that since ... beginning I guess.

**Comment by ahartikainen** [comment]
I just wonder if load stan fit function in experimental could handle this problem?
