### ISSUE TITLE
Setup error on python 3.7 with cython 0.29.6 (with proposed workaround)

### ISSUE THREAD

**Issue by dargor** [stan-dev/pystan#559]
#### Summary:
Compilation error when installing latest pystan release.

#### Description:
On python 3.6.8 with cython 0.29.6, installation from sdist works.
On python 3.7.2 with cython 0.29.6, installation from sdist does not work. When I download the source tarball from pypi and remove some cython generated files, I can build the wheel manually (see "proposed workaround").

#### Reproducible Steps:
`pip install --no-binary pystan --force-reinstall pystan` from a 3.7 venv.

#### Proposed workaround
Do not distribute cython generated files `_api.cpp`, `_chains.cpp` and `_misc.cpp` : make cython a required dep, and use it during pip build to recompile them instead.

#### Current Output:
```
[many errors like the following one]
    pystan/_misc.cpp:18836:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tstate->exc_traceback = *tb;
                 ^~~~~~~~~~~~~
                 curexc_traceback
```

#### Expected Output:
```
  Running setup.py install for pystan ... done
Successfully installed Cython-0.29.6 numpy-1.16.2 pystan-2.18.1.0
```

#### PyStan Version:
`2.18.1.0`

#### Python Version:
`3.7.2`

#### Operating System:
`Gentoo`

**Comment by cconw** [comment]
I'm running into this installation problem.  Can you be more explicit about the workaround?  I should remove the _api.cpp, _chains.cpp and _misc.cpp from the pystan distribution and then install?

**Comment by cconw** [comment]
I'm running into this installation problem. Can you be more explicit about the workaround? I should remove the _api.cpp, _chains.cpp and _misc.cpp from the pystan distribution and then install?

**Comment by dargor** [comment]
Sure, here what I have done : 
- download pystan-2.18.1.0.tar.gz from https://pypi.org/project/pystan/#files
- extract it and remove files `_api.cpp`, `_chains.cpp` and `_misc.cpp`
- build it whith `python setup.py bdist_wheel`
Then install the resulting wheel. Beware, the build consumes a lot of memory !

**Comment by ahartikainen** [comment]
Hmm, I wonder at what step at pip upload (twine?) takes the source.

I think you can just do pip install the folder after you have removed .cpp files unless you need the wheel later.

    pip install .

Is this only a problem with Gentoo (multilinux fails on Gentoo??).

What compiler are you using?

**Comment by dargor** [comment]
I don't think it's Gentoo fault, as it works with python 3.6 but fails with python 3.7.

Compiler is `gcc (Gentoo 8.2.0-r6 p1.7) 8.2.0` in both cases.

**Comment by dargor** [comment]
Same issue on Fedora with python 3.7 : https://github.com/mcfletch/pyopengl/issues/11

**Comment by ahartikainen** [comment]
Ok, so I believe the problem is in https://github.com/stan-dev/pystan-wheels

Has it used incompatible cython to generate wheels (or numpy?)?

```
Successfully installed Cython-0.29.2 numpy-1.15.4
Building libraries finished.
Looking in links: ...
Collecting numpy==1.14.5
```


cc. @riddell-stan

**Comment by riddell-stan** [comment]
@dargor It is odd that sdist doesn't work. It's not clear what's causing the problem. I don't think it's a Cython problem, as the commenters in the pyopengl mentioned.

The standard practice in the Python packaging world is to distribute the cpp files with the sdist.

The recommended installation method (which should work for more than 95% of users) is to use the binary wheels for their operating system.

**Comment by dargor** [comment]
The binary wheel works for x86_64, yes.

Closing since that's the general use case.
