### ISSUE TITLE
mean_par_names  VS sampler_param_names

### ISSUE THREAD

**Issue by Yanjiayork** [stan-dev/pystan#560]
#### Summary:

The return  of VB method is not including mean_par_names.  

#### Description:
What is the difference between "mean_par_names"  and "sampler_param_names"?

#### Reproducible Steps:
sm.vb(data=datadkt )

print(fit['sampler_param_names'])
print(fit['mean_pars'])
print(fit['mean_par_names '])

KeyError: 'mean_par_names '
#### PyStan Version:
2.17.1.0
#### Python Version:
3.5.2
#### Operating System:
MAC

**Comment by ahartikainen** [comment]
`mean_par_names` was added in 2.18. See https://github.com/stan-dev/pystan/pull/457
