### ISSUE TITLE
distutils.errors.CompileError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by s144117** [stan-dev/pystan#561]
#### Summary:
Compilation error on Pystan 2.18.1.0

#### Description:
I am running Pystan on a Linux environment. I am running Python 3.5.2 and gcc 4.4.7. When trying to run the Eight Schools example, I get the output below.
It should be noted that I am able to run this on my laptop (Win10) and this occurred after changing to my universities servers. I do not have permission to install anything on the servers and would therefore like an educated guess before I go running to the administrator. 
I have check my Cython version, it is newer than 0.22. (Issue [219](https://github.com/stan-dev/pystan/issues/219) )
There is no error telling me to install a development version of Python. (Issue [245](https://github.com/stan-dev/pystan/issues/245))
Issue [550](https://github.com/stan-dev/pystan/issues/550) seems to be IOS based, is I am not mistaken.
Several possible solution were found in issue [470](https://github.com/stan-dev/pystan/issues/470), still open. I do not have build-essential installed, this might be a solution.

Can you guys see anything obvious from my error message?

Thanks in advance!

#### Reproducible Steps:
**_Model described in .STAN file, called eight_schools_cp.stan:_**
data {
  int<lower=0> J;
  real y[J];
  real<lower=0> sigma[J];
}

parameters {
  real mu;
  real<lower=0> tau;
  real theta[J];
}

model {
  mu ~ normal(0, 5);
  tau ~ cauchy(0, 5);
  theta ~ normal(mu, tau);
  y ~ normal(theta, sigma);
}

**_In Python:_**
import pystan
import stan_utility
model = stan_utility.compile_model('eight_schools_cp.stan', verbose=True)

#### Current Output:
INFO:pystan:COMPILING THE C++ CODE FOR MODEL None_71b609c34d59a40b345b5328a36dbb39 NOW.
INFO:pystan:OS: linux, Python: 3.5.2 (default, Aug 18 2016, 15:01:11) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)], Cython 0.29.2
Compiling /tmp/tmppvnqbc6i/stanfit4None_71b609c34d59a40b345b5328a36dbb39_1695251132362266569.pyx because it changed.
[1/1] Cythonizing /tmp/tmppvnqbc6i/stanfit4None_71b609c34d59a40b345b5328a36dbb39_1695251132362266569.pyx
building 'stanfit4None_71b609c34d59a40b345b5328a36dbb39_1695251132362266569' extension
creating /tmp/tmppvnqbc6i/tmp
creating /tmp/tmppvnqbc6i/tmp/tmppvnqbc6i
gcc -Df2cFortran -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I/tmp/tmppvnqbc6i -I/pack/python_3.5.2/lib/python3.5/site-packages/pystan -I/pack/python_3.5.2/lib/python3.5/site-packages/pystan/stan/src -I/pack/python_3.5.2/lib/python3.5/site-packages/pystan/stan/lib/stan_math -I/pack/python_3.5.2/lib/python3.5/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3 -I/pack/python_3.5.2/lib/python3.5/site-packages/pystan/stan/lib/stan_math/lib/boost_1.66.0 -I/pack/python_3.5.2/lib/python3.5/site-packages/pystan/stan/lib/stan_math/lib/sundials_3.1.0/include -I/pack/python_3.5.2/lib/python3.5/site-packages/numpy/core/include -I/pack/python_3.5.2/include/python3.5m -c /tmp/tmppvnqbc6i/stanfit4None_71b609c34d59a40b345b5328a36dbb39_1695251132362266569.cpp -o /tmp/tmppvnqbc6i/tmp/tmppvnqbc6i/stanfit4None_71b609c34d59a40b345b5328a36dbb39_1695251132362266569.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++11
Traceback (most recent call last):
  File "/pack/python_3.5.2/lib/python3.5/site-packages/stan_utility/utils.py", line 211, in compile_model
    sm = pickle.load(open(cache_fn, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/micmad/Documents/stan_cache/cached-model-71b609c34d59a40b345b5328a36dbb39.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pack/python_3.5.2/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/pack/python_3.5.2/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/pack/python_3.5.2/lib/python3.5/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/pack/python_3.5.2/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/micmad/Documents/thesis/stan_test/test.py", line 31, in <module>
    model = stan_utility.compile_model('eight_schools_cp.stan', verbose=True)
  File "/pack/python_3.5.2/lib/python3.5/site-packages/stan_utility/utils.py", line 213, in compile_model
    sm = pystan.StanModel(model_code=model_code, model_name=model_name, **kwargs)
  File "/pack/python_3.5.2/lib/python3.5/site-packages/pystan/model.py", line 349, in __init__
    build_extension.run()
  File "/pack/python_3.5.2/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/pack/python_3.5.2/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
    self._build_extensions_serial()
  File "/pack/python_3.5.2/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
    self.build_extension(ext)
  File "/pack/python_3.5.2/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
    depends=ext.depends)
  File "/pack/python_3.5.2/lib/python3.5/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/pack/python_3.5.2/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

#### PyStan Version:
2.18.1.0

#### Python Version:
3.5.2

#### Operating System:
Scientific Linux realease 6.10 (Carbon)

**Comment by riddell-stan** [comment]
Is gcc 4.4.7 recent enough? I can't recall the lowest version supported. 
It's mentioned in the docs, I believe.

Could you try compiling the model (with verbose=True) without using 
stan_utility? I think we might get a better error message.

**Comment by s144117** [comment]
Circumventing stan_utility and using `verbose=True` did not yield any new information. (Did use verbose before).
It might be something to do with the gcc version.
If you don't mind, could you check [ahartikainen's comment](https://github.com/stan-dev/pystan/issues/470#issuecomment-400053499) to confirm that I understand it correct :)
I believe I need to upgrade to gcc 4.7 or higher.
[It](https://pystan.readthedocs.io/en/latest/whats_new.html) says Pystan v2.17.0.0 requires a C++11 compatible compiler.

**Comment by riddell-stan** [comment]
Sounds right to me. Try it with a gcc version >= 4.7.
