### ISSUE TITLE
Problem using StanModel

### ISSUE THREAD

**Issue by paulgGithub10** [stan-dev/pystan#576]
#### Summary:
I am new to pystan. I am having difficulty creating a StanModel. 

#### Description:
I am using mingw64 with gcc 8.1.0. Before, when I tried to run the example in the pystan installation guide for windows, it would say no MSVC compiler 1916. I edited the file cygwinccompiler.py, adding 

elif msc_ver == '1916':
            return ['vcruntime140']

I have a distutils.cfg file that says

[build]
compiler=mingw32

[build_ext]
compiler=mingw32

When I run the example now, I get:

command 'C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe' failed with exit status 1

What can I do? Thank you in advance.

**Comment by ahartikainen** [comment]
How did you install PyStan? Is this on cygwin?

**Comment by paulgGithub10** [comment]
I solved the problem. I didn't install the dependencies.

**Comment by MGES** [comment]
> I solved the problem. I didn't install the dependencies.

I met the same problem.How did you solve it?
