### ISSUE TITLE
Installing Pystan on Android

### ISSUE THREAD

**Issue by toidtoistic** [stan-dev/pystan#578]
#### Summary:

I've seen a couple of posts in which it seems as if installing `pystan` on Android (with Termux and `clang` is possible. I was wondering if there was a guide to do so, as I've been running into an error when attempting to install `pystan`.

#### Reproducible Steps:

Here's the command I've been using:
```
$ LDFLAGS=" -lm -lcompiler_rt" pip install -U pystan
```

#### Current Output:

I've been getting this error, primarily:
```
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-ry7jkr43/pystan/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-fs3xjrpt/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-ry7jkr43/py
```

Any help would be greatly appreciated, thanks!

**Comment by ahartikainen** [comment]
Download source and install from source (install numpy + cython first)

    git clone --recursive https://github.com/stan-dev/pystan
    cd pystan
    pip install -e .

But you might run out off RAM doing this.

**Comment by toidtoistic** [comment]
Thanks for the quick reply! Here's what I got:
```
Command "/data/data/com.termux/files/usr/bin/python -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/home/pystan/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /data/data/com.termux/files/home/pystan/
```

I wonder if it's because my version of python/`clang` are 3.7.3/7.0.1 respectively and I should downgrade?

**Comment by RSwarnkar** [comment]
Hello there, I am trying to install `pystan` on Termux App 0.76 on Android (Redmi Note 7 Pro) for `fbprophet` with all dependencies already installed. But the app crashes while building the app. I even tried taking wake lock. No help. I will upload the log with new issue if needed.

**Comment by ahartikainen** [comment]
I will close this issue, nothing we can do (see also #674 )
