### ISSUE TITLE
appveyor account -> pystan

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan#579]
There's a pystan organization account on appveyor. I believe riddell-stan and ahartikainen are both owners of it. It should be running the tests and (eventually) building wheels.

**Comment by ahartikainen** [comment]
That sounds good. Who can enable it? Should I disable my pystan first?

**Comment by riddell-stan** [comment]
Looks like you're not on the appveyor `pystan` team. I sent an email invitation to your aalto address. If that's not right, send me your new email address? (I wouldn't post it here, lest the spam bots get it.)

**Comment by ahartikainen** [comment]
I got the mail. I deleted pystan on my channel and it is now running on pystan channel.
