### ISSUE TITLE
pystan  error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by newbieh4cker** [stan-dev/pystan#587]
Environment.

OS : CentOS 7 x86_64
RAM : 5GB
Python 3.6.7
GCC 4.8 
Cython 0.29.7

![image](https://user-images.githubusercontent.com/23703741/56490791-5b346f80-6521-11e9-9fbb-6ffa1eebd112.png)

I used 'pip3' to install pystan (I can't use conda for some reason)

**Comment by ahartikainen** [comment]
You probably need newer compiler (4.9.x or 5+ for C++14 support).

What does `gcc --version()` gives?

Also what is your pystan version?

**Comment by newbieh4cker** [comment]
![image](https://user-images.githubusercontent.com/23703741/56491037-27a61500-6522-11e9-8fd0-904af74a8e42.png)


GCC : 4.8.5
pystan : 2.19.0.0

**Comment by newbieh4cker** [comment]
I just show #583.

downgrading pystan version to 2.18 worked
