### ISSUE TITLE
CompileError: command gcc.exe' failed with exit status 1

### ISSUE THREAD

**Issue by MGES** [stan-dev/pystan#589]
i got a problem and i have tried many ways but not works
I have used the create a new conda environment and follow all the steps in https://pystan.readthedocs.io/en/latest/windows.html,
but it can't solve the problem

windows7
Python 3.6.8
x86_64-w64-mingw32
gcc (Rev5, Built by MSYS2 project)5.3.0
pystan 2.18.1.0

CompileError: command gcc.exe' failed with exit status 1

`

import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)`

#### Current Output:

---------------------------------------------------------------------------
DistutilsExecError                        Traceback (most recent call last)
D:\setup\Python36\lib\distutils\cygwinccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    172                 self.spawn(self.compiler_so + cc_args + [src, '-o', obj] +
--> 173                            extra_postargs)
    174             except DistutilsExecError as msg:

D:\setup\Python36\lib\distutils\ccompiler.py in spawn(self, cmd)
    908     def spawn(self, cmd):
--> 909         spawn(cmd, dry_run=self.dry_run)
    910 

D:\setup\Python36\lib\distutils\spawn.py in spawn(cmd, search_path, verbose, dry_run)
     37     elif os.name == 'nt':
---> 38         _spawn_nt(cmd, search_path, dry_run=dry_run)
     39     else:

D:\setup\Python36\lib\distutils\spawn.py in _spawn_nt(cmd, search_path, verbose, dry_run)
     80             raise DistutilsExecError(
---> 81                   "command %r failed with exit status %d" % (cmd, rc))
     82 

DistutilsExecError: command 'D:\\setup\\Anaconda3\\envs\\test_env\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1

During handling of the above exception, another exception occurred:

CompileError                              Traceback (most recent call last)
<ipython-input-3-ef7f74b7bbad> in <module>
      1 model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
----> 2 model = pystan.StanModel(model_code=model_code)  # this will take a minute

D:\setup\Python36\lib\site-packages\pystan\model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, include_paths, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args)
    347 
    348         try:
--> 349             build_extension.run()
    350         finally:
    351             if redirect_stderr:

D:\setup\Python36\lib\distutils\command\build_ext.py in run(self)
    337 
    338         # Now actually compile and link everything.
--> 339         self.build_extensions()
    340 
    341     def check_extensions_list(self, extensions):

D:\setup\Python36\lib\distutils\command\build_ext.py in build_extensions(self)
    446             self._build_extensions_parallel()
    447         else:
--> 448             self._build_extensions_serial()
    449 
    450     def _build_extensions_parallel(self):

D:\setup\Python36\lib\distutils\command\build_ext.py in _build_extensions_serial(self)
    471         for ext in self.extensions:
    472             with self._filter_build_errors(ext):
--> 473                 self.build_extension(ext)
    474 
    475     @contextlib.contextmanager

D:\setup\Python36\lib\distutils\command\build_ext.py in build_extension(self, ext)
    531                                          debug=self.debug,
    532                                          extra_postargs=extra_args,
--> 533                                          depends=ext.depends)
    534 
    535         # XXX outdated variable, kept here in case third-part code

D:\setup\Python36\lib\distutils\ccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    572             except KeyError:
    573                 continue
--> 574             self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    575 
    576         # Return *all* object filenames, not just the ones we just built.

D:\setup\Python36\lib\distutils\cygwinccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    173                            extra_postargs)
    174             except DistutilsExecError as msg:
--> 175                 raise CompileError(msg)
    176 
    177     def link(self, target_desc, objects, output_filename, output_dir=None,

CompileError: command 'D:\\setup\\Anaconda3\\envs\\test_env\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1

**Comment by ahartikainen** [comment]
Is there any C++ error info if you define `verbose=True` for `StanModel`

**Comment by MGES** [comment]
just like this
"model = pystan.StanModel(model_code=model_code,verbose=True)"

but also met the problem
"
D:\setup\Python36\lib\distutils\cygwinccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    173                            extra_postargs)
    174             except DistutilsExecError as msg:
--> 175                 raise CompileError(msg)
    176 
    177     def link(self, target_desc, objects, output_filename, output_dir=None,

CompileError: command 'D:\\setup\\Anaconda3\\envs\\test_env\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1
"

**Comment by MGES** [comment]
> Is there any C++ error info if you define `verbose=True` for `StanModel`

just like this
"model = pystan.StanModel(model_code=model_code,verbose=True)"

but also met the problem
"
D:\setup\Python36\lib\distutils\cygwinccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
173 extra_postargs)
174 except DistutilsExecError as msg:
--> 175 raise CompileError(msg)
176
177 def link(self, target_desc, objects, output_filename, output_dir=None,

CompileError: command 'D:\setup\Anaconda3\envs\test_env\Library\mingw-w64\bin\gcc.exe' failed with exit status 1
"

**Comment by ahartikainen** [comment]
Can you see C++ errors? Those are traceback from python.

**Comment by MGES** [comment]
> Can you see C++ errors? Those are traceback from python.

emm.I am new to python.I am in China.

I just can see:

INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
INFO:pystan:OS: win32, Python: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)], Cython 0.29.6

Compiling C:\Users\MGES\AppData\Local\Temp\tmpjuu0j79y\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_7709233965744249539.pyx because it changed.
[1/1] Cythonizing C:\Users\MGES\AppData\Local\Temp\tmpjuu0j79y\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_7709233965744249539.pyx
building 'stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_7709233965744249539' extension
D:\setup\Anaconda3\envs\test_env\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -IC:\Users\MGES\AppData\Local\Temp\tmpjuu0j79y -ID:\setup\Python36\lib\site-packages\pystan -ID:\setup\Python36\lib\site-packages\pystan\stan\src -ID:\setup\Python36\lib\site-packages\pystan\stan\lib\stan_math -ID:\setup\Python36\lib\site-packages\pystan\stan\lib\stan_math\lib\eigen_3.3.3 -ID:\setup\Python36\lib\site-packages\pystan\stan\lib\stan_math\lib\boost_1.69.0 -ID:\setup\Python36\lib\site-packages\pystan\stan\lib\stan_math\lib\sundials_4.1.0\include -ID:\setup\Python36\lib\site-packages\numpy\core\include -ID:\setup\Python36\include -ID:\setup\Python36\include -c C:\Users\MGES\AppData\Local\Temp\tmpjuu0j79y\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_7709233965744249539.cpp -o c:\users\mges\appdata\local\temp\tmpjuu0j79y\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_7709233965744249539.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y -D_hypot=hypot -pthread -fexceptions

**Comment by MGES** [comment]
> Can you see C++ errors? Those are traceback from python.

I use the jupyter notebook.
and 

![cmd](https://user-images.githubusercontent.com/14008997/56798896-55ed6280-684a-11e9-8e61-122d0d795900.png)

**Comment by MGES** [comment]
maybe problem is:

--- cygwinccompiler.py
+++ cygwinccompiler.py
@@ -82,7 +82,18 @@ def get_msvcr():
         elif msc_ver == '1600':
             # VS2010 / MSVC 10.0
             return ['msvcr100']
+        elif msc_ver == '1700':
+            # Visual Studio 2012 / Visual C++ 11.0
+            return ['msvcr110']
+        elif msc_ver == '1800':
+            # Visual Studio 2013 / Visual C++ 12.0
+            return ['msvcr120']
+        elif msc_ver == '1900':
+            # Visual Studio 2015 / Visual C++ 14.0
+            # "msvcr140.dll no longer exists" http://blogs.msdn.com/b/vcblog/archive/2014/06/03/visual-studio-14-ctp.aspx
+            return ['vcruntime140']
         else:
+            # to do: can we make this futureproof?
             raise ValueError("Unknown MS Compiler version %s " % msc_ver)

**Comment by ahartikainen** [comment]
Can you scroll the c++ output and check if there is some error?

**Comment by MGES** [comment]
> Can you scroll the c++ output and check if there is some error?
Sorry. I don't know what you mean very well.
Did I need use some tools to scroll the c++ output?

![image](https://user-images.githubusercontent.com/14008997/56880791-b837a480-6a90-11e9-953e-18b66b9c5fe5.png)

**Comment by ahartikainen** [comment]
C++ can be found from the terminal (cmd.exe)

**Comment by MGES** [comment]
> C++ output can be found from the terminal (cmd.exe)

D:/setup/Anaconda3/envs/test_env/Library/mingw-64/include/c++/5.3.0/bits/c++0x_warning.h:32:2: error:
#error This file requires compiler and library support for the ISO C++ 2011 standard.This support is currently experimental,and must be enabled with the -std=c++11 or -std=gnu+11 compiler options.

**Comment by ahartikainen** [comment]
Ok, there is something weird going on with your installation. It is missing many needed compiler flags.

Can you remove the current installation and reinstall `pip install pystan`

**Comment by MGES** [comment]
> Ok, there is something weird going on with your installation. It is missing many needed compiler flags.
> 
> Can you remove the current installation and reinstall `pip install pystan`

Thank you.
If it doesn't work, maybe I should use the macOS.

**Comment by moniquebakker** [comment]
Hi! I get this same error `distutils.errors.CompileError: command 'C:\\Users\\name\\.conda\\envs\\stan_env\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1` in _debug_ mode, but not in a normal run. It happens both in pycharm and in VS code.

**Comment by ahartikainen** [comment]
Hi, can you create a new issue and we can fix your problem there.
