### ISSUE TITLE
command 'g++' failed with exit status 1

### ISSUE THREAD

**Issue by yzheng27** [stan-dev/pystan#596]
#### Summary:
Previously, i had error 'command 'gcc' failed with exit status 1', and after I upgrade my gcc, i have error message 'g++' failed with exit status 1' when I ran sm = pystan.StanModel(model_code=schools_code)

I am new to pystan, any help is appreciated. thanks!

#### Description:
Not sure if the following versions will help
g++ (MacPorts gcc5 5.5.0_4) 5.5.0
gcc (MacPorts gcc5 5.5.0_4) 5.5.0

#### Reproducible Steps:
I am using the example code at https://github.com/stan-dev/pystan

#### Current Output:
DistutilsExecError: command 'g++' failed with exit status 1

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### PyStan Version:
pystan 2.19.0.0
#### Python Version:
python 3.7.3
#### Operating System:
MacOS Mojave 10.14.4

**Comment by ahartikainen** [comment]
Hi, can you try to find c++ error msg?

If you are running this in jupyter notebook, error nsg can be found in terminal. Otherwise try to run with `verbose=True`.

It might be that you have wrong version for libc / libstdc.

**Comment by yzheng27** [comment]
Hi, below is the error msg.

INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_0fe254f3c524d4153537de9712f3f235 NOW.
INFO:pystan:OS: darwin, Python: 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)], Cython 0.29.7
Compiling /var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/stanfit4anon_model_0fe254f3c524d4153537de9712f3f235_4436498613922570104.pyx because it changed.
[1/1] Cythonizing /var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/stanfit4anon_model_0fe254f3c524d4153537de9712f3f235_4436498613922570104.pyx
building 'stanfit4anon_model_0fe254f3c524d4153537de9712f3f235_4436498613922570104' extension
creating /var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/var
creating /var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/var/folders
creating /var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/var/folders/kz
creating /var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/var/folders/kz/58drk88s4jb68znny445w43m0000gr
creating /var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/var/folders/kz/58drk88s4jb68znny445w43m0000gr/T
creating /var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/stan_env/include -arch x86_64 -I/anaconda3/envs/stan_env/include -arch x86_64 -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I/var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32 -I/usr/local/lib/python3.7/site-packages/pystan -I/usr/local/lib/python3.7/site-packages/pystan/stan/src -I/usr/local/lib/python3.7/site-packages/pystan/stan/lib/stan_math -I/usr/local/lib/python3.7/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3 -I/usr/local/lib/python3.7/site-packages/pystan/stan/lib/stan_math/lib/boost_1.69.0 -I/usr/local/lib/python3.7/site-packages/pystan/stan/lib/stan_math/lib/sundials_4.1.0/include -I/anaconda3/envs/stan_env/lib/python3.7/site-packages/numpy/core/include -I/anaconda3/envs/stan_env/include/python3.7m -c /var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/stanfit4anon_model_0fe254f3c524d4153537de9712f3f235_4436498613922570104.cpp -o /var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/stanfit4anon_model_0fe254f3c524d4153537de9712f3f235_4436498613922570104.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y
g++ -bundle -undefined dynamic_lookup -L/anaconda3/envs/stan_env/lib -arch x86_64 -L/anaconda3/envs/stan_env/lib -arch x86_64 -arch x86_64 /var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/stanfit4anon_model_0fe254f3c524d4153537de9712f3f235_4436498613922570104.o -o /var/folders/kz/58drk88s4jb68znny445w43m0000gr/T/tmp008c1o32/stanfit4anon_model_0fe254f3c524d4153537de9712f3f235_4436498613922570104.cpython-37m-darwin.so

**Comment by ahartikainen** [comment]
Ok, that is cython call. Then there is still C++ output. Can you try to run this with Jupyter Lab / Notebook? I think mac might hide that output when the code is executed on a terminal.

**Comment by yzheng27** [comment]
But right now, I do run this with jupyter notebook.

**Comment by ahartikainen** [comment]
Ah, that's good. Do you have your terminal open?

If not try to start jupyter from terminal

    activate base

or

    conda init

And then `cd` where you want and

    jupyter lab

or

    jupyter notebook

**Comment by yzheng27** [comment]
yes i have my terminal open and i start jupyter by source activate stan_env

**Comment by ahartikainen** [comment]
When compiling your model, do you see any output there?

**Comment by yzheng27** [comment]
No. sm = pystan.StanModel(model_code=schools_code, verbose=True) gives me an error message saying 'command 'g++' failed with exit status 1'.

**Comment by yzheng27** [comment]
Just now i typed
`sudo port select gcc none`
in the terminal. Now when i compile the model, it gives me the error 
`command 'gcc' failed with exit status 1`. Not sure what is causing these problems.

**Comment by ahartikainen** [comment]
Ok, your compiler is too old. You need 4.9.x or newer (I don't remember what was the first gcc compiler to give C++14 compatibility; Stan uses `-c++1y` == C++14 or newer).

**Comment by yzheng27** [comment]
I checked the post https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave and it fixed my problem. Thank you, Ari.
