### ISSUE TITLE
Initializing and saving mass matrix

### ISSUE THREAD

**Issue by s144117** [stan-dev/pystan#597]
Hi,

I have a few questions about the mass matrix. Not to the adaptation or anything, but is there a way to retrieve it?
And am I correct that only CmdStan has the possibility to initialize the mass matrix?

Best,
Michael

**Comment by bob-carpenter** [comment]
I don't know about the other interfaces, but CmdStan allows you to read in the mass matrix.  The service function in Stan now support input for the mass matrix, so the interfaces should be able to make it possible.

CmdStan outputs the estimated mass matrix in a CSV file in a structured way.  RStan also lets you retrieve the mass matrix, though again it's not part of the main line interface (there's a vignette on dealing with stan.fit objects).
