### ISSUE TITLE
No display of output from print statements in stan models

### ISSUE THREAD

**Issue by daeh** [stan-dev/pystan#598]
#### Summary:
I can't figure out how to display the output of stan's print statements.

#### Description:
In rstan and previous versions of pystan, pystan.sampling() displayed the output of print statements from the stan model. I haven't been able to access that information in version 2.19. Is there a new way to display the system output? I wasn't able to access it using logging or otherwise.

#### Reproducible Steps:
```python
schools_code = """
data {
    int<lower=0> J; // number of schools
    vector[J] y; // estimated treatment effects
    vector<lower=0>[J] sigma; // s.e. of effect estimates
}
parameters {
    real mu;
    real<lower=0> tau;
    vector[J] eta;
}
transformed parameters {
    vector[J] theta;
    theta = mu + tau * eta;
}
model {
    eta ~ normal(0, 1);
    y ~ normal(theta, sigma);
    print("target: ", target());
}
"""
schools_dat = {'J': 8, 'y': [28,  8, -3,  7, -1,  1, 18, 12], 'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}
sm = pystan.StanModel(model_code=schools_code)
fit = sm.sampling(data=schools_dat, iter=100, chains=4, verbose=True)
```

#### Current Output:
`WARNING:pystan:Rhat above 1.1 or below 0.9 indicates that the chains very likely have not mixed`

#### Expected Output:
Running the same in rstan gives
```
Chain 4: target: -43.1107
Chain 4: target: -41.9666
Chain 4: target: -42.3969
Chain 4: target: -43.1959
```

#### PyStan Version:
2.19.0.0
#### Python Version:
3.7.3
#### Operating System:
CentOS Linux release 7.4.1708 (Core)
MacOS 10.14.4

**Comment by ahartikainen** [comment]
Do you mean those `1/100 done` info?

**Comment by daeh** [comment]
That's probably what I need, yeah. I'm just wanting to see the output print statements in the `model{}` block (e.g. `print("target: ", target());` in this case) for debugging. I was expecting the `verbose` argument to give me the real-time sample output but it doesn't seem to. I presume I'm just missing something? Sorry if this is covered in the docs somewhere, I didn't see it.

Thanks!

**Comment by ahartikainen** [comment]
I'm not sure if those `Chain 4: target` are implemented in PyStan. I think they come from R, not C++.

IPython stdout is a bit weird / hard to get working on all the systems. I personally use jupyter lab, so I can see the C++ output in terminal window.

**Comment by daeh** [comment]
got it. thanks!

**Comment by bob-carpenter** [comment]
Do print statements in Stan programs show up in Jupyter Lab's terminal window and not in the standard Python REPL environments?  

It'd be nice to have print statements printing to the console whenever they're executed for purposes of debugging.

**Comment by ahartikainen** [comment]
> Do print statements in Stan programs show up in Jupyter Lab's terminal window and not in the standard Python REPL environments?

While running with Jupyter Lab / Notebook, the print statements from C++ go to the terminal.

https://stackoverflow.com/questions/46068321/jupyter-notebook-does-not-show-c-output-cout

With normal Python / IPython, it depends (on many system level things). On my Windows I can see the progress for chains in the main window and there is no way to silence this. For mac / linux it can be grabbed and silenced ( or processed).

But on some systems there is someting going on with the default output channels, that silence the output from C++.

**Comment by rmohajer** [comment]
I was wondering how can I open the terminal when running a Jupyter notebook in Jupyterlab.
This is what I need to see the print statements when running pystan.
