### ISSUE TITLE
Error while installing PyStan

### ISSUE THREAD

**Issue by Ram0987** [stan-dev/pystan#599]
#### Summary:
Hi, I tried to install pystan for Fb-Prophet in my Windows machine and encountered following error.

#### Error:

`Processing c:\python3.7.3\pystan-2.18.1.0.zip`

`Requirement already satisfied: Cython!=0.25.1,>=0.22 in c:\python3.7.3\lib\site-packages (from pystan==2.18.1.0) (0.29.7)`
`
Requirement already satisfied: numpy>=1.7 in c:\python3.7.3\lib\site-packages (from pystan==2.18.1.0) (1.16.3)`

`Installing collected packages: pystan`
`  Running setup.py install for pystan ... error`
`ERROR: Complete output from command 'c:\python3.7.3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\pip-req-build-03gsup3j\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Lenovo\AppData\Local\Temp\pip-record-5qoltswu\install-record.txt' --single-version-externally-managed --compile:`
`
ERROR: Compiling pystan/_api.pyx because it changed.
    Compiling pystan/_chains.pyx because it changed.
    Compiling pystan/_misc.pyx because it changed.
    [1/3] Cythonizing pystan/_api.pyx
    [2/3] Cythonizing pystan/_chains.pyx
    [3/3] Cythonizing pystan/_misc.pyx
    running install
    running build
    running build_py
    creating build
`
`...`

`TypeError: '>=' not supported between instances of 'NoneType' and 'str' ``----------------------------------------`
`ERROR: Command "'c:\python3.7.3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\pip-req-build-03gsup3j\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Lenovo\AppData\Local\Temp\pip-record-5qoltswu\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Lenovo\AppData\Local\Temp\pip-req-build-03gsup3j\`

I tried these methods, `pip install pystan` or `pip install pystan-2.19.0.0.tar.gz
` but all result in error as shown above.

I have installed visual studio Build Tools 2019 and Visual Studio Community 2019 - But i'm not sure I selected/installed all the required components. Kindly advise me on installing the required VS packages and how to solve the above error.

#### Operating System: Windows 10, 64 bit.

Thanks in advance!

**Comment by ahartikainen** [comment]
PyStan is not currently supported with MSVC.

See our Windows installation instructions found in docs.

https://pystan.readthedocs.io/en/latest/windows.html

**Comment by Ram0987** [comment]
@ahartikainen Thank you very much for your response. If i install another compiler e.g. GCC, will it affect any existing OS/software functionalities?

**Comment by ahartikainen** [comment]
It might, but there is high probability that PyStan is the only lib you have that does compilation while used. 

You can control what compiler is used with `distutils.cfg`. This means you can use VS to compile some modules, then change compiler to gcc and do your inference. Also, I think fbprophet compiles the models at the installation time, so you could try to just use gcc while installing PyStan+fbprophet.

You can have multiple Python environments with conda, so you could have one env for PyStan/fbprophet and other envs for something else.

**Comment by Ram0987** [comment]
@ahartikainen Thank you very much for your response. If i use Python 2.x (instead of 3.x), do i still need to change my compiler?

**Comment by ahartikainen** [comment]
Yes. This problem is with the `mvsc`, not python 2 / 3. On Windows I don't recommend using python 2.

**Comment by Ram0987** [comment]
Hi @ahartikainen , I have a question. I was able to install and run Pystan on my windows machine with Python 2 (a year before). Now i'm not able to. Is it because of any new Pystan version update?

**Comment by ahartikainen** [comment]
Yes. msvc still worked with older PyStan versions (2.15/2.16/2.17?), but even then the vectorization was broken.

**Comment by Ram0987** [comment]
oh okay. Thank you very much for the information!
