### ISSUE TITLE
Error when compile from source file

### ISSUE THREAD

**Issue by saravanansaminathan** [stan-dev/pystan#601]
#### Summary:
I am trying to compile the pystan git source in a docker environment

#### Description:
I want to generate a wheel file by compile the pystan from the source .
But while running the setup.py file error throws

#### Reproducible Steps:
I followed these steps provided by in the Pystan wiki page:
```
git clone --recursive https://github.com/stan-dev/pystan.git
cd pystan
python setup.py install
```

#### Current Output:
When I run 

> python setup.py install

I got this following error

`DISABLE_ASSERTS -Ipystan/stan/src -Ipystan/stan/lib/eigen_3.2.0 -Ipystan/stan/lib/boost_1.54.0 -I/usr/local/lib/python3.6/site-packages/numpy/core/include -c'
g++: pystan/stan/src/stan/agrad/rev/var_stack.cpp
g++: pystan/stan/src/stan/math/matrix.cpp
g++: pystan/stan/src/stan/agrad/matrix.cpp
g++: error: pystan/stan/src/stan/agrad/rev/var_stack.cpp: No such file or directory
g++: error: pystan/stan/src/stan/math/matrix.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
g++: fatal error: no input files
compilation terminated.
g++: error: pystan/stan/src/stan/agrad/matrix.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
error: Command "g++ -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -Ipystan/stan/src -Ipystan/stan/lib/eigen_3.2.0 -Ipystan/stan/lib/boost_1.54.0 -I/usr/local/lib/python3.6/site-packages/numpy/core/include -c pystan/stan/src/stan/agrad/rev/var_stack.cpp -o build/temp.linux-x86_64-3.6/pystan/stan/src/stan/agrad/rev/var_stack.o -MMD -MF build/temp.linux-x86_64-3.6/pystan/stan/src/stan/agrad/rev/var_stack.o.d" failed with exit status 1`

#### Expected Output:
I am trying to build a wheel file in my system using the source files available in github

#### PyStan Version:
2.19.0.0

#### Python Version:
3.6.1

#### Operating System:
Centos:7
GCC version -8.3.0

**Comment by ahartikainen** [comment]
Do you want to edit files? If not you can do

    pip install git+https://github.com/stan-dev/pystan

Also, make sure you have up-to-date compiler with C++14 support.

**Comment by saravanansaminathan** [comment]
My intention is to generate a wheel file in my own system. How to generate a wheel file for pystan?

**Comment by ahartikainen** [comment]
See `.travis.yml`

**Comment by saravanansaminathan** [comment]
what is the required GCC version and OS to generate the wheel file?

**Comment by ahartikainen** [comment]
I think any gcc > 5 should work

**Comment by saravanansaminathan** [comment]
`      File "/usr/local/lib/python3.6/site-packages/pystan/api.py", line 13, in <module>
        import pystan._api  # stanc wrapper
        ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by            /usr/local/lib/python3.6/site-packages/pystan/_api.cpython-36m-x86_64-linux-gnu.so)`

I compiled the wheel file in my centos:7 with gcc 8.3.0 . But still while installing I got this issue
Why it requires GLIBXCC 3.4.20.
In centos max available GLIBCXX is 3.4.19

**Comment by ahartikainen** [comment]
Hmm, no idea. This is after source is installed? How do you setup compiler tools.

Make sure that `CC` env value is correct.

Try

    #python setup.py install
    python -m pip install .

**Comment by ahartikainen** [comment]
Hi, did you have g++ installed too?

**Comment by saravanansaminathan** [comment]
> Hi, did you have g++ installed too?

Yes. I have it

**Comment by saravanansaminathan** [comment]
Instead of having normal gcc version. I installed the gcc of redhat using the following commands and it is working fine now
```
yum install centos-release-scl
yum install devtoolset-8-gcc*
scl enable devtoolset-8 bash
```
Old gcc version : (GCC)' 8.3.0 Copyright '(C)' 2018 Free Software Foundation, Inc.
New Gcc version : gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)

In centos pystan requires GLIBXCC 3.4.20. Redhat gcc helps to solve this problem. But I don't know how they did it
