### ISSUE TITLE
Add Windows Python 3.7 wheels to pypi

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan#603]
That is the current default versions users use. Can we upload wheel with twine?

**Comment by riddell-stan** [comment]
I must have lost track of this. I thought I had uploaded them / built them.

Looks like things are building on appveyor. I'll try to find the wheels.

**Comment by riddell-stan** [comment]
They have been built. Now hitting a file size limit with PyPI: https://github.com/pypa/warehouse/issues/5950

The Windows 64-bit wheel is ~77M, which is over the limit.

**Comment by ahartikainen** [comment]
What is the limit?

Can we remove something?

**Comment by riddell-stan** [comment]
That was fast, they raised the limit. See https://github.com/pypa/warehouse/issues/5950

**Comment by riddell-stan** [comment]
Uploaded.
