### ISSUE TITLE
Release PyStan 2.20

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan#619]
New version of Stan is out.

**Comment by ahartikainen** [comment]
Numpy distutils, same issue than httpstan?

**Comment by wds15** [comment]
I am not sure where the old issue is on static order init stuff...so let me comment here.

I just cloned pystan from git and got things running using python 2.7 under macOS. Everything seems to run just fine for me; including the example which uses `map_rect` which you posted here:

https://pystan.readthedocs.io/en/latest/threading_support.html

I was expecting to see segfaults, but I am getting a nice Stan sample.

How do I break it?

**Comment by ahartikainen** [comment]
That is interesting. What compiler did you use?

There is the first try:
https://github.com/stan-dev/pystan/pull/626

https://travis-ci.org/stan-dev/pystan/pull_requests

Segfault at the end
https://travis-ci.org/stan-dev/pystan/jobs/568978434

For mac (from httpstan) there is bus error:

https://travis-ci.org/stan-dev/httpstan-wheels

**Comment by wds15** [comment]
The default, I guess (I haven't changed anything)

```
[21:14:23][sebi@sebastians-mbp:~/work/pystan-bug]$ clang++ --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by wds15** [comment]
which python version should I use?

**Comment by ahartikainen** [comment]
I would recommend either python 3.6 or 3.7.

**Comment by riddell-stan** [comment]
Closing this. 2.21 is out. We're going to stick on 2.19.1 until we can figure out how to ship 2.21.

**Comment by wds15** [comment]
With the TBB in 2.21 there is hope that this STAN_THREADS issue resolves nicely... however, you will need a bit of C++ code to get things going in httpstan. Let me know once you are at the point of putting things together. Things like how many threads per chain / how big the threadpool is supposed to be need to be managed.
