### ISSUE TITLE
PARSER error in realising distributions

### ISSUE THREAD

**Issue by rmohajer** [stan-dev/pystan#621]
#### Summary:
PyStan does not identify std_normal() and other distributions. 

#### Description:
I am running a ML code on Guassian processes and using PyStan to solve the problem. I have written the code in Windows, Conda Jupyter notebook, python 3.7.3, and it works fine in there. However, due to lack of memory issue I use our HPC system , which is using Python 3.6.1, and Jupyter notebook. The system of HPC is Linux. Pystan is installed and can be called on the system. Unfortunately, I receive the following parser error:

ValueError: Failed to parse Stan model 'anon_model_2d955c928ca82dac780de8dd43af336b'. Error message:
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

No matches for: 

  real ~ std_normal()

Distribution std_normal not found. Require function with _lpdf or _lpmf or _log suffix
require real scalar return type for probability function.
  error in 'unkown file name' at line 29, column 30
  -------------------------------------------------
    27: model {
    28:         rho ~ inv_gamma(5, 5);
    29:         alpha ~ std_normal();
                                     ^
    30:         a ~ std_normal();
  -------------------------------------------------

#### Reproducible Steps:
This is the code I run:
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
gauss_reg_code = """
data {
    int<lower=0> n_train; //number of training data
    int<lower=0> D; //number of features
    vector[D]  X_train[n_train];
    int<lower=0, upper=1> Y_train[n_train];
    //real delta = 1e-9;
}
transformed data {}
    gauss_reg_code = """
data {
    int<lower=0> n_train; //number of training data
    int<lower=0> D; //number of features
    vector[D]  X_train[n_train];
    int<lower=0, upper=1> Y_train[n_train];
    //real delta = 1e-9;
}
transformed data {}
   
parameters {
    real<lower=0> rho;
    real<lower=0> alpha;
    real a;
    vector[n_train] eta;
}
transformed parameters {
        vector[n_train] f;
        matrix[n_train, n_train] L_K;
        // diagonal elements
        matrix[n_train, n_train] K = cov_exp_quad(X_train, alpha, rho);
        for(n in 1:n_train) {
            K[n, n] = K[n, n] + 1e-9;}
        L_K = cholesky_decompose(K);
        f = L_K * eta;
}
model {
        rho ~ inv_gamma(5, 5);
        alpha ~ std_normal();
        a ~ std_normal();
        eta ~ std_normal();
        Y_train ~ bernoulli_logit(a + f);
}
generated quantities {}
"""

gauss_reg_dat = {
    'n_train': n_train_g,
    'D': N,
    'X_train': X_train_imp_short,
    'Y_train': Y_train_int_short,
    }

fit_gaus = pystan.stan(model_code= gauss_reg_code, data=gauss_reg_dat, iter=2000, chains=1)
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

#### Current Output:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-709dc03f475e> in <module>()
     42     }
     43 
---> 44 fit_gaus = pystan.stan(model_code= gauss_reg_code, data=gauss_reg_dat, iter=2000, chains=1)

/apps/python/3.6.1/lib/python3.6/site-packages/pystan/api.py in stan(file, model_name, model_code, fit, data, pars, chains, iter, warmup, thin, init, seed, algorithm, control, sample_file, diagnostic_file, verbose, boost_lib, eigen_lib, n_jobs, **kwargs)
    381         m = StanModel(file=file, model_name=model_name, model_code=model_code,
    382                       boost_lib=boost_lib, eigen_lib=eigen_lib,
--> 383                       obfuscate_model_name=obfuscate_model_name, verbose=verbose)
    384     # check that arguments in kwargs are valid
    385     valid_args = {"chain_id", "init_r", "test_grad", "append_samples", "enable_random_init",

/apps/python/3.6.1/lib/python3.6/site-packages/pystan/model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args)
    211                                          model_name=model_name,
    212                                          verbose=verbose,
--> 213                                          obfuscate_model_name=obfuscate_model_name)
    214 
    215         if not isinstance(stanc_ret, dict):

/apps/python/3.6.1/lib/python3.6/site-packages/pystan/api.py in stanc(file, charset, model_code, model_name, verbose, obfuscate_model_name)
    131             msg = msg.encode('ascii', 'replace')
    132         error_msg = "Failed to parse Stan model '{}'. Error message:\n{}".format(model_name, msg)
--> 133         raise ValueError(error_msg)
    134     elif result['status'] == 0:  # SUCCESS_RC is 0
    135         logger.debug("Successfully parsed Stan model '{}'.".format(model_name))

ValueError: Failed to parse Stan model 'anon_model_2d955c928ca82dac780de8dd43af336b'. Error message:
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

No matches for: 

  real ~ std_normal()

Distribution std_normal not found. Require function with _lpdf or _lpmf or _log suffix
require real scalar return type for probability function.
  error in 'unkown file name' at line 29, column 30
  -------------------------------------------------
    27: model {
    28:         rho ~ inv_gamma(5, 5);
    29:         alpha ~ std_normal();
                                     ^
    30:         a ~ std_normal();
  -------------------------------------------------

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Python Version:
3.6.1
#### Operating System:
Linux

**Comment by ahartikainen** [comment]
What PyStan version do you have on the server?

**Comment by rmohajer** [comment]
I checked it out, it is written v-2.16

**Comment by ahartikainen** [comment]
I think you need to update your PyStan on the server or transform std_normal -> normal(0,1)

**Comment by rmohajer** [comment]
Thanks a lot Ari! 
It does answer my question.
