### ISSUE TITLE
conda-forge PyStan is 2.17.1.0 while Anaconda Cloud has 2.19.0.0

### ISSUE THREAD

**Issue by farr** [stan-dev/pystan#632]
#### Summary:
An outdated version of PyStan is on conda-forge, while the Anaconda default channel has the latest.  Because conda-forge recommends (and, for some packages, requires) that it live at higher priority than the default channel many users will not be able to access the Anaconda default.

#### Description:
See above.  This problem is fixable in several ways:

* By uploading the latest PyStan to conda-forge as well as Anaconda Cloud.  

* By removing PyStan from conda-forge.  Now users will default to the Anaconda Cloud installation even when following the approved procedure for adding the conda-forge channel to their conda installation.  Note that this is the recommended procedure from conda-forge for packages that appear in the Anaconda defaults channel as well.

**Comment by ahartikainen** [comment]
This needs to be fixed

https://github.com/conda-forge/pystan-feedstock/pull/24

**Comment by ahartikainen** [comment]
This is now fixed.
