### ISSUE TITLE
Function to separate divergent and non-divergent transitions

### ISSUE THREAD

**Issue by sursu** [stan-dev/pystan#634]
@betanalpha has a function `partition_div` [here](https://github.com/betanalpha/knitr_case_studies/blob/master/gaussian_processes/gp_part3/stan_utility.R). Pasted below:

```R
# Returns parameter arrays separated into divergent and non-divergent transitions
partition_div <- function(fit) {
  nom_params <- extract(fit, permuted=FALSE)
  n_chains <- dim(nom_params)[2]
  params <- as.data.frame(do.call(rbind, lapply(1:n_chains, function(n) nom_params[,n,])))

  sampler_params <- get_sampler_params(fit, inc_warmup=FALSE)
  divergent <- do.call(rbind, sampler_params)[,'divergent__']
  params$divergent <- divergent

  div_params <- params[params$divergent == 1,]
  nondiv_params <- params[params$divergent == 0,]

  return(list(div_params, nondiv_params))
}
```
I cannot find it in PyStan.
Is is implemented anywhere?

#### PyStan Version: 2.19.0.0

**Comment by ahartikainen** [comment]
Not in PyStan (at least I can't remember if there is one). One could use `.to_dataframe()` function and groupby

    df = fit.to_dataframe()
    div_split_dict = {"nondiv" if not key else "div" : values for key, values in df.groupby("divergent__")}

Or one option is to use `stan_utility` functions from https://github.com/betanalpha/jupyter_case_studies/blob/master/principled_bayesian_workflow/stan_utility.py

There is `partition_div` function

```
def partition_div(fit):
    """ Returns parameter arrays separated into divergent and non-divergent transitions"""
    sampler_params = fit.get_sampler_params(inc_warmup=False)
    div = numpy.concatenate([x['divergent__'] for x in
                            sampler_params]).astype('int')
    params = _shaped_ordered_params(fit)
    nondiv_params = dict((key, params[key][div == 0]) for key in params)
    div_params = dict((key, params[key][div == 1]) for key in params)
    return nondiv_params, div_params
```

**Comment by sursu** [comment]
Thank you, @ahartikainen !
You decide if you this function is worth including or not, and if not, please close the issue.

**Comment by ahartikainen** [comment]
I don't think we are going to add this functionality (at least not currently for PyStan2), and one can easily use @betanalpha excellent `stan_utility` file.
