### ISSUE TITLE
PyStan does not obey print() command

### ISSUE THREAD

**Issue by sursu** [stan-dev/pystan#635]
Example taken from [Robust GPs in Stan - Part 3](https://betanalpha.github.io/assets/case_studies/gp_part3/part3.html).

Stan file `gp_prior_tune.stan`:
```stan
functions {
  vector tail_delta(vector y, vector theta, real[] x_r, int[] x_i) {
    vector[2] deltas;
    deltas[1] = inv_gamma_cdf(theta[1], exp(y[1]), exp(y[2])) - 0.01;
    deltas[2] = 1 - inv_gamma_cdf(theta[2], exp(y[1]), exp(y[2])) - 0.01;
    return deltas;
  }
}

transformed data {
  vector[2] y_guess = [log(10), log(20)]';
  vector[2] theta = [2, 10]';
  vector[2] y;
  real x_r[0];
  int x_i[0];

  y = algebra_solver(tail_delta, y_guess, theta, x_r, x_i);

  print("a = ", exp(y[1]));
  print("b = ", exp(y[2]));
}
```

In R the following command spits 2 values, for `a` and `b` respectively:
```R
fit <- stan(file='gp_prior_tune.stan', iter=1, warmup=0, chains=1,
            seed=5838298, algorithm="Fixed_param")
```

That does not happen in PyStan with:

```python
sm = pystan.StanModel(model_code=gp_prior_tune)
fit = sm.sampling(iter=1, warmup=0, chains=1, seed=5838298, algorithm="Fixed_param")
```
(`gp_prior_tune` is now the model code from the file)

#### PyStan Version: 2.19.0.0

**Comment by ahartikainen** [comment]
Do you run with Jupyter Notebook? See the `terminal` where notebook have been opened.

    jupyter lab

or

    jupyter notebook

**Comment by sursu** [comment]
Yeah, I should have mentioned that.

You are right, the values are outputted, twice.

Thanks!

**Comment by yiyuezhuo** [comment]
@ahartikainen Is it possible to redirect the output from terminal to notebook? Otherwise one can not see output in a "pure notebook" environment such as colab.

**Comment by ahartikainen** [comment]
It is possible. We would need to wrap together python stdout and C++ stringstream.

**Comment by josealvarez97** [comment]
> @ahartikainen Is it possible to redirect the output from terminal to notebook? Otherwise one can not see output in a "pure notebook" environment such as colab.

Does this mean that, if I am using Google Colab, I can't debug PyStan by using the print command? @yiyuezhuo @ahartikainen . Isn't there any workaround?

**Comment by ahartikainen** [comment]
I think either pystan3 or cmdstanpy (with some hacks) can handle this.

    pip install pystan --pre

If you try cmdstanpy, you need to read and print stdout files.

Also, this might work:

https://gist.github.com/ahartikainen/06192df9719031cf1a22b887b7b5d67b

 But print, don't silence.
