### ISSUE TITLE
C++ compiler (pystan + fbprophet)

### ISSUE THREAD

**Issue by qrdbr** [stan-dev/pystan#645]
Summary:

Can not install C++ compiler with conda.
In my company I can use only pip. Conda is not allowed.
 

Description:

C:\Users\myuser>conda install libpython m2w64-toolchain -c msys2

Fetching package metadata ...

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/msys2/win-64/repodata.json>

Elapsed: -

 
An HTTP error occurred when trying to retrieve this URL.

HTTP errors are often intermittent, and a simple retry will get you on your way.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'conda.anaconda.org\', port=443): Max retries exceeded with url: /msys2/win-64/repodata.json (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, \'WSAECONNRESET\')",),))',),)

 

#### Reproducible Steps:

 

conda install libpython m2w64-toolchain -c msys2

 

I installed with pip a lot of packages: cufflinks ...sklearn ...plotly .. scipy …datetools …statsmodels …pandas

 
#### Current Output:

When I tried to run my .py that has a fbprophet import:

 
(C:\ProgramData\Anaconda3) C:\Users\myuser\pj_03_Pred>python F_Principal.py

Traceback (most recent call last):

  File "F_Principal.py", line 28, in <module>

    from   F6_Pred_FbProphet   import *

  File "C:\Users\myuser\pj_03_Pred\F6_Pred_FbProphet.py", line 13, in <module>

    from   fbprophet import  Prophet

  File "C:\ProgramData\Anaconda3\lib\site-packages\fbprophet\__init__.py", line 8, in <module>

    from fbprophet.forecaster import Prophet

  File "C:\ProgramData\Anaconda3\lib\site-packages\fbprophet\forecaster.py", line 17, in <module>

    import pystan  # noqa F401

  File "C:\ProgramData\Anaconda3\lib\site-packages\pystan\__init__.py", line 9, in <module>

    from pystan.api import stanc, stan

  File "C:\ProgramData\Anaconda3\lib\site-packages\pystan\api.py", line 13, in <module>

     import pystan._api # stanc wrapper

ImportError: DLL load failed: The specified module could not be found.

 

#### Expected Output:

I need an alternative option for the following instruction: 
conda install libpython m2w64-toolchain -c msys2

 
PyStan Version:
pystan 2.19.0.0

Python Version:
Python  3.6.3

Operating System:
Windows 10 Enterprise

**Comment by ahartikainen** [comment]
I can check if it is possible to manually download (this works with browser, they are basically compressed tar files) and unpack (this can be done with 7zip for example, or python).

Then they need to be put on the PATH or correct location.

**Comment by qrdbr** [comment]
I have download the packages
libpython-2.1-py37_0.tar.bz2 and
m2w64-toolchain-5.3.0-7.tar.bz2

After I installed with this comando

conda install --offline libpython-2.1-py37_0.tar.bz2 -c msys2

conda install --offline m2w64-toolchain-5.3.0-7.tar.bz2 -c msys2

But still not working


(C:\ProgramData\Anaconda3) C:\Users\myuser\pj_03_Pred>python F_Principal.py

Traceback (most recent call last):

File "F_Principal.py", line 28, in

from   F6_Pred_FbProphet   import *
File "C:\Users\myuser\pj_03_Pred\F6_Pred_FbProphet.py", line 13, in

from   fbprophet import  Prophet
File "C:\ProgramData\Anaconda3\lib\site-packages\fbprophet_init_.py", line 8, in

from fbprophet.forecaster import Prophet
File "C:\ProgramData\Anaconda3\lib\site-packages\fbprophet\forecaster.py", line 17, in

import pystan  # noqa F401
File "C:\ProgramData\Anaconda3\lib\site-packages\pystan_init_.py", line 9, in

from pystan.api import stanc, stan
File "C:\ProgramData\Anaconda3\lib\site-packages\pystan\api.py", line 13, in

 import pystan._api # stanc wrapper
ImportError: DLL load failed: The specified module could not be found.

**Comment by ahartikainen** [comment]
Can you try to install pystan and fbprophet again?

**Comment by ahartikainen** [comment]
Ok, you also need to install the toolchain parts

```
libpython
m2w64-binutils
m2w64-bzip2
m2w64-crt-git
m2w64-gcc
m2w64-gcc-ada
m2w64-gcc-fortran
m2w64-gcc-libgfortran
m2w64-gcc-libs
m2w64-gcc-libs-core
m2w64-gcc-objc
m2w64-gmp
m2w64-headers-git
m2w64-isl
m2w64-libiconv
m2w64-libmangle-git
m2w64-libwinpthread-git
m2w64-make
m2w64-mpc
m2w64-mpfr
m2w64-pkg-config
m2w64-toolchain
m2w64-tools-git
m2w64-windows-default-manifest
m2w64-winpthreads-git
m2w64-zlib
msys2-conda-epoch
```

**Comment by qrdbr** [comment]
I resolved this problem only with a copy of the 2 libraries belos

libpython-2.1-py37_0
m2w64-toolchain-5.3.0-7

from C:\ProgrData\Anaconda3\pkgs
to C:\ProgrData\Anaconda3\lib\site-packages

After this my . py execute properly.

Thanks for everyone!!!
