### ISSUE TITLE
summary() method of stanfit4model returns jumbled per-chain summaries

### ISSUE THREAD

**Issue by ianmtaylor1** [stan-dev/pystan#646]
#### Summary:
When calling the summary() method on a stanfit object, the per-chain summaries in the 'c_summary' array are incorrect.

#### Description:
I'm comparing the 'c_summary' array to what would be expected based on [this documentation](https://pystan.readthedocs.io/en/latest/api.html#pystan.StanFit4model.summary). The array appears to have the correct dimension, but the statistics in it are jumbled and out of order. The statistics in the 'summary' array appear correct, however.

#### Reproducible Steps:
```
import pystan

print("Pystan version {}".format(pystan.__version__))

model = """
parameters {
    real x;
    real<lower=0> y;
    real<lower=0,upper=1> z;
}
model {
    x ~ normal(0,1);
    y ~ exponential(1);
    z ~ uniform(0,1);
}
"""
fit = pystan.stan(model_code=model, iter=2000, warmup=1000, chains=4)
summary = fit.summary(['x','y','z'])

# Works as expected
print("Overall Summary")
print(summary['summary'].shape)
print(summary['summary_rownames'])
print(summary['summary_colnames'])
print(summary['summary'])

#Doesn't work as expected
print("\nPer-chain Summaries")
print(summary['c_summary'].shape)
for c in range(4):
    print("Chain {}:".format(c))
    print(summary['c_summary_rownames'])
    print(summary['c_summary_colnames'])
    print(summary['c_summary'][:,:,c])
```

#### Current Output:
```
Pystan version 2.19.0.0

...

Per-chain Summaries
(3, 7, 4)
Chain 0:
['x' 'y' 'z']
('mean', 'sd', '2.5%', '25%', '50%', '75%', '97.5%')
[[-0.02307199  0.01966731 -2.10222845  1.90486413  0.66493426  0.0052593  -0.60352653]
 [ 1.03294278  0.98448683  0.0414301   4.05733061  1.36258881  0.6333088   0.35498434]
 [ 0.5009154   0.50282996  0.02142389  0.97399295  0.74335219  0.50048433  0.26107641]]
Chain 1:
['x' 'y' 'z']
('mean', 'sd', '2.5%', '25%', '50%', '75%', '97.5%')
[[ 1.03533941  1.01674393 -0.73007723 -1.93315832  1.82265497  0.70875041  0.04871477]
 [ 1.03203243  1.05533867  0.29956665  0.017848    3.65183564  1.36072427  0.78556689]
 [ 0.29156898  0.28957028  0.25615317  0.02886532  0.96786329  0.76048625  0.52508856]]
Chain 2:
['x' 'y' 'z']
('mean', 'sd', '2.5%', '25%', '50%', '75%', '97.5%')
[[-0.01983724  0.07769435  0.03602894 -0.66088321 -1.99026842  2.06293935  0.77159257]
 [ 0.96146572  1.05986871  0.71884719  0.24340069  0.02526616  4.07677082  1.43740428]
 [ 0.49382109  0.50961477  0.50413717  0.22877532  0.0310972   0.97041891  0.75102874]]
Chain 3:
['x' 'y' 'z']
('mean', 'sd', '2.5%', '25%', '50%', '75%', '97.5%')
[[ 0.9882535   0.98934648  0.68239403 -0.04180734 -0.64374413 -1.78721296  2.00201341]
 [ 0.97278495  0.99830314  1.37040643  0.65294511  0.25705069  0.02450101  3.79587896]
 [ 0.29139673  0.28593755  0.74932309  0.49422176  0.24865417  0.02719876  0.98237372]]
```

#### Expected Output:
I would expect each entry `summary['c_summary'][:,:,c]` for `c` from 0 to 3 to be (approximately)
```
[[ 0.00  1.00 -1.96 -0.67  0.00  0.67  1.96]
 [ 1.00  1.00  0.03  0.29  0.69  1.39  3.69]
 [ 0.50  0.29  0.03  0.25  0.50  0.75  0.98]]
```
based on the correct means, standard deviations and quantiles of these distributions. You can see that these numbers are present, but in the wrong places.

#### PyStan Version:
2.19.0.0 (installed via conda from channel main)

#### Python Version:
3.7.3 (from conda)

#### Operating System:
Linux Mint 19.2, 
kernel version 4.15.0-65-generic, 
g++ version7.4.0

**Comment by ianmtaylor1** [comment]
I've found some additional information. I manually compared the output of `summary()` to my own calculations of means, standard deviations, and percentiles. It looks like the problem has to do only with the second axis (statistic) and the third axis (chain) of the array. The first axis (parameter) seems to be correct for everything. 

In other words, everything in `summary['c_summary'][0,:,:]` does indeed pertain to the parameter `x`, as it should. But the other two axes don't reference what they should.

**Comment by ahartikainen** [comment]
Is there some offset or order difference (does transpose "fix" this).

**Comment by ianmtaylor1** [comment]
I think so. I think there's a row-major/column-major mix up somewhere in the summary code. Specifially, my hunch is that it's either in the `misc._summary_sim` function or the `misc._combine_msd_quan` function.

The picture below is my full understanding of where things are in the c_summary array vs where they should be.
![stan_c_summary_shuffle](https://user-images.githubusercontent.com/2293284/66717665-c35d6300-ed98-11e9-9f81-5fbc3bca7efa.png)
For example, cell D8 says that where I would expect to find x's standard deviation for chain 2, I actually find x's mean for chain 3.
Here's the same file filtered down to only x's fields (i.e. `c_summary[0,:,:]`):
![stan_c_summary_shuffle_x](https://user-images.githubusercontent.com/2293284/66717748-c0af3d80-ed99-11e9-9417-01c5b6f92079.png)

Within the mean/sd part of the array, it looks like row-major and column major order were switched while inserting data. The same seems to have happened in the quantile part of the array.

Based on this, I think the error must either be in the `misc._summary_sim` function, which creates each of those portions of the array, or the `misc._combine_msd_quan` function, which appends them column-wise.
