### ISSUE TITLE
A couple of documentation issues on installation

### ISSUE THREAD

**Issue by smoh** [stan-dev/pystan#653]
- I think the link to 'detailed installation instruction' in README.md should be updated; right now it links to a fork of the repo which is outdated.
- Is there a reason why current [installation_beginner.rst](https://github.com/stan-dev/pystan/blob/develop/doc/installation_beginner.rst) is not reflected in the latest [documentation](https://pystan.readthedocs.io/en/latest/installation_beginner.html)? I find that I always need some additional guidance setting things up on a new system and it'd be great if I do not need to seek rst files in the repo.

**Comment by ahartikainen** [comment]
We update docs after release (and there was little problems with latest release (2.20))

**Comment by smoh** [comment]
I see.. perhaps the changes I am looking for fall between 2.19 and 2.20. I guess I should just wait for the second item and I made a small pull request just updating the link in README.
