### ISSUE TITLE
Release notes for PyStan 3.0 general release

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan#96]
Notes will accumulate here.

- [x] Acknowledge Jiale Zhi gh:@calio for the gift of the `stan` namespace on PyPI.
- [x] Thank @bgoodri for work on the user interfaces spec

**Comment by felixmartinsson** [comment]
I have a question, in Pystan 2 we got automatic output of e.g. Rhat and divergences through check_hmc_diagnostics. Is that gone in Pystan 3? 

Thanks for great work!

**Comment by riddell-stan** [comment]
We put in a plugin system with check_hmc_diagnostics in mind. Someone needs to write the plugin. Then users can, as an additional step, ``pip install pystan-hmc-diagnostics``, and everything will work basically the same as it did earlier. No additional configuration will be needed.

Someone does need to step up and write (and maintain) the plugin. Most of the code is already written.

**Comment by riddell-stan** [comment]
These items have been added to the draft release announcement. The release announcement will appear on https://discourse.mc-stan.org/
